### PR TITLE
Quadrat: added pagination to the query block

### LINKED ISSUE #3807: Quadrat: index/archive template is missing pagination

### PR DESCRIPTION
**Pull request by MaggieCabrera**
#### Changes proposed in this Pull Request:

This PR adds pagination to the query block so that we can have it for archive/index/blog pages:

Screenshot 2021-05-17 at 11 18 57

#### Related issue(s):

Closes #3807

### CODE REVIEW

**Review by jffng — COMMENTED** [review]
This works as advertised. @kjellr @beafialho could you weigh in on the design here? 

Screen Shot 2021-05-17 at 11 09 47 AM

**Comment by kjellr** [comment]
@jffng @MaggieCabrera: Let's use this mockup, based on the current post navigation:

Pagination

On mobile screens, it's ok to hide the page numbers so that this fits better: 

Pagination-Small

**Comment by MaggieCabrera** [comment]
This is ready for another review. 

Desktop:

Screenshot 2021-05-18 at 16 28 09

Mobile:

Screenshot 2021-05-18 at 16 25 56

**Comment by beafialho** [comment]
I think this looks good :+1:

**Comment by kjellr** [comment]
This looks good, thanks @MaggieCabrera. One small comment: 

On the first page (when there's no "Previous Page" link), can we still center the page numbers? Currently it looks like this: 

Screen Shot 2021-05-18 at 10 43 17 AM

(Same thing for the last page, when there's no "Next Page" link).

**Comment by MaggieCabrera** [comment]
> This looks good, thanks @MaggieCabrera. One small comment:
> 
> On the first page (when there's no "Previous Page" link), can we still center the page numbers? Currently it looks like this:
> 
> (Same thing for the last page, when there's no "Next Page" link).

Oh, that's tricky because it's using flexbox, mmmh I'll see what I can come up with.

**Comment by MaggieCabrera** [comment]
ok, grid to the rescue!

Screenshot 2021-05-18 at 16 59 01
Screenshot 2021-05-18 at 16 59 47

**Review by kjellr — APPROVED** [review]
Looks good! I did notice that the page is bumping right up against the  edges of the screen on mobile — I'm not sure when that happened? But I'm seeing it in `trunk` too. 🤔

**Comment by MaggieCabrera** [comment]
> Looks good! I did notice that the page is bumping right up against the edges of the screen on mobile — I'm not sure when that happened? But I'm seeing it in `trunk` too. 🤔

I've seen it too, I'm going to open a separate issue for that, thanks Kjell!

**Pull request merged**
