### PR TITLE
OutNow: add theme

### PR DESCRIPTION
**Pull request by henriqueiamarino**
OutNow is the perfect theme for our users who are engaged in artistic activities. Its concise and straightforward introduction enables users to promptly select topics for their blog posts or content pages.

screenshot

### CODE REVIEW

**Comment by jasmussen** [comment]
Nice theme! Let me try a review of this one and please let me know if the following feedback is useful or not. I've plenty of things to learn, so let me know any best practices I should absorb.

**General feedback/opinion**

This is a cool subversive take on an upside down theme, with what is traditionally "footer material" shown instead at the top of the page, rather than at the bottom. I love it! I am wondering about the "Designed with WordPress" credit, however, if it wouldn't still be useful to have that in the actual footer. It can be smaller, if need be. Or if you really want it at the top, could it sit on the right, below "Coming next" and "Hiring the band"? Main motivation: if we can find something that's slightly more informative as the first sentence on the page, it might be more useful to readers that start in the top left corner. Not a strong opinion, but a thought.

Love the theme. Especially exploring the templates you've built. The staging site is down for the moment, so I can't validate, but from the templates it looks like the posts will show up in a grid and allow you to explore the subpages. That's good.

Mostly a personal preference, the theme with its grid and non-rounded images feels sharp. So it might be nice to have sharp corners on buttons too?
Screenshot 2024-06-24 at 16 22 50

Style variations look great, I notably like this one:
Screenshot 2024-06-24 at 16 25 20

Is it worth trying some additional typography there? I often connect jazz themes with Clarendon, or something like [this](https://fonts.google.com/specimen/Besley). Typography only style variations, and color only style variations are coming too, so for the "full" style variations I find it's often good to mix things up a bit more than just color.

**Things worth addressing**

I’d note that the main H1 link currently links hard-codedly to [a staging website](https://theoutnow.mystagingwebsite.com/blog/). It should probably not link anywhere.

On the theme, I notice the header and footer are lowercase:

Screenshot 2024-06-24 at 15 55 37

Can these be titlecase? @beafialho do you have any best practices here? It's a tiny detail but would be nice. This affecs all the template parts, and if I'm misunderstanding something here let me know!

The search block here looks a bit tight:

Screenshot 2024-06-24 at 16 22 33

Maybe this can default to the search-button-inside configuration?

Screenshot 2024-06-24 at 16 32 59

The readme file looks good. A couple of small things, though:

> OutNow is the perfect theme for our users who are engaged in artistic activities. Its concise and straightforward introduction enables users to promptly select topics for their blog posts or content pages.

Can you delete "our users" and just write "people"? So:

> OutNow is the perfect theme for people who are engaged in artistic activities. Its concise and straightforward introduction enables users to promptly select topics for their blog posts or content pages.

On this one:

> All images used in the templates were generated with AI using Midjourney.

I'd love to include that these are CC0. Perhaps something simpler like "Generated with AI on Midjourney, released under the CC0 license".

Also, just to be sure: is this image AI generated? (If yes, wow.)

Screenshot 2024-06-24 at 16 32 13

**Comment by beafialho** [comment]
Thanks for your first review Joen!

> Can these be titlecase? @beafialho do you have any best practices here? It's a tiny detail but would be nice. This affecs all the template parts, and if I'm misunderstanding something here let me know!

My guess is that they're written like that in Block Canvas, and we often use that as a base theme. Personally, I don't think it's a matter of high importance and I don't change them. If it bothers us collectively too much though, we could create an issue to make that small change to Block Canvas?

> Mostly a personal preference, the theme with its grid and non-rounded images feels sharp. So it might be nice to have sharp corners on buttons too?
> Is it worth trying some additional typography there? I often connect jazz themes with Clarendon, or something like [this](https://fonts.google.com/specimen/Besley).

I agree these would be nice touches 👌

> I’d note that the main H1 link currently links hard-codedly to [a staging website](https://theoutnow.mystagingwebsite.com/blog/). It should probably not link anywhere.

For placeholder links, I always just type in `#`. This avoids this issue, but it still creates a "link".

**Comment by jasmussen** [comment]
Great feedback, all sounds good to me!

**Comment by henriqueiamarino** [comment]
Hey, @jasmussen, thanks for the feedback.
Before any other comment, here is the [demo site](https://outnow.mystagingwebsite.com/). As this site is named The Stage in Dotcom, I forgot to clone it on Pressable, but I'll do it and complement all other PRs with such links.

- I confirm the image is AI, as we chatted on Slack. I've added the CC0 mention to readme.txt;
- The title case issue was explained by @beafialho's comment. Thanks Bea;
- Search-button-only is now implemented;

The type suggestion was very convenient; thanks. I've been using Besley for related topics, too; I just didn't think of it at the time. I added it to two of the style variations.

**Comment by jasmussen** [comment]
Demo site looks fantastic, and changes sound great to me. 

It _sounds_ like the next step is to update this PR, then we can merge it. Sound good?

**Comment by jasmussen** [comment]
Nice work. Readme looks good, changes look good and test well in Playground.

I wonder: should a site title be included somewhere ont he front page? The following counts as the h1:_

Screenshot 2024-06-25 at 09 51 28

And on the test site, all looks good. I'm mainly comparing the out-of-box experience:

Screenshot 2024-06-25 at 09 50 18

Screenshot 2024-06-25 at 09 50 23

Depending on the answer, I don't know if that's a thing to address or not, for now it's mostly a question. Otherwise, this looks good to go!

Meta: I need to learn the process here, so a quick CC to @mikachan for _awareness_ of this particular review, but no urgency to respond.

**Comment by henriqueiamarino** [comment]
@jasmussen this 'READ THE MSGRS' is a link to the Blog, where all the posts are. When I create sites with a Front Page such as this one, I always think it's necessary. But I agree that this should be better explained. Maybe I'll write in Themeshaper to introduce the theme on the post.

When I use a 'large' site logo like that, I prefer not to include the site title to avoid repetition. But users will always have the chance to change that.

Anyway, I agree with you that the out-of-the-box experience is strange, and it happens all the time, with all themes. I really support demo content, but I know this is a problematic argument for WordPress.

**Comment by jasmussen** [comment]
Cool, let's try moving forward with this then!

**Pull request merged**
