### PR TITLE
Blockbase: Move block styles to theme.json

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
We can set list typography in the theme.json now, we don't need to do it in custom, so this is just a simplification.

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
I'm running the latest from GB trunk and blockbase is not showing fontfamily for ol/ul:

Screenshot 2021-06-17 at 14 32 19

**Comment by scruffian** [comment]
I changed the approach here. We don't need to declare the font at all, since themes can just use theme.json when they want to change it now.

There are also some new templates that come from rebuilding the child themes which should have happened in a different PR.

**Comment by pbking** [comment]
Looks like the related PR was closed in favor of this one.
This might still need some work to support that particular change, but there are conflicts so I'm moving out of "review" until those are resolved.

**Comment by scruffian** [comment]
This is rebased and good to go.

**Review by pbking — APPROVED** [review]
Good to Go Indeed.
🚢

**Pull request merged**
