### PR TITLE
Archeo: Headline over dark image pattern

### PR DESCRIPTION
**Pull request by MaggieCabrera**
#### Changes proposed in this Pull Request:

I created this pattern as a cover block with 100vh and added it to "pages" category, I'm not sure if that's the correct way to go about this one. I also had trouble reproducing the image masking from the design. Figma shows that blend mode is "pass-through" and I'm not sure if we can even do that with CSS. @beafialho @kjellr what do you think about this? It looks bad with 70 opacity with the #242321 overlay. 

Screenshot 2022-02-04 at 16 11 59

#### Related issue(s):

https://github.com/Automattic/themes/issues/5429

### CODE REVIEW

**Comment by beafialho** [comment]
Thanks @MaggieCabrera, I tried to do that in the editor and if you use ` #242321` with 80% opacity it should look as intended:

Captura de ecrã 2022-02-04, às 15 19 45

Here's the code from my attempt: https://gist.github.com/beafialho/7b98243a03918da02aa054ad83358a1e

**Comment by MaggieCabrera** [comment]
> Here's the code from my attempt: https://gist.github.com/beafialho/7b98243a03918da02aa054ad83358a1e

That helps a lot! The main problem was the base image I was using, with yours it looks nice now. Thank you!!

**Comment by beafialho** [comment]
Looks great 👍

**Comment by MaggieCabrera** [comment]
Oh, @beafialho I forgot, do you have an alt text for this image?

**Review by mikachan — APPROVED** [review]
I guess we should merge when we've added the alt text, but this looks great to me!

**Comment by scruffian** [comment]
If you need to merge so we can add more patterns we can always update the alt text later

**Comment by kjellr** [comment]
Alt text: "Photo of the Governor's Palace at Uxmal"

**Pull request merged**
