### PR TITLE
Downtown: add theme

### PR DESCRIPTION
**Pull request by henriqueiamarino**
Downtown was designed as a spin-off of Vetro, a theme with wide-width layouts, generous space for images, and bold type sizes. Its pages have wide content blocks that allow viewers to focus on visuals and short paragraphs.

[Site demo](https://downtown.mystagingwebsite.com/)

screenshot

### CODE REVIEW

**Comment by iamtakashi** [comment]
Hi @henriqueiamarino, here are the notes I've noticed.

* Not sure if it needs the side gaps. It's up to you, though. 
* The border-radius is awkward on small screens. It looks like they come from the cover block.
CleanShot 2024-11-06 at 14 13 37@2x
 
* In Pages and Single Posts, the theme uses a Columns block to make the layout, but I suggest using a group block with "justify items left" instead. In this way, the width of the content doesn't stretch more than 900px of the theme-specified width, and it's better for medium screens because there is no empty column. You could do the same for 404 templates if you like it.
CleanShot 2024-11-06 at 14 46 10@2x
CleanShot 2024-11-06 at 14 37 11@2x 

* There are quite a few font size settings without using a preset. For a better UX, a font size should always use a preset. 
  * In `theme.json`, `core/button`,  `core/button.variations.outline`, `core/comment-author-name`, `core/comment-date`, `core/comment-reply-link`, `core/read-more`, and `core/site-title` 
  * These four elements on the archive, the index, and the search templates. For the post-date and the post-terms block, you can just reselect the extra small size, and that should fix it.
CleanShot 2024-11-06 at 17 23 39@2x
  * On the front-page template,
CleanShot 2024-11-06 at 17 15 55@2x
CleanShot 2024-11-06 at 17 17 39@2x
  * On the single posts template, 
CleanShot 2024-11-06 at 17 27 56@2x
* The font Source Serif Pro isn't used. Let's remove it.
* `patterns/about.php`, `pattern/hidden-404.php`, `patterns/single.php`, and `small-about.php` don't seem to be used anywhere. Let's remove it.
* Let's remove the credit for Source Serif from `readme.txt`
* Since there are no patterns from the theme that show up in the inserter, let's remove `block-patterns` tag from the stylesheet header.
* Minor issue. I commonly see "fullwidth" to be spelt "full-width" or "full width"
CleanShot 2024-11-06 at 13 53 10@2x

**Comment by henriqueiamarino** [comment]
Thanks for the review, @iamtakashi. It's strange, but those elements were already using Font presets. Anyway, I just replaced the REM codes on theme.json, and I hope they are now fixed.

Screenshot 2024-11-07 at 10 26 22

**Comment by henriqueiamarino** [comment]
All the following issues were addressed and fixed:

- Removed unnecessary columns (Single, Pages, and 404) and used blocks and alignment;
- Removed the cover block corners and the padding that added side gaps to the hero;
- Manually replaced all the "0.75 rem" font sizes for "var(--wp--preset--font-size--medium)";
- Renamed the custom template for 'Page without Sidebar' > this is more informative;
- Deleted Source Serif Pro and its credits from readme;
- Removed unused: patterns/about.php, pattern/hidden-404.php, patterns/single.php, and small-about.php;
- Removed block-patterns tag from style.css.

**Comment by iamtakashi** [comment]
I'm unsure why some elements with the x-small size have `0.75rem` in the templates. It might have been a bug in the editor at some point. For those elements, select a different size once and select the x-small again. That should fix it.

There are still many elements with non-preset sizes, though. Go through those elements that I pointed out above. Once you have done it, search `fontSize` in the theme files in your text editor, such as VS Code or like that. Basically, you don't want to see a font size with a number. all of them should have a preset name like `x-small`, `large`, and so on. In this way, when a user changes the size of a preset, all the elements with the size change at once.
CleanShot 2024-11-07 at 11 38 51@2x

**Comment by henriqueiamarino** [comment]
You're right, @iamtakashi. I fixed them in theme.json, but there were still issues with patterns and styles that needed to be fixed. I checked them using VSC global search, and hopefully, they are all fixed now.

**Comment by iamtakashi** [comment]
Thanks for the update, @henriqueiamarino. I found three more. 
CleanShot 2024-11-07 at 14 06 58@2x
CleanShot 2024-11-07 at 14 08 44@2x

**Comment by henriqueiamarino** [comment]
Oh, man... this is being reverted when I save the theme using CBT. I am 100% sure there was none in the theme.json and patterns. Anyway, I'll try again @iamtakashi.

**Comment by henriqueiamarino** [comment]
@iamtakashi, this time, I only updated the necessary lines using VSC. I didn't save using the CBT. I hope these are now fixed.

**Comment by iamtakashi** [comment]
Almost. In JSON, you want it to be `var(--wp--preset--font-size--x-small)` instead of just `x-small` :) 

CleanShot 2024-11-07 at 17 04 43@2x

**Comment by henriqueiamarino** [comment]
Thanks, @iamtakashi :P
It makes sense... theme.json is now fixed.

**Comment by iamtakashi** [comment]
It looks good to me. Ship it! 🚢

**Comment by henriqueiamarino** [comment]
**Downtown** was renamed **Urbem** and is now submitted as #8424.

**Pull request merged**
