### PR TITLE
Varia: Add vertical margins to blocks inside Jetpack’s Layout Grid block.

### LINKED ISSUE #1672: Varia: Block inside Layout Column block don't have vertical margins
We have the vertical margins for blocks immediately inside `entry-content`, but when you add something inside in a layout grid block, there are no vertical margins.

Screenshot 2019-11-19 at 14 07 30

### PR DESCRIPTION
**Pull request by allancole**
#### Changes proposed in this Pull Request:

Adds the same vertical margin logic used in `.entry-content` to content within the Layout Grid. 

**Before**|**After**
------------|------------
image|image

#### Related issue(s):

- Fixes #1672 

#### ToDo:

- [ ] Recompile all child themes

### CODE REVIEW

**Comment by iamtakashi** [comment]
Thank you for the fix! LGTM 👍

**Comment by allancole** [comment]
No prob! I’ll run the all-child-themes recompile tool today or tomorrow and merge it.

**Comment by iamtakashi** [comment]
@allancole I'll go ahead and merge this now since it's been a few days, and we need to get this in before the next deployment.

**Comment by michaeldcain** [comment]
The child themes are being rebuilt in #1716

**Pull request merged**
