### PR TITLE
Fix errors for redefined functions

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
These redeclared functions is causing errors. We need to add a check.

### CODE REVIEW

**Review by jffng — COMMENTED** [review]
Should the following functions also be wrapped in a `function_exists` for safety?

`hex_to_rgb`
`rgb_to_lum`
`rgb_to_hsvl`

These themes appear to redeclare them also.

**Review by MaggieCabrera — APPROVED** [review]
LGTM

**Comment by scruffian** [comment]
I added the other checks @jffng suggested, so this will need another review

**Comment by jffng** [comment]
I tested this on wpcom and verified that the custom color HSL calculations are working. LGTM.

**Pull request merged**
