### PR TITLE
New theme: Ibis

### PR DESCRIPTION
**Pull request by ianstewart**
👋🏻  Hi! This PR is the first commit of a new, proposed, block-based child theme of Seedlet named _Ibis_. It was forked from Seedlet Blocks, and is a work-in-progress towards a variation that more closely aligns with some of the defaults the WP.com View Team has come to expect from our favourite Varia-based themes on WP.com. It's named after a bird because birds are cool.

There are several things wrong, potentially wrong, or unfinished with it. Here's a few todo items off the top of my head.

- The header template part needs updating.
- The editor styles don't match the front-end.
- The default palette is probably lame in practice.
- The grid proportions need to be adjusted down to mobile.
- The screenshot.png file still shows off Seedlet Blocks.

That list can likely be extended to greater length. :)

Here's a screenshot of the current front-end status featuring a nice block pattern courtesy of @iamtakashi.

image

cc @iamtakashi @alaczek @rickybanister

### CODE REVIEW

**Comment by ianstewart** [comment]
Updated the header template part to be more vertically compact by default with a wide width. Here's a longer screenshot showing it off with some more patterns.

image

**Comment by kjellr** [comment]
This is cool! I love that it's possible to iterate and create a new-feeling theme with such little extra code. If you find that it's easiest to merge this and continue improving from there in separate PRs, please go ahead and do so. We can always remove it later on if we decide to. 👍

**Comment by ianstewart** [comment]
Awesome. 

>  love that it's possible to iterate and create a new-feeling theme with such little extra code.

Agreed. Overriding the vars in style.css or the experimental json file is pretty clever.

> We can always remove it later on if we decide to.

Plus one and my thoughts exactly. I may also test this on WPcom with, say, Gutenboarding, and also just with new Patterns and Layouts — but with the same criteria. Easy enough to remove later. :) But having the PR merged will make that (and team collaboration) easier.

**Comment by iamtakashi** [comment]
Wow, nice! This is super cool 👍👍👍👍

**Comment by ianstewart** [comment]
> 👍👍👍👍

PRs welcome. :)

**Comment by apeatling** [comment]
Looks great, nice work @ianstewart!

**Pull request merged**
