### PR TITLE
Bibliophile: add theme

### PR DESCRIPTION
**Pull request by madhusudhand**
#### Changes proposed in this Pull Request:

Adds the new theme `bibliophile` designed by @beafialho 

image

### CODE REVIEW

**Comment by madhusudhand** [comment]
Fixed the general issues.

@beafialho The post-meta shows `By <categores>` as follows

image

The prefix `BY` suggests it to be author name instead of categories. Can you confirm?

**Comment by beafialho** [comment]
Yes @madhusudhand, that's correct. Good catch. 

I set it up as categories because I wanted to have different "authors" in the demo, and naming them as categories was the only way to do that.

Captura de ecrã 2023-06-28, às 10 36 15

**Comment by beafialho** [comment]
The only thing is that I don't remember if I set Post Author to look exactly like the Categories, could you confirm?

**Comment by madhusudhand** [comment]
There isn't a post-author-name definition in any of the templates, but if I place one, yes it looks exactly like categories.

image

Also, in the `single` template, there isn't a comments block. is it intentional?

**Comment by beafialho** [comment]
Ok, it looks as intended. Thanks for checking.

> Also, in the single template, there isn't a comments block. is it intentional?

Yes, that's intentional.

**Comment by madhusudhand** [comment]
Ready to 🚢

**Pull request merged**
