### PR TITLE
Videomaker: Add dynamic template references

### LINKED ISSUE #4858: Videomaker: Post Meta template part
## Steps to replicate
On WordPress.com, the block patterns have an error because they try to use the template part block, which isn't supported in WordPress.com yet. We'll need to find a different solution for now.

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
The theme slug needs to be dynamic in the block-template block, as it depends where the theme is installed.

#### Related issue(s):
Fixes https://github.com/Automattic/themes/issues/4858

### CODE REVIEW

**Comment by pbking** [comment]
Looks like it's writing the markeup:
```
<!-- wp:template-part {"slug":"post-meta","theme":"pub/blockbase"} /-->
```

which doesn't seem to work.  Manually changing the block markup to this does:

```
<!-- wp:template-part {"slug":"post-meta","theme":"pub/videomaker"} /-->
```

I think the concept will work, but should be writing the current them not parent theme?

**Comment by MaggieCabrera** [comment]
you'd want [get_stylesheet_directory()](https://developer.wordpress.org/reference/functions/get_stylesheet_directory/) maybe? it doesn't work without the theme attribute??

**Comment by scruffian** [comment]
Oh yeah sorry, it's actually `get_stylesheet`. Updated.

**Comment by pbking** [comment]
> it doesn't work without the theme attribute??

From what I understand (and can tell tinkering with this branch) it works without the theme attribute in a block template (i.e. the index.html block template) but not in the content.

**Review by pbking — APPROVED** [review]
Creates the pattern w/ reference to block template part as expected:
```
<!-- wp:template-part {"slug":"post-meta","theme":"pub/videomaker"} /-->
```

Tested locally and on wpcom.

🚢

**Pull request merged**
