### PR TITLE
Add Stitchery

### PR DESCRIPTION
**Pull request by scruffian**

### CODE REVIEW

**Comment by iamtakashi** [comment]
Blocked for the dotorg submission due to the use of AI images

**Comment by alaczek** [comment]
I'm going to have to swap out all the images in this one (generated on the wrong Midjourney plan).

**Comment by iamtakashi** [comment]
Hi @alaczek, will this theme still be worked on?

**Comment by alaczek** [comment]
Thanks for the ping - it fell of my radar. As mentioned earlier I will have to generate all new imagery. I'll get on with it when I'm back in January. In the meantime I will close this PR, and start a new one when ready.

**Pull request closed without merging**
