### PR TITLE
Independent Publisher: Add theme styles to the editor so that fonts match

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
This adds the theme styles to the editor so that the frontend and the editor match. Ideally we wouldn't need editor styles at all, but the post title requires them, and maybe other blocks do to...

#### Related issue(s):
Part of #3280

### CODE REVIEW

**Review by jffng — APPROVED** [review]
This fixes the issue of the incorrect fonts loading in the editor.

**Comment by jffng** [comment]
Should the minor version number be bumped?

**Comment by scruffian** [comment]
Changed to local file references and bumped the version number.

**Comment by scruffian** [comment]
I also removed the `.edit-post-visual-editor` selector from editor-blocks.css. When this file is added as an editor style then the `.editor-styles-wrapper` prefix is added, so `.edit-post-visual-editor` won't work. I also renamed `.editor-block-list__block` to `.block-editor-block-list__block` since the class has changed names in Gutenberg.

**Comment by scruffian** [comment]
I updated the approach here to remove as many editor styles as possible. This is ready for another review.

**Comment by jffng** [comment]
This is being affected in the same way that Penscratch was, where some styles are leaking into the editor UI:

Screen Shot 2021-02-19 at 9 12 20 AM

**Pull request closed without merging**
