### PR TITLE
MyMenu: add theme

### PR DESCRIPTION
**Pull request by henriqueiamarino**
My Menu is a simple theme designed to facilitate restaurant owners’ site-building experiences. It is clean, direct, and customizable. Test the cool style variations that have been added to the theme.
[Demo site](https://mymenu.mystagingwebsite.com/)

screenshot

### CODE REVIEW

**Comment by jasmussen** [comment]
**General visual observations**

This is really nice. I quite like the logo with a plate on it, the font looks strong, and the layout looks very street-food in that it could be printed on recycled paper. 

I like that these things align:

Screenshot 2024-07-03 at 09 26 57

Note: on the _demo site_, these lines don't line up:

Screenshot 2024-07-03 at 09 26 09

But they do line up in the playground test, so the PR appears good.

The logo doesn't take me to the homepage:

Screenshot 2024-07-03 at 09 30 52

It's just an image, can you change it to the Site Logo block?



Using emoji here is fun:

Screenshot 2024-07-03 at 09 27 46

Mobile looks good, which is important for this one. I like the centered menu button:

Screenshot 2024-07-03 at 09 32 11

**Template review**

Templates look good. For some reason on the Index page, the second vertial line in the menu doesn't line up with the second vertical line in the header:

Screenshot 2024-07-03 at 09 34 55

It works, more or less, on the front page:

Screenshot 2024-07-03 at 09 36 14

Not a blocker, not sure what it is, and it's small anyway.

This is a note to self, we really need to provide better options for styling inputs. We're very limited here still, right @beafialho ?
Screenshot 2024-07-03 at 09 34 33

One thing we need to fix, there's a bit of a typo on the 404 page:

Screenshot 2024-07-03 at 09 34 24

Perhaps just "We're sorry" and delete the next line?

**Style variations**

I _love_ the color variations:

Screenshot 2024-07-03 at 09 39 00

and I love that the logo through the magic of duotone, also transforms. That's a seductive detail. This duotone should still be possible via a site logo.

I know this is already on your radar, so this is only feedback going forward: would be good with some typography changes in these style variations too, and even spacing changes if need be (sometimes the line-heights need massaging too).

**File and readme reviews**

Looks good!

**Summary**

This is a great little theme. Beyond any other changes you might choose to make, if you can fix the site logo, this one is good to go.

**Comment by henriqueiamarino** [comment]
Thanks @jasmussen.
Yes, I'll check all the column misalignments that should not happen. Unfortunately, styling inputs are still very limited.

I'd like to discuss the site logo here. The previous version had it there, but the theme lost all its mojo with that empty element hanging by the top. Also, the site logo element is square, and it doesn't contribute much to restaurant owners, as the majority of them use horizontal branding due to facades.

In defense of the site logo, there's the link issue, which I miss here. What if we could link this image locally to `home`?

**Comment by jasmussen** [comment]
The site logo can be rectangular, no? 

Screenshot 2024-07-03 at 10 29 46

I understand that the logo you designed here is important for the demo content, but surely that can live in the demo site, assigned as a site logo? Here's what that looks like when I test:

Screenshot 2024-07-03 at 10 31 17

Yes, the out of box experience will have an empty logo. But it won't be misleading since restaurant owners will need to replace it regardless.

**Comment by henriqueiamarino** [comment]
Alright, this was easily adjusted as almost all issues were okay on the previous version.

**Comment by henriqueiamarino** [comment]
Yet again, the PR was destroyed by a push to the trunk while I was committing the change. I cloned it 20 minutes ago, but it was not enough. 
@jasmussen As I don't know how to fix it, I'll close this one and create a new one to merge.

**Comment by jasmussen** [comment]
No worries. This feedback is still valid for the new PR, so the new PR can also be merged with the site logo change you made. Nice!

**Pull request closed without merging**
