### PR TITLE
Skatepark: Fix social links navigation alignment on desktop

### LINKED ISSUE #4590: Skatepark: Social Links navigation is not properly aligned on desktop
It's a little too high, and a little off to the right. 

---

Current:

Screen Shot 2021-09-14 at 2 24 47 PM

Intended: 

Screen Shot 2021-09-14 at 2 24 29 PM

### PR DESCRIPTION
**Pull request by danieldudzic**
Closes #4590

### CODE REVIEW

**Review by scruffian — APPROVED** [review]
LGTM

**Comment by scruffian** [comment]
Deployed in D67205-code

**Comment by kjellr** [comment]
I'm not sure this solved the issue. here's what I'm seeing:

Screen Shot 2021-09-22 at 9 19 45 AM

... but here's what I expect:

Screen Shot 2021-09-22 at 9 19 45 AM

**Comment by kjellr** [comment]
I'm still seeing the same on the demo site as well: 

Screen Shot 2021-09-22 at 9 28 44 AM

**Pull request merged**
