### PR TITLE
Update/ponyfill to styles

### PR DESCRIPTION
**Pull request by scruffian**
Quick rename for the stylesheet for consistency with other themes.

### CODE REVIEW

**Comment by pbking** [comment]
https://github.com/Automattic/themes/blob/f1698a833e810016df1a2b7b208c6bcfb25f899a/blank-canvas-blocks/package.json#L35

That will need some love too I think.

**Comment by scruffian** [comment]
I merged the ponyfill with the existing style.css.

**Comment by pbking** [comment]
It doesn't appear to merge, but replace losing the meta info.
I didn't initially realize that was the .css file you were targeting.  
Because that's the source of meta, and so that we DON'T have to keep that in 2 places (styles.css/styles.scss) (as we do with other themes) which can become out-of-sync I would much prefer to target a separate file unless there is a technical reason not to.  I don't much care what it's called, but I was hoping it wouldn't be /style.css

**Review by jffng — COMMENTED** [review]
Should this PR also remove the `ponyfill.css` file? I don't see that deletion...

**Comment by scruffian** [comment]
It should if we go with it. We seem divided :)

**Comment by scruffian** [comment]
We decided not to do this.

**Pull request closed without merging**
