### PR TITLE
Update RITRATTO

### LINKED ISSUE #7593: Update/Fix Theme RITRATTO
I want to request an update for Ritratto, as several necessary fixes were conducted.

## Issue
We had various issues with settings and styling, and they are all fixed now. Besides fixing the theme, I also added three new color styles that will help this theme perform better on the showcase.

## Results
The theme is ready to be updated by the following file:
[ritratto.zip](https://github.com/Automattic/themes/files/13863056/ritratto.zip)

screenshot

### PR DESCRIPTION
**Pull request by mikachan**
#### Changes proposed in this Pull Request:
This includes the changes from @henriqueiamarino made to RITRATTO from the zip included in https://github.com/Automattic/themes/issues/7593.

#### Related issue(s):
Fixes https://github.com/Automattic/themes/issues/7593

### CODE REVIEW

**Review by vcanales — APPROVED** [review]
LGTM

**Comment by creativemf** [comment]
Hello Sarah Norris! pardon my interrupting this unrelated thread! But as you are a very savvy Engineer, of course its muy dificil (and probably invasive) to contact you regarding Wordpress theme issues off hours? I hope you don't mind? I've got a bit of an emergency after I tried to upgrade a wpcom-premium theme (not hosted) _ and I think I broke the theme path somehow? i dunno ...see **(https://edvicek12.com/)**
ALL the subsequent PAGES and POST now redir to THIS: **https://edvicek12.com/sales/** and I decided to stop hacking as not to screw it up permanently? I hope you can help me by Thursday sometime? Cheers x Ben  (a fan and phenotype)

**Comment by creativemf** [comment]
U deleted my comment? why to try to cull me to BUY your shYte products? ... Whats with all this 'fake helpful' bollocks, when all you guys are really doing is building a hostile geek wall around your little made up world? you create BIAS in your product and you defend it by cordoning off any detractors. How boring and lonely ... and ultimately USELESS

**Comment by vcanales** [comment]
@creativemf your original message was off-topic for the thread and repo, and your second message is absolutely inappropriate.

If you have trouble with a Premium Theme, there are appropriate channels to get support, listed [here](https://wordpress.com/support/themes/premium-themes/).

**Pull request merged**
