### PR TITLE
Skatepark: theme.json: add margin/spacing settings + content layout

### LINKED ISSUE #4316: Skatepark: theme.json: Margin/spacing settings + content layout
Add Skatepark default spacing settings and content layout values:

Screenshot 2021-07-27 at 13 05 21

### PR DESCRIPTION
**Pull request by mikachan**
#### Changes proposed in this Pull Request:
This change adds the default margin settings and content sizes for Skatepark.

#### Sense Check
It's my first time using a Figma design and setting up a theme, so thought it might help to say where I got my sizes from in case I've completely confused myself.

The default margin sizes are from the 'Styles' section of the design (also included in #4316).

The layout `contentSize` I based on the width of the content from the design here:

contentsize

And the layout `wideSize` I based on the width of the container with a border:

widesize

#### Related issue(s):

Closes #4316

### CODE REVIEW

**Comment by pbking** [comment]
Changes are all in the right place. G2G there.

The numbers make sense according to the design but would like to get confirmation from @melchoyce that the contentSize and wideSize are as intended.

**Comment by MaggieCabrera** [comment]
These changes need to be done on child-theme.json rather than on theme.json (and then theme.json gets generated with the build command), otherwise it looks good to me

**Comment by melchoyce** [comment]
Settings LGTM 👍

**Comment by mikachan** [comment]
Ahh thanks @MaggieCabrera, I've moved the settings to child-theme.json.

Thanks all!

**Review by MaggieCabrera — APPROVED** [review]
Let's bring this in then!

**Pull request merged**
