### PR TITLE
Varia: Fix shopping cart menu issue

### LINKED ISSUE #2022: Varia: Adding/removing menu items to the Customizer adds shopping carts
## Steps to replicate

1. Set theme to Exford
2. WooCommerce Plugin is active
3. Add a Menu item to the Menu in the Customizer

I also duplicated this on my test site where the only additional plugin was WooCommerce and I had the same results. 

## Result

For every Menu item added, an extra shopping cart appears in the Customizer.
When you switch to view the live site, the shopping carts do not display.

**Screenshots are from my test site.**
Customizer:
Screen Shot 2020-05-14 at 4 30 00 PM

Live SIte:
Screen Shot 2020-05-14 at 4 30 19 PM

## Expected

When a menu item is added, instead just 1 shopping cart should remain.

* User report: [Chat #20965267-hc]
* Follow-up ticket: [ #2975294-zd]

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #2022 

**Issue:**

Every time a menu item got added to or removed from the primary menu, an additional cart icon had been added to the primary menu.

**Fix:**

1. Get option `varia_cart_icon`
2. If primary menu if empty or if option `varia_cart_icon` does not exist, set the option to `false`
3. If the option is set to `false`, add the cart icon to the primary menu and set the option to `true`

## Alves

<table>
<tr>
<td>Before:
<br><br>

#2022-Alves-before
</td>
<td>After:
<br><br>

#2022-Alves-after
</td>
</tr>
</table>

## Balasana

<table>
<tr>
<td>Before:
<br><br>

#2022-Balasana-before
</td>
<td>After:
<br><br>

#2022-Balasana-after
</td>
</tr>
</table>

## Barnsbury

<table>
<tr>
<td>Before:
<br><br>

#2022-Barnsbury-before
</td>
<td>After:
<br><br>

#2022-Barnsbury-after
</td>
</tr>
</table>

## Brompton

<table>
<tr>
<td>Before:
<br><br>

#2022-Brompton-before
</td>
<td>After:
<br><br>

#2022-Brompton-after
</td>
</tr>
</table>

## Coutoire

<table>
<tr>
<td>Before:
<br><br>

#2022-Coutoire-before
</td>
<td>After:
<br><br>

#2022-Coutoire-after
</td>
</tr>
</table>

## Dalston

<table>
<tr>
<td>Before:
<br><br>

#2022-Dalston-before
</td>
<td>After:
<br><br>

#2022-Dalston-after
</td>
</tr>
</table>

## Exford

<table>
<tr>
<td>Before:
<br><br>

#2022-Exford-before
</td>
<td>After:
<br><br>

#2022-Exford-after
</td>
</tr>
</table>

## Hever

<table>
<tr>
<td>Before:
<br><br>

#2022-Hever-before
</td>
<td>After:
<br><br>

#2022-Hever-after
</td>
</tr>
</table>

## Leven

<table>
<tr>
<td>Before:
<br><br>

#2022-Leven-before
</td>
<td>After:
<br><br>

#2022-Leven-after
</td>
</tr>
</table>

## Mayland

<table>
<tr>
<td>Before:
<br><br>

#2022-Mayland-before
</td>
<td>After:
<br><br>

#2022-Mayland-after
</td>
</tr>
</table>

## Maywood

<table>
<tr>
<td>Before:
<br><br>

#2022-Maywood-before
</td>
<td>After:
<br><br>

#2022-Maywood-after
</td>
</tr>
</table>

## Morden

<table>
<tr>
<td>Before:
<br><br>

#2022-Morden-before
</td>
<td>After:
<br><br>

#2022-Morden-after
</td>
</tr>
</table>

## Redhill

<table>
<tr>
<td>Before:
<br><br>

#2022-Redhill-before
</td>
<td>After:
<br><br>

#2022-Redhill-after
</td>
</tr>
</table>

## Rivington

<table>
<tr>
<td>Before:
<br><br>

#2022-Rivington-before
</td>
<td>After:
<br><br>

#2022-Rivington-after
</td>
</tr>
</table>

## Rockfield

<table>
<tr>
<td>Before:
<br><br>

#2022-Rockfield-before
</td>
<td>After:
<br><br>

#2022-Rockfield-after
</td>
</tr>
</table>

## Shawburn

<table>
<tr>
<td>Before:
<br><br>

#2022-Shawburn-before
</td>
<td>After:
<br><br>

#2022-Shawburn-after
</td>
</tr>
</table>

## Stow

<table>
<tr>
<td>Before:
<br><br>

#2022-Stow-before
</td>
<td>After:
<br><br>

#2022-Stow-after
</td>
</tr>
</table>

## Stratford

<table>
<tr>
<td>Before:
<br><br>

#2022-Stratford-after
</td>
<td>After:
<br><br>

#2022-Stratford-before
</td>
</tr>
</table>

### CODE REVIEW

**Comment by dphyled** [comment]
Hi there @allancole! A ticket popped up in the queue waiting on this PR, and I noticed that the PR has been waiting for review since May 15th with no one assigned. You were listed as a "Suggested reviewer" in the GH sidebar, so I hit the Request button, but please let me know if we should request from someone else. Thank you!

**Review by jeffikus — COMMENTED** [review]
In principle this should be able to be merged and deployed on Monday - I have a few more test scenarios I'd like to run this through before we get this merged.

**Review by jeffikus — APPROVED** [review]
LGTM - tested in Varia.

**Review by allancole — APPROVED** [review]
Yup, this looks good! 
LGTM :-)

**Review by allancole — DISMISSED** [review]
So I decided to test this out again before deploying and it looks like there’s an issue with this change. 

For some reason, the mini-cart seems to disappear on both the frontend and in the customizer. I could see it fine when I first went to the customizer and started changing menu items and it stopped duplicating the mini-cart. But after I published my changes, the mini-cart went away and there’s no way to get it to reappear afterward. 

Before|After
------------|------------
image|Screenflick Movie 80

**Comment by dougaitken** [comment]
@nielslange are you able to take a look at this, please?

**Comment by nielslange** [comment]
> @nielslange are you able to take a look at this, please?

Sure, I'll look into this issue the next days and will ping @allancole for another review when I'm done.

**Comment by nielslange** [comment]
@allancole Based on https://github.com/Automattic/themes/pull/2024#pullrequestreview-468699011, I reviewed my PR and adjusted it accordingly. Feel free to run another test to see if the fix behaves as expected now.

CC: @dougaitken

**Comment by allancole** [comment]
Just did some testing with your latest commits @nielslange and the issue is still there, unfortunately. I cannot see the mini-cart at all on this PR and im not sure why. When I revert your changes, the mini-cart reappears but the duplicating issue comes back :-/

**Comment by MaggieCabrera** [comment]
This is ready for another review

**Review by scruffian — APPROVED** [review]
LGTM

**Pull request merged**
