### PR TITLE
CastCore: add theme

### PR DESCRIPTION
**Pull request by henriqueiamarino**
Welcome podcast producers about to board this journey. CastCore is a theme designed to be your first podcast site.

[Demo site](https://castcore.mystagingwebsite.com/)

screenshot

### CODE REVIEW

**Comment by alaczek** [comment]
I looked at this one only briefly and noticed a couple things:
* the content mismatch - the copy in the footer is about plants, while the author bio is of Matt. Would it make sense to create a fictional persona? Sidebar pattern also mentions Josepha... are WordPress.org references on purpose here?
* related to above the Subscribe button in the author pattern is a link to subscribe to Matt's podcast - we should probably remove that?
* the comments.html template part is not used, so should be ok to remove.

**Comment by henriqueiamarino** [comment]
Hey, @alaczek, thanks for this.
Yes, the content here needs to be improved. The theme was created based on the existing podcast Josepha was producing, WP Briefing. Now that she has left, I replaced it with Matt's old _Distributed_ show. Do you have another one to suggest if this is not okay?
- The comments should be used on the single page; I'll fix that.
- I'll also check the Subscribe button; that was a good catch.

**Comment by alaczek** [comment]
> Do you have another one to suggest if this is not okay?

No, it's just that I personally steer clear of using real people in default theme content, as it will appear on thousands of sites. But you have the full background on this theme, so it's your call.

**Comment by henriqueiamarino** [comment]
Okay, I can always use suggestions; that's why I am asking. Anyway, I also checked with Anne here at the meetup, and she said repeating content would not help SEO, so I'll change everything.

**Comment by henriqueiamarino** [comment]
@iamtakashi, after replacing all the content and conducting other necessary fixes, I believe this is ready to be reviewed.

**Comment by iamtakashi** [comment]
Thanks. As soon as I finish reviewing Coach Ava, I'll review this.

**Comment by iamtakashi** [comment]
@henriqueiamarino Here are notes I've noticed.

* I understand the intention, but it's a pity that the navigation quickly goes on two lines because the third column is narrow. It's not ideal, especially for small screens. Consider using a row block instead of a column block in the header, the navigation is set to right-aligned anyway. It's up to you, though. 
CleanShot 2024-10-29 at 15 27 34@2x 
CleanShot 2024-10-29 at 15 49 17@2x
* In the page template, a block spacing was given to the main columns block, creating a misalignment.
CleanShot 2024-10-29 at 15 53 20@2x
* There is no `main` tag in the search results template. 
* There is an empty paragraph block in the single post template. 
CleanShot 2024-10-29 at 16 03 51@2x
* Figtree 600 normal and italic are bundled but not registered in the JSON file.
* Revise the registration for Outfit. There seem to be a few errors there. 
CleanShot 2024-10-29 at 16 29 09@2x
* `portrait_photomatt.jpg` is no longer used. Remove it.
* Since the `also-available` template part has text strings that must be internationalised, it needs to be converted to a pattern. The steps are:
1. Create a new file called `also-available.php` in `/patterns`, and paste this.
```
<?php
/**
 * Title: Also Available
 * Slug: castcore/also-available
 * Inserter: no
 */
?>
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"var:preset|spacing|50"}}},"layout":{"type":"default"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--50)"><!-- wp:paragraph {"style":{"typography":{"textDecoration":"none"}},"fontSize":"medium"} -->
<p class="has-medium-font-size" style="text-decoration:none"><?php
	$pocketcasts = '<a href="#"><strong>PocketCasts</strong></a>';
	$soundcloud = '<a href="#"><strong>' . esc_html__( 'SoundCloud', 'castcore' ) . '</strong></a>';
	$spotify = '<a href="#"><strong>' . esc_html__( 'Spotify', 'castcore' ) . '</strong></a>';
	$googlepodcasts = '<a href="#"><strong>' . esc_html__( 'Google Podcasts', 'castcore' ) . '</strong></a>';
	$applepodcasts = '<a href="#"><strong>' . esc_html__( 'Apple Podcasts', 'castcore' ) . '</strong></a>';
	$rss = '<a href="#"><strong>' . esc_html__( 'RSS', 'castcore' ) . '</strong></a>';
	echo sprintf(
		esc_html__( 'Podcast also available on %1$s, %2$s, %3$s, %4$s, %5$s, and %6$s.', 'castcore' ),
		$pocketcasts, $soundcloud, $spotify, $googlepodcasts, $applepodcasts, $rss
	);?></p><!-- /wp:paragraph --></div>
<!-- /wp:group -->
```
2. Delete everything in the `also-available.html`.
3. Add this to the `also-available.html`
 ```
  <!-- wp:pattern {"slug":"castcore/also-available"} /-->
 ```
* The `post-meta` template part is not used. Remove it.
* In the `salmon hit` variation, the font for headings are set to use `outfit`, but later is set to `piazzolla-24`?
CleanShot 2024-10-29 at 18 15 58@2x
* Double-check the credits for the fonts and the images in readme.text There are some missing ones and some that are no longer in the theme
* Similar to CoachAva, remove the following theme tags. `block-styles`, `custom-colors`, `custom-header`, `custom-logo`, `custom-menu`, `editor-style`, `featured-image-header`, `flexible-header`, `footer-widgets`, `front-page-post-form`, `post-formats`, `template-editing`, `theme-options`

Let me know if I can clarify on anything!

**Comment by henriqueiamarino** [comment]
Thanks for the thorough review, @iamtakashi. I have worked on all the following:

- Turned the columns in the Header into a flex row block;
- Removed remaining block spacing from previous version;
- Added main tag to the Search Results template;
- Removed the paragraph block from the Home and Single templates;
- Registered Figtree 600 on the theme.json file;
- Revised the Outfit settings on the theme.json file;
- Removed Matt's image;
- Created a pattern for also-available and fixed the related part;
- Removed the post-meta template part;
- Fixed the Salmon Hit variation; Piazzola is my pick for all the headings.

**Comment by iamtakashi** [comment]
@henriqueiamarino Thanks for the updates! One last note—you accidentally removed the woman's image and kept Matt's photo. Once you swap it, it should be ready to merge.

**Comment by henriqueiamarino** [comment]
Thanks, @iamtakashi. This is very awkward... I'm sure I removed Matt's photo as I noted it. It looks like I'm being trolled sometimes. Anyway, it's done.

**Pull request merged**
