### PR TITLE
Muscat: Update theme and prepare for Dotorg submission

### PR DESCRIPTION
**Pull request by beafialho**
Changes from WordPress Playground, made some adjustments to the theme:

- Changed its main heading "Is this nice?" to "Is this cool?" after some feedback regarding the expression
- Adjustments in the outer spacing
- Adjustments in the templates wide widths
- Adjustments in the header and footer
- Added font license
- Updated screenshot

### CODE REVIEW

**Comment by jasmussen** [comment]
Catching up on old theme reviews here, I can maybe help here. First question: is this PR still relevant? If so, it needs a rebase. I can help with that. I'm also guessing that if I do this, a Playground link for testing will be created? Let me know, happy to help!

**Comment by beafialho** [comment]
Yes, this one, Covr and Iotix are waiting review please. Thanks!

**Comment by jasmussen** [comment]
I wasn't able to rebase this branch to fix the conflict, so I created a new one here: #7938. The changes should be the same.

**Comment by jasmussen** [comment]
Closing in favor of #7938.

**Pull request closed without merging**
