### PR TITLE
Blockbase: Remove CSS to bring up the page content and instead remove the bottom margin from post titles

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
In https://github.com/Automattic/themes/pull/4733 we removed the margin on top of all `<main>` elements, but this is actually needed for the index template. This PR removes that change and instead removes the bottom margin on Post Title blocks, so that the content sits closer to the post title. This means that https://github.com/Automattic/themes/issues/4722 is now fixed again.

#### Related issue(s):
 https://github.com/Automattic/themes/pull/4733
https://github.com/Automattic/themes/issues/4722

### CODE REVIEW

**Comment by kjellr** [comment]
This _almost_ fixes it, but the spacing below the title is now very slightly less than it was before (and no longer exactly equal to the space between the post content and the post meta):

Before|After
---|---
Screen Shot 2021-09-29 at 9 46 43 AM|Screen Shot 2021-09-29 at 9 46 34 AM

**Comment by scruffian** [comment]
I think that's caused by paragraphs not using block gap. I pushed a commit so paragraph spacing now uses the block gap settings.

**Comment by kjellr** [comment]
We are really close! The only small issue I'm seeing now is that the gap between the title and the featured image (when there is one) is shorter than the the other gaps used: 

Screen Shot 2021-09-29 at 1 05 36 PM

If we can add more space above the top of the featured image so it matches the post meta gap (and let everything else stay the way it is right now), we're good to go.

**Comment by jffng** [comment]
> The only small issue I'm seeing now is that the gap between the title and the featured image (when there is one) is shorter than the the other gaps used

I looked into this and it's caused by some extra space on the featured image:

Screen Shot 2021-09-29 at 4 56 02 PM

I added a commit https://github.com/Automattic/themes/pull/4738/commits/54234ac4b3798ef363ec4e9ef8e7760340d27ed0 to remove it. I am not sure if this should go in Gutenberg.

**Comment by scruffian** [comment]
> I am not sure if this should go in Gutenberg.

I think so probably

**Comment by kjellr** [comment]
Any objections to changing the custom gap baseline to 15px instead of 10px? I just pushed a quick commit to try that out, and I like it better than the previous iteration. Feels much more comfortable, and sort of minimizes any other spacing inconsistencies: 

Screen Shot 2021-09-30 at 7 44 38 AM

Screen Shot 2021-09-30 at 7 44 57 AM

Screen Shot 2021-09-30 at 7 45 06 AM

The only thing I _don't_ like with this extra space is that it should not be applied to paragraphs. I reset that back to using `1em`, which is a better default: 

1em|block-gap
---|---
Screen Shot 2021-09-30 at 7 47 04 AM|Screen Shot 2021-09-30 at 7 46 58 AM

The main issue is that that change doesn't get picked up in the editor unless I add some weird extra specific rules. 😕 Any ideas there?

**Comment by scruffian** [comment]
This is looking good. I changed the selectors on the paragraph to make it work in the editor. It's not pretty but I couldn't think of a better option....

I'll open a Gutenberg issue...

**Review by kjellr — APPROVED** [review]
Excellent. I imagine in the future it would be nice to be able to just specify a `blockGap` value for the paragraph block itself to take care of that. 🤔

Anyway, in the meantime I think this is good to go!

**Comment by scruffian** [comment]
Tracked here: https://github.com/WordPress/gutenberg/issues/35267

**Comment by jffng** [comment]
If I'm following correctly, the space between paragraphs should be `1em` in the editor and front-end. This is not reflected on the front-end because the blockGap selector specificity is still winning: 

Screen Shot 2021-09-30 at 1 49 54 PM

**Comment by kjellr** [comment]
> If I'm following correctly, the space between paragraphs should be 1em in the editor and front-end. This is not reflected on the front-end because the blockGap selector specificity is still winning:

Ugh yes. I just pushed another commit that specifically overrides that. It's pretty specific, but it's the only one I found that generally worked. 

(I tried doing just `.wp-site-blocks p`, but the specificity there messed with static `p` tags inside of other blocks like the Author block. So instead I focused on just overriding this single rule. 😕)

**Review by jffng — APPROVED** [review]
Since we've documented the paragraph spacing issue in GB, I think this is good to bring in. 

I also opened a PR about the extra space on the featured image block: https://github.com/WordPress/gutenberg/pull/35273

**Pull request merged**
