### PR TITLE
Lodestar, Illustratr & Galactic 2: Remove Uppercase in Post Titles

### PR DESCRIPTION
**Pull request by torres126**
#### Changes proposed in this Pull Request:

As mentioned in #413, Illustratr, Intergalactic 2 and Lodestar all has themes which transform the post title in the Editor with intent to make the editor and front-end match, but this can cause confusion. So, this PR intends to stop that from happening so the user can decide to use capital letters.

### CODE REVIEW

**Comment by laurelfulford** [comment]
Thanks for the patch, @torres126! This looks good to me.

**Comment by vinnie333** [comment]
Sorry for the noobie question but I edited the CSS file in intergalactic-2/editor-blocks.css inside Wordpress, hoping that Post Titles wouldn't be all caps anymore but it doesn't seem to have done anything?
I removed the two lines & added the one as it showed but nothing seems to have changed...
Any insight on what i'm missing?   I love this theme other than the darn ALL CAPS in Page titles & Post Titles...

**Comment by torres126** [comment]
Hi @vinnie333, `editor-blocks.css` (which was modified in this PR) is only for the Gutenberg editor, so removing that bit there won't affect the actual content. It's generally recommended to use the Customiser instead of directly editing the theme to make CSS changes though, there's some reasons and steps listed here: https://codex.wordpress.org/CSS#Custom_CSS_in_WordPress

Try adding this. :)

```
.entry-title {
text-transform: inherit;
}
```

**Comment by vinnie333** [comment]
You're amazing, thank you so much! 
No more ALL CAPS!

**Pull request merged**
