### PR TITLE
Seedlet: Add theme support for custom spacing controls

### LINKED ISSUE #2280: Seedlet Blocks: Add support for custom spacing controls for cover block
Identical to #2277, could we have the support for custom spacing controls added to the cover block?

Ref: WordPress/gutenberg#21492

> This feature is opt-in via add_theme_support. In order to show the padding controls, the following needs to be added to a theme's function.php
add_theme_support( 'experimental-custom-spacing' );

### PR DESCRIPTION
**Pull request by kjellr**
Closes #2280. Seems to work just fine in the front end too. 

cover-padding

### CODE REVIEW

**Comment by jffng** [comment]
Hmm this isn't working for me, but seems like a Gutenberg bug (note the "NULL" value in the padding input field): 

Screen Shot 2020-07-28 at 9 14 17 AM

I'm running the plugin version 8.6.0.

**Comment by kjellr** [comment]
I saw that too, but once I typed in a value (e.g. `100px`), it started working. If you're seeing that too, would you mind filing an issue for that in the GB repo?

**Comment by jffng** [comment]
https://github.com/WordPress/gutenberg/issues/24245

**Comment by kjellr** [comment]
Cool. Since that's a GB problem, I _think_ this is good to go?

**Pull request merged**
