### PR TITLE
Alves: Add Color Annotataions.

### PR DESCRIPTION
**Pull request by allancole**
Follows the mold of #1944 to add basic color annotations for Alves.

image

To Do:
- [x] Refinement around contrast.
- [x] Double checking responsive styles.
- [x] Add featured color palettes.

### CODE REVIEW

**Comment by kjellr** [comment]
I made a few small updates in 915b62f in order to get submenu items working right on mobile. Since we can't have responsive color annotation rules, we need to have submenus use the background color on desktop:

Screen Shot 2020-05-07 at 7 01 51 PM

We need to add some custom CSS to add a border or drop shadow to that. I tried doing that just not, but couldn't get the extra styles to load. Will try again.

**Comment by kjellr** [comment]
@allancole Check out 4df3bed when you have a moment. Here's what I did there: 

- I duplicated the `wpcom-editor-colors.php` colors file you created for Varia. 
- I deleted all color styles _except_ for the Utility Classes. 
- I replaced the default values with the ones from Alves. ([Example](https://github.com/Automattic/themes/pull/1962/commits/4df3bed41c9e94ddbab05e4a19fa3895496d02a4#diff-9e4f12d4df5990cbfbd119dcbd840167R8))
- I used the colors command line tool to pull the selectors from Alves' `style-editor.css`, and populated those rules in this file. 

The end result looks good, and is closer to the original theme than the default inherited rules from Varia. It also took me ~15 minutes. Since the editor stylesheets are relatively small, I wonder if this is a better approach going forward? 

Before (Editor)|Front End
---|---
Screen Shot 2020-05-21 at 08 28 45|Screen Shot 2020-05-21 at 08 31 00

After (Editor)|Front End
---|---
Screen Shot 2020-05-21 at 08 27 38|Screen Shot 2020-05-21 at 08 31 00

**Comment by kjellr** [comment]
Also, I noticed a weird issue that I'm having trouble looking into (the editor keeps throwing a WSOD when I inspect things for some reason). 

The custom colors in the palette show up nicely in the palette picker: 

Screen Shot 2020-05-21 at 8 33 17 AM

... but then in the editor itself, they all appear darker: 

Screen Shot 2020-05-21 at 8 33 04 AM

... except for the "background" color, which is showing up as pure white for some reason. 

This is only an issue in the editor. They appear just fine on the front end. I didn't notice this in Varia, but it does appear to happen to the child themes when they inherit Varia's `wpcom-editor-colors.php` (or when I copy/paste Varia's Color Utilities rules, like I did in 4df3bed. Any idea what's happening here?

**Comment by kjellr** [comment]
> Also, I noticed a weird issue that I'm having trouble looking into
> The custom colors in the palette show up nicely in the palette picker:
> ... but then in the editor itself, they all appear darker

This is due to the `!important` styles for those that are inherited from Varia. Once we fix these in Varia and recompile the CSS here, this will go away.

**Comment by kjellr** [comment]
Posting these issues here for tracking: 

## General Issues

- [ ] Default text color for cover blocks is incorrect on the front end.

Editor|Front End
---|---
Screen Shot 2020-06-05 at 1 46 20 PM|Screen Shot 2020-06-05 at 1 46 03 PM

- [ ] Default button text color is incorrect in both the editor and the front end.

Screen Shot 2020-06-05 at 1 49 04 PM


## Contact Templates Issues

- [ ]  Text colors appear too dark in the front end (this may be the same issue as the Cover block issue)

Editor|Front End
---|---
Screen Shot 2020-06-05 at 12 53 44 PM|Screen Shot 2020-06-05 at 12 53 24 PM

Editor|Front End
---|---
Screen Shot 2020-06-05 at 12 54 28 PM|Screen Shot 2020-06-05 at 12 54 13 PM


## Services Templates Issues

- [ ]  Text and button colors appear too dark on the front end (this may be the same issue as the Cover block issue)

Editor|Front End
---|---
Screen Shot 2020-06-05 at 12 59 00 PM|Screen Shot 2020-06-05 at 12 58 46 PM

- [ ] Services list background colors appear unreadable. 

Editor|Front End
---|---
Screen Shot 2020-06-05 at 1 00 52 PM|Screen Shot 2020-06-05 at 1 00 10 PM

## Blog Template Issues

- [ ]  Text appears too dark on the front end (this may be the same issue as the Cover block issue)

Editor|Front End
---|---
Screen Shot 2020-06-05 at 1 01 53 PM|Screen Shot 2020-06-05 at 1 02 08 PM


## Portfolio Template Issues

- [ ]  When the page goes wide, the slider background on the edges does not update with the page background. 

Screen Shot 2020-06-05 at 12 56 37 PM

**Comment by allancole** [comment]
Merging this PR and syncing the changes to wpcom.

**Comment by desnum** [comment]
When changing the customizer color palette for white text, the text in the editor's input fields also becomes white, making it difficult to read:

Screen Shot 2020-06-26 at 3 10 14 PM

HC-22156681

**Comment by jackiejade** [comment]
When changing the customizer color palette for white text, the text in form submissions becomes white, making it difficult (or impossible without highlighting) to read:

screenshot of customizer with form and white text

This isn't a HUGE problem for users on Premium or higher, but those on Personal cannot fix the issue as they can't add CSS. I've had to give a Custom Design stand alone upgrade in order to temporarily fix this using the following CSS:

`
.wp-block-jetpack-contact-form input[type="text"], .wp-block-jetpack-contact-form input[type="email"], .wp-block-jetpack-contact-form input[type="tel"], .wp-block-jetpack-contact-form input[type="url"] {
	color: #000;
}
`

**Pull request merged**
