### PR TITLE
GH-2847 Adds AMP meta to compatible themes.

### PR DESCRIPTION
**Pull request by milindmore22**
#### Changes proposed in this Pull Request:
Added `AMP:true` meta in the following themes.

- [x] Varia
- [x] Alves
- [x] Balasana
- [x] Barnsbury
- [x] Brompton
- [x] Exford
- [x] Hever
- [x] Leven
- [x] Mayland
- [x] Maywood
- [x] Morden
- [x] Redhill
- [x] Rivington
- [x] Shawburn
- [x] Stow

### CODE REVIEW

**Comment by adamsilverstein** [comment]
See also https://github.com/Automattic/newspack-theme/pull/1153

**Comment by scruffian** [comment]
This looks good. Thanks for the fixes. I've updated the version numbers so we can rebuild new ones.

**Comment by jamesozzie** [comment]
That looks great. @milindmore22 I don't see the flag appearing if the theme is downloaded from the [WordPress.org links](https://wordpress.com/theme/varia). 

Do these download links need to be updated?

**Comment by scruffian** [comment]
I have a fix for this here: D56201-code

**Pull request merged**
