### PR TITLE
Add Kamala

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:

Needs a new name

#### Related issue(s):

[Uploading kamalastudio.WordPress.2024-09-16.xml.zip…]()

### CODE REVIEW

**Comment by iamtakashi** [comment]
This theme uses images from Unsplash, but as a part of reducing the backlog, I'll work on this theme to launch only on dotcom.

**Comment by iamtakashi** [comment]
@beafialho Could you let me know the source of the following two photos?
homepage_image_2-1024x671
homepage_image_3-1024x557

**Comment by iamtakashi** [comment]
The theme check fails because of the use of the Unsplash image, but this theme is going to launch only on Dotcom, so I'm merging it. We can add the info about the images above when we can. The info isn't important for a Dotcom-exclusive theme.

**Comment by beafialho** [comment]
> @beafialho Could you let me know the source of the following two photos?

This theme was a spin-off, so it uses Unsplash images.

**Comment by iamtakashi** [comment]
@beafialho Yes, I assumed they were from Unsplash, but it'd still be good to list the source in the readme.txt. I tried to search them in Unsplash but failed. Do you remember by any chance?

**Comment by beafialho** [comment]
@iamtakashi apologies I misread your message and didn't understand you needed the actual links!

Here are the links:
https://unsplash.com/photos/a-person-standing-on-a-yoga-mat-on-the-floor-G9H5edUL0T8
https://unsplash.com/photos/woman-in-white-tank-top-sitting-on-white-yoga-mat-ATXOotRD_H0

**Comment by iamtakashi** [comment]
No worries! Thank you!!

**Pull request merged**
