### PR TITLE
Seedlet Blocks & Mayland Blocks: Add FSE tag for dotorg.

### LINKED ISSUE #4146: Seedlet + Mayland Blocks: Add FSE tag for dotorg
I was navigating the [theme directory for FSE themes](https://wordpress.org/themes/tags/full-site-editing/) and only saw Blockbase. Seedlet Blocks and Mayland Blocks should have the tag too.

### PR DESCRIPTION
**Pull request by danieldudzic**
Closes #4146

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
This is needed for these themes to show up as FSE ready on dotorg, but right now this same tag is being used by themes using the legacy FSE on dotcom (such as Maywood for example). Will this break things for any dotcom integrations? should we add this only for dotorg submissions? @mattwiebe

**Comment by scruffian** [comment]
Should we also add it for Quadrat?

**Comment by MaggieCabrera** [comment]
That's the question of the hour. If you can't use the site editor, then I'd say no.

**Review by MaggieCabrera — APPROVED** [review]
After talking to @Copons about this, we shouldn't have problems merging this.

**Pull request merged**
