### PR TITLE
Elegant Business: Update screenshot to include logo and menus

### LINKED ISSUE #897: Elegant Business: Update screenshot.png
Update the screenshot to include the following.

* Logo (Use one from http://logodust.com/)
* Main menu
* Social menu

### PR DESCRIPTION
**Pull request by danieldudzic**
Closes #897 
screenshot

### CODE REVIEW

**Comment by danieldudzic** [comment]
@iamtakashi Please note, that instead of using a logo from logodust.com I have used the logo that was uploaded to the demo site (I assume it was designed for the theme and seems to be working better than a generic logo).

**Comment by iamtakashi** [comment]
@allancole Do you know anything about this logo? Does it meet the licence? 

Screen Shot 2019-06-06 at 12 30 34

**Comment by allancole** [comment]
@iamtakashi @danieldudzic, I hacked that logo together myself with illustrator as a temporary solution. It doesn’t technically have a license, but if we’re planning on using it, it can be a CC0 graphic. Although I’m not sure how I’d go about assigning a CC0 license to it.

**Comment by allancole** [comment]
Also, I kind of hate how this logo looks, lol. I’d suggest replacing it with some other CC0 logo if possible.

**Comment by danieldudzic** [comment]
I think the confirmation that you are the creator and therefore we are not violating any licenses is sufficient.

Please correct me if I'm wrong, @iamtakashi

**Comment by danieldudzic** [comment]
screenshot

**Pull request merged**
