### PR TITLE
DotCom Automation: create GlotPress project when a theme is deployed

### PR DESCRIPTION
**Pull request by madhusudhand**
#### Changes proposed in this Pull Request:

This PR adds automation script to create and deploy GlotPress project on dotcom.

command: `npm run prelaunch:glotpress pixl`

#### Related issue(s):

https://github.com/orgs/Automattic/projects/215#card-87878291

### CODE REVIEW

**Review by mikachan — COMMENTED** [review]
This is great as a way to automate this from the free themes repo. Maybe this new script could be run as part of the initial deployment (or the deploy script), so we don't need to remember to run it. We'd probably need to add a check for an existing GlotPress project beforehand.

What do you think about automating this within the dotcom codebase instead? I'm thinking that this would then cover any newly created themes on dotcom, not just themes stored in this repo.

**Comment by madhusudhand** [comment]
> Maybe this new script could be run as part of the initial deployment (or the deploy script), so we don't need to remember to run it. We'd probably need to add a check for an existing GlotPress project beforehand.

I am trying this fun commanline approach to launch a theme here. https://github.com/Automattic/themes/pull/6959
Its a draft version and should have all the checklist included.

What do you think about this?

> What do you think about automating this within the dotcom codebase instead? I'm thinking that this would then cover any newly created themes on dotcom, not just themes stored in this repo.

Yes. Agree that it should help all the themes on dotcom.
Which repo do you suggest this should be part of?

**Comment by mikachan** [comment]
> What do you think about this?

I love it! I like that it makes launching a theme fun, and certainly more efficient than our current process.

> Which repo do you suggest this should be part of?

I'm not sure, but when I was initially thinking of automating GlotPress, I thought it would live near the GlotPress theme script file, maybe being triggered by a theme being network-activated or the showcase being published. But the solution in this PR is fab and 10x times better than what we do currently, so I'm not sure anymore. I guess I was thinking that the responsibility for GlotPress should sit with dotcom rather than this repo, but maybe this introduces unnecessary time/complications.

Edit:
Edit to add more thoughts... I'm not sure GlotPress automation should be part of a CLI script. Rather it should happen automatically, hidden in the background of another process, e.g. on theme network activation or deployment. So this maybe could still be this repo for now, but it's triggered as part of the `deploy-theme` step.

**Comment by pbking** [comment]
I agree with the "hidden and automated" part of @mikachan  comments.  Can we tap that process in to the deploy process?  I think it's fine to have a command that generates the glotpress bits, but I think it might be best if that command didn't also commit that change and that instead it just rolls that change into every push if it hadn't already been created (and maybe if the theme version is >= 1.0 or something).

**Comment by madhusudhand** [comment]
Thanks @mikachan @pbking for the feedback.

GlotPress creation is now made part of push-button-deployment, for the themes that changed. 
It makes sense to create every time a theme is deployed (it might have included new patterns or strings that requires translations)
It does nothing if the glotpress already exists.

As suggested by @pbking, included a version check to create only when the theme reaches its first major version.

**Review by mikachan — APPROVED** [review]
Thanks for addressing the feedback!

> It makes sense to create every time a theme is deployed (it might have included new patterns or strings that requires translations)

This makes sense 👍 This sounds like an improvement on our current workflow.

I think we can bring this in, as it removes the manual step from the current process and gives us a good basis for our other automation work.

**Pull request merged**
