### PR TITLE
removed non-gap margins from heading

### PR DESCRIPTION
**Pull request by pbking**
#### Changes proposed in this Pull Request:
Removed all gaps in the header not controlled by the gap (flex) attribute.

Before:
image
image

After:
image
image
image

#### Related issue(s):
#4597

### CODE REVIEW

**Comment by danieldudzic** [comment]
I like this approach, but I'm getting some odd behavior for smaller screen sizes:

ouYUIsKfVM

**Comment by pbking** [comment]
Thank you @danieldudzic.  I see that I was overly aggressive removing the auto from the right margin of that element.  Returned it looks correct again:

image

**Comment by danieldudzic** [comment]
@pbking it looks better now, but still a bit odd. Is that correct? The site title being on the right and the subtitle under the logo on the left?
1h557y9O5s

**Comment by pbking** [comment]
I've combined this behavior with #4692.  Can you check there?  The behavior should be different but I've focused my efforts there to make sure it's right:
image
image

**Comment by danieldudzic** [comment]
Yep! Header in Quadrat in #4692 seems to be behaving correctly.

**Comment by pbking** [comment]
Closing this, fixed by #4597 instead

**Pull request closed without merging**
