### PR TITLE
Lodestar: Fix image block background color issue

### LINKED ISSUE #1685: Lodestar: Remove white background for images added via image block
## Steps to replicate

Add an image to the image block and it will have white background, even though the image is transparent.

Screen Shot 2019-11-28 at 18 55 46

This doesn't happen when an image is added via URL.

But it happens again if the image block is linked to another URL. The workaround is to either add custom CSS:

.entry-content a img {
background: none;
box-shadow: none;
}

or add the link to the caption instead.

But overall, I'm not sure why a white background is added by default.

## Expected

Expected not to have a white background on transparent images added via image block.

* User report: 16976068-hc

cc @catkit

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #1685

<table>
<tr>
<td>Before:
<br><br>

#1685-before

</td>
<td>After:
<br><br>

#1685-after

</td>
</tr>
</table>

### CODE REVIEW

**Comment by davoraltman** [comment]
LGTM!

One thing though - for some reason, I can't reproduce the original issue anymore. Looks like this was removed even though this PR wasn't merged?

**Comment by nielslange** [comment]
> LGTM!
> 
> One thing though - for some reason, I can't reproduce the original issue anymore. Looks like this was removed even though this PR wasn't merged?

@davoraltman Have you linked the image? The issue only appears for linked images, not for unlinked images.

**Comment by davoraltman** [comment]
@nielslange In my defense, it was really late when I tried this yesterday 🤦‍♂ 

Reproduced it and checked your fix, works like a charm :)

**Comment by michaeldcain** [comment]
Although the patch functionally works, I wonder if this was an intentional design decision, and the transparent background issue is more an unfortunate side-effect. Personally, I'd prefer a non "destructive" patch in situations like this for live themes, where the issue might not be an explicit defect. A workaround could be a `.no-frame` CSS rule that removes the background and box shadow, and then have the user add the class as needed for transparent images.

I've added a "Needs Theam Reply" label to get @Automattic/theam to weigh in on this.

**Comment by nielslange** [comment]
> Although the patch functionally works, I wonder if this was an intentional design decision, and the transparent background issue is more an unfortunate side-effect. Personally, I'd prefer a non "destructive" patch in situations like this for live themes, where the issue might not be an explicit defect. A workaround could be a `.no-frame` CSS rule that removes the background and box shadow, and then have the user add the class as needed for transparent images.
> 
> I've added a "Needs Theam Reply" label to get @Automattic/theam to weigh in on this.

Personally, I don't see how this issue could be based on an intentional design decision. That said, let's see what the @Automattic/theam thinks on this issue. 😀

**Review by pbking — APPROVED** [review]
Change works and makes sense.  I also cannot discern why the original author would have intended for the white background.
👍

**Comment by scruffian** [comment]
Deployed in r57303-wpcom-themes

**Pull request merged**
