### PR TITLE
BCB: Add post comments styles

### PR DESCRIPTION
**Pull request by jffng**
Starts to address #3546.

Which of these styles do you think should live with Gutenberg? 

Styling in Gutenberg a bit tricky because the post comments block relies on the Core comments template: https://github.com/WordPress/gutenberg/blob/9b75a5c44e934f580282e2d16cc462ff4567cded/packages/block-library/src/post-comments/index.php#L33

Before | After
--------- | ---------
Screen Shot 2021-03-29 at 1 00 16 PM | Screen Shot 2021-03-29 at 12 56 25 PM

### CODE REVIEW

**Comment by danieldudzic** [comment]
Here's the Gutenberg issue: https://github.com/WordPress/gutenberg/issues/26864

I have added the button styling to the Reply link:
Comments_–_themes

**Comment by scruffian** [comment]
Moved this to Gutenberg too: https://github.com/WordPress/gutenberg/issues/26864

**Comment by jffng** [comment]
I removed some styles because of the PR to add some styles in Gutenberg.

**Comment by danieldudzic** [comment]
@jffng Shouldn't this be merged with https://github.com/Automattic/themes/tree/make/blank-canvas-blocks rather than trunk?

**Comment by jffng** [comment]
I believe since we merged BCB to trunk, any changes to BCB can be made directly to trunk / synced to svn as soon as they're merged. `make/blank-canvas-blocks` is now a development branch for the new versions of Seedlet Blocks and Mayland Blocks.

**Pull request merged**
