### PR TITLE
Radcliffe 2: adds styles for Posts List Block

### LINKED ISSUE #830: Radcliff2: Add basic style for Posts List block
Posts List block is coming soon, and let's make sure it's not out of the place in this popular theme.

### PR DESCRIPTION
**Pull request by jeffikus**
#### Changes proposed in this Pull Request:
- Adds Styles for Posts List Block
- Test on single Page and single post

@allancole I've made the title and meta text-transform to uppercase as per some of the other styles in the theme. I've also lined up the button states to match. Please let me know if you don't agree with the design choices I've made!

#### Related issue(s):
#830

### CODE REVIEW

**Comment by iamtakashi** [comment]
Since this theme only shows the title and metas in index/archive view, we need some design decision. I think it's best to replicate sort of its single view.

The difference in typography is glaring at the moment. And the theme has style packs that changes the appearance, and the block style should also "largely" match with each style.

Screen Shot 2019-06-03 at 11 53 48
_The screenshot was taken with the default style._

**Comment by jeffikus** [comment]
@iamtakashi ok, in the screenshot on the right - that's the single post page right? I think if we want to get everything to line up, @allancole is the best person to do a full audit.

**Comment by iamtakashi** [comment]
OK, no worries. I'll take this one then.

**Comment by iamtakashi** [comment]
I've worked on a PR that includes all style pack versions in #902

**Pull request closed without merging**
