### PR TITLE
Quadrat: Add button hover styles

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
This implements the button and link styles from the Figma file

Screenshot 2021-05-04 at 17 34 06
Screenshot 2021-05-04 at 17 33 51

cc @kjellr @beafialho for a review

#### Related issue(s):
https://github.com/Automattic/themes/issues/3640

### CODE REVIEW

**Comment by beafialho** [comment]
I don't mind having the darker background color instead of the border, it works well too.

**Comment by scruffian** [comment]
Oh sorry I missed the hover part of the figma file. I'll copy what is in there...

**Comment by scruffian** [comment]
I updated the button styles and added link styles, so this is ready for another review.

**Comment by jffng** [comment]
I rebased `make/quadrat` against `trunk`, and then rebased this branch against `make/quadrat`.

This is what it looks like on the front-end: 

Kapture 2021-05-04 at 14 01 00

And editor: 

Kapture 2021-05-04 at 14 03 18

Is this expected? I hope I didn't mess anything up in the rebase, but the diff looks clean to me..

**Comment by jffng** [comment]
I rebased `make/quadrat` against `trunk`, and then rebased this branch against `make/quadrat`.

This is what it looks like on the front-end: 

Kapture 2021-05-04 at 14 01 00

And editor: 

Kapture 2021-05-04 at 14 03 18

Is this expected? I hope I didn't mess anything up in the rebase, but the diff looks okay...

**Comment by scruffian** [comment]
I think that's expected, we'll do the navigation in a different PR. The diff has some conflicts in though...

**Comment by scruffian** [comment]
The rebase on this went very bad, so i just recreated it here: https://github.com/Automattic/themes/pull/3756

**Pull request closed without merging**
