### PR TITLE
Poesis: add theme for review

### PR DESCRIPTION
**Pull request by matiasbenedetto**
#### Changes proposed in this Pull Request:
Poesis: add theme for review
Created by @beafialho 

image

Note from @beafialho :

When building the left part of the layout, [this](https://href.li/?https://themeskingdom.com/demo/aperitive/) was what I wanted to do, I meant to have the heaver fixed to the top and the footer fixed at the bottom. To work that around, I added a spacer in between them. The problem is that the spacer isn’t responsive, which means that the layout would be broken in bigger or smaller screens. For my final solution, the cover block “change content position” worked but its behaviour isn’t ideal because the content won’t extend further a certain width:

image

### CODE REVIEW

**Comment by madhusudhand** [comment]
@beafialho image files are missing in the theme zip. could you add them here?

**Comment by beafialho** [comment]
Sure @madhusudhand here it is, I believe this is the only image. FYI the image name is different than the image loaded to the theme, not sure if that is an issue.

poesis_image

**Comment by madhusudhand** [comment]
I liked the theme. Its simple and unique.

@beafialho 404 template is missing in the theme. could you provide one?

**Comment by beafialho** [comment]
> I liked the theme. Its simple and unique.

Thanks @madhusudhand!

> 404 template is missing in the theme. could you provide one?

The theme wasn't originally meant to ship with a 404 template, but I think it might be better to add one. Here's the markup.

```
<!-- wp:columns {"verticalAlignment":null} -->
<div class="wp-block-columns"><!-- wp:column {"lock":{"move":false,"remove":false}} -->
<div class="wp-block-column"><!-- wp:group {"style":{"position":{"type":"sticky","top":"0px"},"spacing":{"padding":{"right":"0","top":"0"}}},"backgroundColor":"tertiary","layout":{"type":"constrained"}} -->
<div class="wp-block-group has-tertiary-background-color has-background" style="padding-top:0;padding-right:0"><!-- wp:cover {"url":"https://poem2.mystagingwebsite.com/wp-content/uploads/2022/09/image-from-rawpixel-id-7651926-jpeg-scaled.jpg","id":30,"hasParallax":true,"dimRatio":0,"minHeight":100,"minHeightUnit":"vh","contentPosition":"bottom left","align":"full","style":{"spacing":{"padding":{"right":"var:preset|spacing|70","left":"var:preset|spacing|70","top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}}} -->
<div class="wp-block-cover alignfull has-parallax has-custom-content-position is-position-bottom-left" style="padding-top:var(--wp--preset--spacing--70);padding-right:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70);padding-left:var(--wp--preset--spacing--70);min-height:100vh"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim"></span><div role="img" class="wp-block-cover__image-background wp-image-30 has-parallax" style="background-position:50% 50%;background-image:url(https://poem2.mystagingwebsite.com/wp-content/uploads/2022/09/image-from-rawpixel-id-7651926-jpeg-scaled.jpg)"></div><div class="wp-block-cover__inner-container"><!-- wp:group {"style":{"spacing":{"blockGap":"0","padding":{"top":"0","bottom":"0","right":"0","left":"0"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","flexWrap":"nowrap","verticalAlignment":"space-between"}} -->
<div class="wp-block-group" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><!-- wp:template-part {"slug":"header","theme":"sonnets"} /-->

<!-- wp:template-part {"slug":"footer","theme":"sonnets"} /--></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|80"}}}} -->
<div class="wp-block-column is-vertically-aligned-center" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--80)"><!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|70","right":"var:preset|spacing|70","bottom":"var:preset|spacing|70","left":"var:preset|spacing|70"},"blockGap":"var:preset|spacing|30"}},"layout":{"inherit":false}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--70);padding-right:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70);padding-left:var(--wp--preset--spacing--70)"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"width":"10%"} -->
<div class="wp-block-column" style="flex-basis:10%"></div>
<!-- /wp:column -->

<!-- wp:column {"width":"80%","style":{"spacing":{"blockGap":"var:preset|spacing|30"}}} -->
<div class="wp-block-column" style="flex-basis:80%"><!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|30"}},"layout":{"type":"default"}} -->
<div class="wp-block-group"><!-- wp:heading {"style":{"typography":{"fontStyle":"normal","fontWeight":"400"}}} -->
<h2 class="wp-block-heading" style="font-style:normal;font-weight:400">Page not found.</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>This page doesn't exist. Maybe try a search?</p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":"20px"} -->
<div style="height:20px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:search {"label":"Search","showLabel":false,"buttonText":"Search","buttonPosition":"button-inside"} /-->

<!-- wp:spacer {"height":"10px"} -->
<div style="height:10px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"10%"} -->
<div class="wp-block-column" style="flex-basis:10%"></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

**Comment by madhusudhand** [comment]
Theme review is complete. Only comment I have is, size of the cover image `image-from-rawpixel-id-7651926-jpeg-scaled` is about 2MB (after compression). This might have significant impact on page performance also beyond the allowed limits on dotCom.

@beafialho should we consider an alternate image with less size?

**Comment by madhusudhand** [comment]
Reduced the image to lower dimensions. Theme is now ready to 🚢

**Pull request merged**
