### PR TITLE
Club: post comments form block styles

### LINKED ISSUE #6217: club: Styles: Comments
Style comments and comments form blocks following the mockups:

Mobile:
image

Desktop:
image

### PR DESCRIPTION
**Pull request by matiasbenedetto**
#### Changes proposed in this Pull Request:
Club: post comments form block styles

#### Related issue(s):
Fixes: https://github.com/Automattic/themes/issues/6217

### CODE REVIEW

**Review by vcanales — COMMENTED** [review]
Checkbox style from the mockup seems to be missing, is that expected?

image

**Comment by pbking** [comment]
My opinion is that adding CSS to style form items (like checkboxes) is quite reasonable.  There isn't likely to be user-controlled or even Global Style attributes to achieve the target design and doing so with CSS is the only/best way to get that.

**Comment by matiasbenedetto** [comment]
In the last commit, I added the CSS to style the checkbox button. It is looking like this:

Unchecked:
image

Checked
image

**Review by vcanales — APPROVED** [review]
Looks good!

**Pull request merged**
