### PR TITLE
Remote: Comment form styles

### LINKED ISSUE #5501: Remote: Comment form styles (dotcom and dotorg) (if needed)
@kjellr @beafialho the form is currently looking like this:
image

### PR DESCRIPTION
**Pull request by matiasbenedetto**
#### Changes proposed in this Pull Request:
Remote: Comment form styles

#### Related issue(s):
https://github.com/Automattic/themes/issues/5501

### CODE REVIEW

**Comment by jffng** [comment]
Here is a corresponding wpcom patch D75679-code required to not break the comment form there.

**Comment by scruffian** [comment]
@kjellr do you think it's worth the custom CSS for this?

**Comment by kjellr** [comment]
> @kjellr do you think it's worth the custom CSS for this?

I think the CSS that styles the form fields is fine, but I would leave out the `grid` stuff, since it's not strictly necessary to re-arrange items.

**Comment by matiasbenedetto** [comment]
@kjellr this is the mockup:
image


This is the styles implementation with grid:
image


This is the syles implementation without grid:
image

Should we remove the grid css?

**Comment by kjellr** [comment]
That's fine. We should fix the padding on the submit button too while we're at it.

**Comment by matiasbenedetto** [comment]
> That's fine. We should fix the padding on the submit button too while we're at it.

@kjellr sorry but I didn't get what is fine. Should we remove the grid CSS or not?

**Comment by kjellr** [comment]
Yes, please remove the grid.

**Review by pbking — APPROVED** [review]
LGTM
🚢

**Pull request merged**
