### PR TITLE
Casthub: add theme

### PR DESCRIPTION
**Pull request by henriqueiamarino**
A theme specially crafted for users who want to publish their show episodes on a professional hub site.

[Demo site](https://casthub.mystagingwebsite.com/)

screenshot

### CODE REVIEW

**Comment by iamtakashi** [comment]
I'll review this Monday next week (11th)!

**Comment by henriqueiamarino** [comment]
Thanks, @iamtakashi. This will be easier to review. I used a reviewed one as a base theme. Many issues are already fixed.

**Comment by iamtakashi** [comment]
@henriqueiamarino I found a lot fewer issues with this theme. Thank you!!

* It's likely intentional, but the navigation in the `header-home.html` could be the same as the `header.html`. I'm not sure the text "MENU" is necessary. 
CleanShot 2024-11-11 at 15 14 52@2x 
CleanShot 2024-11-11 at 15 14 37@2x
* The Jetpack Subscribe block in `footer.php` should be like this. See the `fontSize`, `customFontSize`, and `submitButtonText`. Edit the file in your VS Code (not the site editor) and test it on the demo site in Pressable because the block doesn't work on a local host site.
```
<!-- wp:jetpack/subscriptions {"submitButtonText":"<strong><?php esc_html_e('SUBSCRIBE', 'casthub');?></strong>","fontSize":"x-small","customFontSize":"x-small","borderRadius":4,"borderWeight":0,"className":"is-style-compact"} /-->
```
* The Figtree font is missing. Let's also add the credit to `readme.txt`
* The image `pexels-marta-dzedyshko-7693857-scaled.jpg` is not used. Let's remove it.
* The patterns `comments.php` and `single.php` aren't used. Let's remove them.
* Can you add credit for the icons of the social media and the placeholder to `readme.txt`?

**Comment by henriqueiamarino** [comment]
Thanks, @iamtakashi. We have been working so much on these theme reviews that I'll definitely learn one day 😅
On the last commit, I've updated the following topics:

- Used the same block for the brand and menu for header-home.html and header.html;
- Replaced the Jetpack Subscribe block and tested it on the demo site: it works;
- Added the missing Figtree font and its credits;
- Deleted both unused patterns: comments and single;
- Added a line of credit attributing the icons to myself as the creator.

**Comment by iamtakashi** [comment]
@henriqueiamarino Everything looks good now. I remember you're going to work further on the colour scheme. Let me know when you're done.

**Comment by henriqueiamarino** [comment]
@iamtakashi, I updated the color palette and reduced the H1 type sizes a bit; thank you.

**Comment by iamtakashi** [comment]
@henriqueiamarino Thanks, it looks great. Ship it! 🚢

**Pull request merged**
