### PR TITLE
#6025: Varia: Fix Jetpack map block close icon

### LINKED ISSUE #6025: Varia & Child themes: Map block close button is too large
### Quick summary

The Map block has a close button on the marker popup box. Varia and child themes cause this button to be too large.

### Steps to reproduce

1. Activate Varia
2. Add a marker to a Map box, add a long Marker Title
3. View published page, hover over the close button

### What you expected to happen

Button should be small, like it is when using Skatepark:

Screen Shot on 2022-05-09 at 08:54:22

### What actually happened

Button is too large. 

Varia:

Screen Shot on 2022-05-09 at 08:55:09

Shawburn:

Screen Shot on 2022-05-09 at 08:57:24

### Context

I run into this issue every time I use Varia themes for a DIFM-Lite site build.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Varia and Varia child themes

### Browser, operating system and other notes

I was using Firefox 99.0.1

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

```
/* Map block close button size */

.mapboxgl-popup-close-button {
	padding: 6px !important;
}
```

### PR DESCRIPTION
**Pull request by bobmatyas**
### Changes proposed in this Pull Request:

Added CSS to reduce the size of button and eliminate overlap with headings on Varia and its child themes. Tested on all themes listed in the original issue.

If I didn't commit the changes right, let me know. 

##### Before

Screenshot on 2022-08-08 at 13-12-23

##### After

Screenshot on 2022-08-08 at 11-51-07

##### Before

Screenshot on 2022-08-08 at 11-54-52

##### After

Screenshot on 2022-08-08 at 12-32-22

### Related issue(s):

Fixes #6025

### CODE REVIEW

**Review by pbking — APPROVED** [review]
Looks great and works well.

Only one small nit; bumping the versions isn't necessary for themes in this repo; The deploy action takes care of that.  It won't hurt anything in this instance though.

**Comment by bobmatyas** [comment]
> Only one small nit; bumping the versions isn't necessary for themes in this repo; The deploy action takes care of that. It won't hurt anything in this instance though.

The version bumping happened automatically when I built the theme and child theme. Not sure if the scripts that handle that should be updated?

**Comment by madhusudhand** [comment]
@bobmatyas It seems to be an issue with the script. I'll make a fix. Thanks for the inputs.

**Comment by pbking** [comment]
Oops.  Looks like this change didn't include the SCSS changes!

**Pull request merged**
