### PR TITLE
Remote: add screenshot and description

### LINKED ISSUE #5502: Remote: Pre-launch: screenshot.png
@kjellr @beafialho I don't think we have a screenshot for Remote

### PR DESCRIPTION
**Pull request by MaggieCabrera**
#### Changes proposed in this Pull Request:

This PR adds a theme description and screenshot

#### Related issue(s):

Closes https://github.com/Automattic/themes/issues/5502
Partially addresses https://github.com/Automattic/themes/issues/5511

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
@beafialho the screenshot needs to be a 1200x900 resolution

**Comment by beafialho** [comment]
@MaggieCabrera here's the correct resolution: https://cloudup.com/c5EwkXT-WMB

**Comment by MaggieCabrera** [comment]
That works! Thanks

**Review by mikachan — APPROVED** [review]
LGTM!

**Pull request merged**
