### PR TITLE
Archivo: add theme

### PR DESCRIPTION
**Pull request by jffng**
#### Changes proposed in this Pull Request:

Adds theme designed by @iamtakashi 

image

### CODE REVIEW

**Comment by matiasbenedetto** [comment]
@iamtakashi we would need to add the link and license of the image included in the theme screenshot. Could you provide that, please?

**Comment by iamtakashi** [comment]
@matiasbenedetto Thanks for the review. I've added variable versions of Archivo font that covers the entire family, and added the information about the image and the font to `readme.txt`. Let me know any issues. Thanks in advance!

**Comment by iamtakashi** [comment]
@matiasbenedetto Is there anything else you need to launch the theme? Let me know.

**Comment by matiasbenedetto** [comment]
Looking good to me :rocket:

**Pull request merged**
