### PR TITLE
Blank Canvas: Remove youtube video used in Musician Links pattern

### PR DESCRIPTION
**Pull request by kjellr**
Addresses [feedback](https://themes.trac.wordpress.org/ticket/94482#comment:13) given in the WordPress.org Theme Review, by removing the YouTube Url in the Musician Links pattern.

Before|After
---|---
Screen Shot 2021-02-22 at 2 32 01 PM|Screen Shot 2021-02-22 at 2 32 38 PM

Also bumps the theme version again so we can re-upload.

### CODE REVIEW

**Review by jeffikus — APPROVED** [review]
LGTM!

**Comment by kjellr** [comment]
Thanks! 

⚠️ ⚠️ ⚠️ 
Let's keep this PR open for now, while we sort out the best way to keep this URL in place on WP.com. Please do not merge!

**Comment by kjellr** [comment]
I've added a version bump, and updated the (broken) theme URI to wordpress.com/theme/blank-canvas.

**Review by jeffikus — APPROVED** [review]
LGTM! ship it!

**Pull request merged**
