### PR TITLE
Add new theme "Iotix" (formerly Startup)

### PR DESCRIPTION
**Pull request by madhusudhand**
#### Changes proposed in this Pull Request:

Adds new theme `Startup`

image

#### Related issue(s):

#6877

### CODE REVIEW

**Comment by madhusudhand** [comment]
Following are the initial observations of the theme.

* Missing screenshot
* Block styles mismatch for Site title, buttons, links etc..
* Different states such as hover, active needs fixes
* home.html for the default content

**Post**

image image

**Page**

image

**Archive**

image

**Comment by jffng** [comment]
Perhaps we can have design weigh in on those issues? cc @beafialho

**Comment by beafialho** [comment]
> Block styles mismatch for Site title, buttons, links etc..
> Different states such as hover, active needs fixes

Any idea why this is happening? 🤔 

Here's the theme screenshot: 

screenshot

**Comment by jffng** [comment]
I made the following updates manually:

- Removed unneeded templates
- Escaped text and images, patternized as needed
- Added screenshot
- Removed nav refs

There are some outstanding styling issues but I think they'll be easier to notice and address when we have a demo site on wpcom.

The one thing we should do before merging is rename the theme since the name is taken.

**Pull request merged**
