### PR TITLE
Add theme-experiments as a submodule

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
This is just a test to see how it would work to add a submodule to the theme repo. If it works well we could make blockbase a submodule.

To test, try running `npm run sandbox:push` and check that the new themes get pushed up.

### CODE REVIEW

**Comment by jeffikus** [comment]
@scruffian are sub modules still tied to specific revision numbers or does it pull the latest revision from the target repo trunk?

**Comment by pbking** [comment]
Submodules (optionally) point to any kind of reference.  That which is added here isn't pointing to anything so it defaults to that repositories default branch (and the HEAD of that branch).

I've seen submodule configurations that point to a specific TAG (usually a specific released version) as the mechanism to ensure that the version of submodule that a particular branch is referencing is the one that is expected.  (For instance branch /abc needs version 1.2.3 of submodule XXX while the trunk of the project needs version 1.2.2 of submodule XXX.) But you could configure it to point to any branch or hash or whatever.

**Comment by pbking** [comment]
Note that you need to run this in order to get the submodule checked out:
```
git submodule update --init --recursive
```

and in order to UPDATE the submodule run this:
```
git submodule update --recursive
```

Pulling the update to the "containing" project (themes) doesn't automatically update the "contained" project (theme-experiments).

**Comment by pbking** [comment]
Circling back to this.
The PR shows that a separate repo can be added as a sub-module.
I'm not sure how to test the kind of workflow changes that this would mean for Blockbase though.

**Comment by scruffian** [comment]
Closing for now

**Pull request closed without merging**
