### PR TITLE
Cortado: add theme

### PR DESCRIPTION
**Pull request by vcanales**
Cortado is a simple and elegant theme. Its colors and typography work together perfectly to deliver a subtle style, perfect for restaurants and coffee shops. By @henriqueiamarino

image

### CODE REVIEW

**Comment by henriqueiamarino** [comment]
@vcanales this theme was created before Create Block Themes so I had to conduct some minor changes and update the whole file. Also included the credits on the new file. It is also updated on the P2.

[cortado.zip](https://github.com/Automattic/themes/files/12039852/cortado.zip)

**Comment by henriqueiamarino** [comment]
Hey, @vcanales, I just noticed issues with spacing on the mobile version. Can I fix it and reupload the zip file on the P2?

**Comment by vcanales** [comment]
@henriqueiamarino Absolutely; feel free to ping me when you have.

**Comment by henriqueiamarino** [comment]
The theme is updated @vcanales ! Attached on the P2, and also here

[cortado.zip](https://github.com/Automattic/themes/files/12162397/cortado.zip)

**Pull request merged**
