### PR TITLE
Add stylelint

### PR DESCRIPTION
**Pull request by scruffian**
This adds a stylelint config and also adds stylelint to the pre commit hook so we catch and fix issues in our Sass files.

If you don't install the hook nothing will happen, so this is just a bonus for people who want to catch and fix these issues on commit.

To test, try committing a change to sass file...

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
This LGTM, it will be very helpful. Maybe we should add a mention to this on the readme file too?

**Review by jffng — COMMENTED** [review]
This works in my testing.

Where did the rules come from? What do you think about using the [WordPress coding standards stylelint config](https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress)?

**Comment by scruffian** [comment]
The rules came from Calypso - I didn't know we had one for WordPress - we should definitely use that...

**Comment by scruffian** [comment]
I think we should do this in the same way that GB does it...

**Pull request closed without merging**
