### PR TITLE
Add/bcb all children build script

### PR DESCRIPTION
**Pull request by pbking**
Adds a script to build all BCB children.

Useful when making changes to BCB (especially changes to theme.json)

The change also includes changes to child theme.json based on running the tool.

### CODE REVIEW

**Comment by scruffian** [comment]
Thanks for doing this. What do you think about renaming the command to "all",  and then also rebuilding BCB?

**Comment by pbking** [comment]
Yea, that's a good idea.

**Comment by pbking** [comment]
Added `build:all` and `start:all`

Also removed the `npm install` from each build run (it made it less useful in practice since I had so much longer to wait for changes in the child themes to get built)

**Comment by scruffian** [comment]
That start:all job isn't working for me. I tried to fix it but I ended up down a big rabbit hole!

**Comment by pbking** [comment]
Are you getting an error, is it not building correctly or is it not triggering on changes you expect?  It's working fine for me but happy to help fix it if I can get the issue reproduced.

I'm finding `start:all` to be the most helpful command. :)

**Comment by scruffian** [comment]
It doesn't trigger when I changes files in the child theme. Have you tried that?

**Comment by pbking** [comment]
Oh, no the purpose was only if things change in BCB, then it builds stuff in the child themes.

I was using it in tandem with the child theme's build (running both).  Changes to BCB changes all children.  Changes to the child only rebuild the child.

Not saying your attempt isn't a valid thing, just that wasn't the tools intent when I threw it together.

**Comment by scruffian** [comment]
Ah ok, makes sense. Let's merge this and iterate :)

**Pull request merged**
