### PR TITLE
Varia: Remove overflow:scroll on pre element

### LINKED ISSUE #2842: Varia: Hide scrollbars when using Verse Block
## Steps to replicate

1. Activate Varia or any of its child-themes
2. Create a page or a post using the [Verse Block](https://wordpress.com/support/wordpress-editor/blocks/verse-block/)

## Result

Vertical and horizontal scrollbars are visible right and below the text:

Screenshot 2020-11-22 at 09 36 09

## Expected

No scrollbars are visible:

Screenshot 2020-11-22 at 09 40 11

* User report: https://wordpress.com/nl/forums/topic/scrollbar-verzen/

### PR DESCRIPTION
**Pull request by jacklenox**
`overflow: scroll` is applied to `pre` elements in our normalize file.
This creates unsightly scrollbars on Verse blocks and others. The latest
version of `normalize.css` doesn't include this particular style.

Let's try removing it, and assuming everything is ok we'll remove it
from Seedlet-based themes too.

Fixes #2842

### CODE REVIEW

**Comment by scruffian** [comment]
I think this will mean we'll also need to rebuild the child themes: pNEWy-daO-p2

**Comment by jacklenox** [comment]
@scruffian Yep, you're right. That's now done and included in this PR.

**Comment by scruffian** [comment]
This reveals a discrepancy between the frontend and the editor the verse block in Gutenberg:

Screenshot 2020-12-14 at 17 29 14
Screenshot 2020-12-14 at 17 29 07

However I think this is an issue with Gutenberg, so I'll raise it there. I think we can merge this.

**Review by scruffian — APPROVED** [review]

**Comment by scruffian** [comment]
I created a PR for the Gutenberg issue here: https://github.com/WordPress/gutenberg/pull/27734

**Comment by jacklenox** [comment]
Thanks, I'll get this merged and updated on wpcom.

**Pull request merged**
