### PR TITLE
Add a theme.json file so that we can support border radius in Spearhead

### LINKED ISSUE #3093: Spearhead: Add support for group block's border radius setting
It would be awesome to integrate the fresh-off-the-press [setting for border-radius](https://github.com/WordPress/gutenberg/pull/27665) on Group block. We've got a couple of Spearhead-based podcasting layouts to be launched shortly that would immediately benefit from this, but it's a very handy design tool in general and we would love to start taking advantage of it as soon as possible.

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
Adds an `experimental-theme.json` file to Spearhead, so that it can support border radius controls in the Group bloc:

Screenshot 2021-01-26 at 14 11 12

#### Related issue(s):
Fixes #3093

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
This LGTM and it's not triggering FSE or removing the customizer on wpcom.

**Review by MaggieCabrera — APPROVED** [review]

**Comment by pbking** [comment]
YES!  THAT's what I'm TALKING about.  Incremental improvements by way of additional customization options for classic themes.

**Comment by mtias** [comment]
Should we also include the ones around padding? I've seen many themes that don't seem to have them (for Cover and Group)

**Comment by scruffian** [comment]
It's on the list... https://github.com/Automattic/themes/issues/2449

**Comment by mtias** [comment]
:)

**Pull request merged**
