### PR TITLE
Maywood: Add new theme to repo

### PR DESCRIPTION
**Pull request by iamtakashi**
A Varia child theme to refresh Modern Business.

### CODE REVIEW

**Comment by Copons** [comment]
Just wanted to say that I will always mispell this theme name, as it's just too similar to the renowned Marwood bar in Brighton, recently commended with this prized award:

**Comment by Copons** [comment]
@iamtakashi would you mind rebase this?
I've just merged https://github.com/Automattic/themes/pull/1309, which adds FSE header/footer support to Varia, and I assume Maywood would inherit them.

**Comment by allancole** [comment]
Looks good! Only a couple things I noticed. 

1. `.alignfull` doesn’t stretch to the edge of the viewport on mobile screens. This is actually an issue in Varia. If you merge #1313 into this branch and recompile, it should fix it automatically or we can wait until its merged to `master`.
2. The text-selection color seems to be mint-green. Not sure if that’s intentional, but I think a blush pink color might work better. Color can be changed here: https://github.com/Automattic/themes/pull/1304/commits/a96320b308a05d10803cd2671cfef7a1bf7b898e#diff-6b6d576e17fc0b11ca617099bc96b0c0R87

image

**Comment by iamtakashi** [comment]
> The text-selection color

Oops, I've left it after copy and pasting :) Fixed.

**Comment by iamtakashi** [comment]
Rebased and caught up with recent Varia updates. I'll merge and push to WP.com on Tuesday.

**Pull request merged**
