### PR TITLE
Seedlet-blocks: Screen shot file name in lower case

### LINKED ISSUE #4008: Seedlet-blocks: Screen shot ignored
## Steps to replicate

Install Seedlet (Blocks) and visit the Themes admin page. 

## Result

The theme does not have a screenshot.

## Expected

The included file Screenshot.png should be visible.

### PR DESCRIPTION
**Pull request by RavanH**
#### Changes proposed in this Pull Request:
Screen shot file name in lower case

#### Related issue(s):
Screenshot.png with capital S not recognized on WordPress Themes admin page.

### CODE REVIEW

**Comment by RavanH** [comment]
Issue #4008

**Comment by pbking** [comment]
Looks like there are more commits in here than intended...

**Comment by RavanH** [comment]
My bad, should have worked on this in a new branch on a fresh fork but took a shortcut... Still, there should be no issue because the other changes have (just) been merged already :)

**Comment by RavanH** [comment]
But I can start fresh if needed. It's not that much work ;)

**Comment by RavanH** [comment]
looks like it's already fixed in trunk :)

**Pull request closed without merging**
