### PR TITLE
Videomaker: Add navigation styles

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
Adds navigation styles for Videomaker:
Screenshot 2021-09-23 at 10 30 57
Screenshot 2021-09-23 at 10 30 45

#### Related issue(s):
https://github.com/Automattic/themes/issues/4656

### CODE REVIEW

**Comment by kjellr** [comment]
Sorry for not having caught this sooner — let's leave this vertical menu out entirely for the initial launch. It's not viable for a bunch of users, and the existing horizontal menu is entirely fine. We should turn on the hamburger by default at all times (once that's possible), but that's all we should do with the menu. 

If we'd like, we can decide to bundle a vertical option like this as an optional header block style. But I don't think it's a priority at all, and I think we should launch without it to keep things streamlined.

**Comment by beafialho** [comment]
This could work if menu links didn't have sublinks, but I agree we can launch without it.

**Comment by scruffian** [comment]
I've updated the code and the screenshot. Ready for another review.

**Comment by beafialho** [comment]
Thanks, this looks good!

**Comment by kjellr** [comment]
The only other feedback I have is that this suffers from the same issue noted in https://github.com/Automattic/themes/issues/4687. The spacing on the sides + top of the header should be identical. Not sure if you want to fix that here or in a separate PR though — it's also a blockbase issue.

**Comment by scruffian** [comment]
Deployed in D67302-code

**Pull request merged**
