### PR TITLE
Verso: add theme

### PR DESCRIPTION
**Pull request by mikachan**
#### Changes proposed in this Pull Request:
This adds Verso, a new theme designed by @beafialho.

image
image

- [x] Add image credits for `verso.jpg`

### CODE REVIEW

**Comment by mikachan** [comment]
@beafialho, do you have the credits for the `verso.jpg` image? Thanks!

**Comment by beafialho** [comment]
Yes @mikachan here's the source: https://picryl.com/media/pessoabaixa-a6a60d

**Comment by mikachan** [comment]
Thank you!

**Comment by mikachan** [comment]
I'm going to merge this so we can test easily on wpcom.

**Pull request merged**
