### PR TITLE
Varia/Alves/Hever/Morden align site logo with the menu

### LINKED ISSUE #1467: Varia: Logo misalignment on grid-based headers
## Steps to replicate

1. Activate a theme with a grid-based header layout. Example: Alves or Morden
2. Go to Customize > Site Identity
3. Add a logo
4. Hide the site title/tagline
5. Visit the site

### With site title, without logo
Captura de Tela 2019-10-02 às 12 19 01

### With site title and logo
Captura de Tela 2019-10-02 às 12 19 11

### Without site title, with logo (and fewer menu items for a better understanding)

Captura de Tela 2019-10-02 às 12 19 57

## Expected

To have my logo horizontally aligned with my menu. When I choose to not display my site title, I'm assuming that it's redundant and that we place it where the site title should be.

A quick workaround would be to change the grid template when we have a logo:

```
@media only screen and (min-width: 560px) {
	.wp-custom-logo .site-header {
		grid-template-areas:
        	"site-logo main-navigation"
        	"site-title ."
        	"site-description social-navigation";
  }	
}
```

Captura de Tela 2019-10-02 às 12 21 15

***

User report: none, #dogfooding

### PR DESCRIPTION
**Pull request by scruffian**
As raised in https://github.com/Automattic/themes/issues/1467, we should drop the site logo into the same line as the menu when the site title and tagline are hidden.

#### Changes proposed in this Pull Request:
- Adds site logo and site title/tagline classes to the header
- Displays the site-logo alongside the menu when there site title and tagline are hidden.

#### Testing instructions
Test that when the site title and tagline are hidden the site logo moves to the same line as the menus.

#### Screenshots:
Screenshot 2020-11-06 at 11 47 15
Screenshot 2020-11-06 at 11 46 54

#### Related issue(s):
Fixes #1467

### CODE REVIEW

**Review by allancole — CHANGES_REQUESTED** [review]
Tested the following themes and they all look good and work as expected on this PR accept Varia. See screenshots. 

- [x] Alves [screenshot](https://user-images.githubusercontent.com/709581/98389126-a63da700-2021-11eb-96f8-9f74c35fb279.png)
- [x] Hever [screenshot](https://user-images.githubusercontent.com/709581/98388980-74c4db80-2021-11eb-84e3-b28a97a8ee9e.png).
- [x] Morden [screenshot](https://user-images.githubusercontent.com/709581/98389338-e9981580-2021-11eb-8489-5c66c8a321d8.png).
- [ ] Varia [screenshot](https://user-images.githubusercontent.com/709581/98389622-4dbad980-2022-11eb-8781-224c6bf634af.png).

**Review by allancole — APPROVED** [review]

**Comment by allancole** [comment]
Turns out Varia doesn’t have a grid-based header so I think this is good to go!

LGTM!

**Comment by edequalsawesome** [comment]
Hey, all! This is also an issue with Barnsbury, which has a grid-based header -- is it possible to also deploy this fix for that theme as well?

**Comment by scruffian** [comment]
@edequalsawesome added to the board 👍

**Pull request merged**
