### PR TITLE
Meraki: Style updates.

### PR DESCRIPTION
**Pull request by alaczek**
Minor styling changes to theme.json:
* update the secondary color definition.
* update default heading font-weight.

### CODE REVIEW

**Comment by alaczek** [comment]
I wanted to update the button hover color as well - do I need to do it via style.css ([like in TT2](https://github.com/WordPress/twentytwentytwo/blob/trunk/style.css#L74))?

**Comment by MaggieCabrera** [comment]
> I wanted to update the button hover color as well - do I need to do it via style.css ([like in TT2](https://github.com/WordPress/twentytwentytwo/blob/trunk/style.css#L74))?

Since this is a Blockbase child, you want to change the value of [this](https://github.com/Automattic/themes/blob/b4c9812b821819b76c4256a9b936ffb855e08cda/blockbase/theme.json#L113) variable.

**Comment by alaczek** [comment]
Thanks @MaggieCabrera! What if I wanted to do the same thing as TT2 - don't change the color, but just add opacity - how would I do that in theme.json?

**Comment by MaggieCabrera** [comment]
> Thanks @MaggieCabrera! What if I wanted to do the same thing as TT2 - don't change the color, but just add opacity - how would I do that in theme.json?

I don't think we contemplated that with Blockbase. You can either add an rgba value with opacity to the theme.json variable or simply add CSS. I think CSS is better in this case, so follow what TT2 does.

**Comment by alaczek** [comment]
Yeah, ok. I don't think I'm going to do that in this case after all, so I'm assuming this is good to merge.

**Review by MaggieCabrera — APPROVED** [review]
LGTM

**Pull request merged**
