### PR TITLE
Club: font size fixes in various elements

### PR DESCRIPTION
**Pull request by matiasbenedetto**
#### Changes proposed in this Pull Request:
Club: font size fixes in various elements:

- Reduce the line height of the footer elements from 1.6 to 1.3

- Update line height of h1 and h2 elements

| Before | After |
| --- | --- |
| image | image |

- Update the font size of the single and page template title

| Before | After |
| --- | --- |
| image | image |

- Update post comment form submit button font size update

| Before | After |
| --- | --- |
| image | image |

- Update pagination links font size

| Before | After |
| --- | --- |
| image | image |

- Remove the underline from query pagination and post navigation blocks

| Before | After |
| --- | --- |
| image | image | 

| Before | After |
| --- | --- |
| image | image |

- Remove double underline in reply comment link:

| Before | After |
| --- | --- |
| image | image |

- Set the same font size for post comment meta and content

| Before | After |
| --- | --- |
| image | image | 

#### Related issue(s):
Part of https://github.com/Automattic/themes/issues/6374

### CODE REVIEW

**Comment by vcanales** [comment]
The [figma file I have access to](https://www.figma.com/file/VtkA1u4mt9sWbZagxqhn93/Club?node-id=2%3A828) shows some differences. For instance, the pagination links are set to `40px` in the Singe template

image

Perhaps I'm not looking in the right place?

**Comment by matiasbenedetto** [comment]
> the pagination links are set to `40px` in the Singe template

Yep, that is a fluid size, in large/desktop viewport is 40px. Tha is what I fixed in this PR:
image

**Comment by madhusudhand** [comment]
There are few font differences in other areas. Created #6374 to track all issues. consider adding font fixes part of this.

**Comment by matiasbenedetto** [comment]
I added a few more little fixes in the latest commits.

**Comment by pbking** [comment]
These changes look good and does everything it says on the tin.

I haven't compared deeply to figma, but the changes look good and follow the notes from here and #6374.

The scaling of the site looks really good; this is the first time I've explored that in any depth.  Well done.

**Review by pbking — APPROVED** [review]

**Pull request merged**
