### PR TITLE
Varia: Fix Faux button style

### LINKED ISSUE #1751: Varia: Faux button style is broken
While I was testing the new Calendly block that adds a link with `.button` class (faux button). Varia tries to style it like a button, but it's broken on the front of the site. It looks fine in the editor.

Screenshot 2020-01-17 at 00 18 47

Twenty Twenty style it correctly.

Screenshot 2020-01-17 at 00 19 38

It should be displayed as an inline-block element. Calendly block is soon to be released so it'd be great if we can fix this in Varia and all the child themes quickly.

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #1751 

<table>
<tr>
<td>Before:
<br><br>

#1751-before
</td>
<td>After:
<br><br>

#1751-after
</td>
</tr>
</table>

### CODE REVIEW

**Comment by iamtakashi** [comment]
@nielslange, thanks for working on the fix! 

I know this wasn't mentioned in the original issue, but can we make sure that the link won't have an underline at all? It'd be good to test with a parent block that has a background colour or/and image. For example, Group or Cover block.

**Comment by nielslange** [comment]
> @nielslange, thanks for working on the fix!
> 
> I know this wasn't mentioned in the original issue, but can we make sure that the link won't have an underline at all? It'd be good to test with a parent block that has a background colour or/and image. For example, Group or Cover block.

Sure, @iamtakashi! I'll adjust the PR according to your feedback later today and will create more test cases.

**Comment by nielslange** [comment]
## Editor

<table>
<tr>
<td>Before:
<br><br>

#1757-editor-before
</td>
<td>After:
<br><br>

#1757-editor-after
</td>
</tr>
</table>

## Frontend

<table>
<tr>
<td>Before:
<br><br>

#1757-frontend-before
</td>
<td>After:
<br><br>

#1757-frontend-after
</td>
</tr>
</table>

cc: @iamtakashi

**Comment by iamtakashi** [comment]
Thanks for the improvement! LGTM!!

**Pull request merged**
