### PR TITLE
Libretto: Prevent Title Block Link Overlap with Menu

### PR DESCRIPTION
**Pull request by torres126**
#### Changes proposed in this Pull Request:

This change should mean that only the image and the site title will redirect, allowing for the users to visit the intended pages by clicking their names on the menu. I've tried to explain it in this image here: https://prnt.sc/lkvaj0

#### Related issue(s):

#369

### CODE REVIEW

**Comment by laurelfulford** [comment]
Thanks for the patch @torres126!

I think a better approach might be to get the link out of the way, rather than changing it's behaviour -- I'm a little worried that could be confusing down the road for other people working on the theme.

I _think_ switching `.title-block .site-logo-link` to `display: inline-block` would be one option, though I need to test a bit more to make sure it won't cause other issues. Let me know what you think!

**Comment by torres126** [comment]
Hmm, maybe it's just me, but though that seems to stop the menu items linking to the home page, it seems to leave them unclickable completely? Agreed though, there's probably a better solution to this.

**Comment by torres126** [comment]
No luck in managing to align things yet I'm afraid. Added a commit (still a WIP) showing a possible solution, but it's pretty much useless without figuring an alignments. I'm wondering if there's even a better way to do this without touching the widths, but that does seem to be the problem here. My worry is it's the best solution too.

Out of curiosity though, what about touching the margins [here](https://github.com/Automattic/themes/blob/master/libretto/style.css#L2645)? If the icon was lowered beneath the menu, it'd solve both this issue but also more importantly the issue of menus overlapping with the site icon on tablets, and therefore being invisible. But then again, it's a pretty notable change.

**Comment by torres126** [comment]
I did a bit more testing and I think that this PR should work, since it centre aligns the title block without resorting to having it take up the full width, which isn't ideal as it's a link that overlaps the menu. It does mean line breaks will be after less characters now though, it seems.

**Comment by laurelfulford** [comment]
Thanks @torres126! Oof, this is a weird one. 

>  It does mean line breaks will be after less characters now though, it seems.

Thanks for catching that. That could be problematic, since this theme is already on live sites. 

What do you think about leaving the width as is, and instead give the menu a slightly higher z-index -- like: 

```
#site-navigation .menu {
  position: relative;
  z-index: 2;
}
```

This does mean a really long menu will run in front of the logo instead of behind it, but both aren't great, and I'm not sure there's a way around it that doesn't involve completely redoing the header (and likely changing how it looks).

**Comment by torres126** [comment]
Oops, I forgot about this one! But yep, there's probably no ideal way to address this, though that may just be the best option. Confirmed it works and solves the issue.

**Comment by laurelfulford** [comment]
Looks good! Thanks for all your work on this one, @torres126 - it was a doozy!

**Pull request merged**
