### PR TITLE
Quadrat: Fix Code block text color in the editor

### LINKED ISSUE #4625: Quadrat: Text unreadable in Code Block while editing
Though it shows up correctly on the front end, in the editor the text is currently looking too dark. It should be pink to pass contrast.

Captura de ecrã 2021-09-16, às 15 27 17

### PR DESCRIPTION
**Pull request by danieldudzic**
Closes #4625

### CODE REVIEW

**Comment by scruffian** [comment]
The problem here seems to be that WordPress.com is loading the theme.css files for blocks even though we don't add support for that in the theme. I think that's the problem we should address as I expect it causes other issues.

**Comment by jeffikus** [comment]
@scruffian is this something that wpcom does globally for all themes?

**Comment by danieldudzic** [comment]
@scruffian What's the process of including theme.css usually? What _should_ be causing the theme.css file to be enqueued?

**Comment by scruffian** [comment]
There's two theme.css files, one that is used by the child theme, in this case Quadrat. That file is being enqueued by functions.php in Quadrat.

There's also a theme.css file that is used by blocks, which Gutenberg adds. This provides opinionated styles for blocks. This file is only used when a theme adds support for it via `add_theme_support('wp-block-styles')`, which we don't do for Blockbase themes. I'm not sure why this file is being added on wpcom... yet!

**Comment by scruffian** [comment]
Fixed by D67673-code

**Pull request closed without merging**
