### PR TITLE
Update block canvas styles

### LINKED ISSUE #6592: Design improvement suggestions to Block Canvas
In order to improve Block Canvas as a starting point to build themes, there are a few improvements I suggest.

The first one is the theme links states. Here's a comparison between Blockbase and Block Canvas' hover states, Blockbase being what I consider to be ideal:

**Blockbase:**

https://user-images.githubusercontent.com/65220155/191051561-3ce6e70f-196b-4c27-914a-b1e76e189ded.mp4

**Block Canvas:**

https://user-images.githubusercontent.com/65220155/191051601-85b3232a-5749-49f5-8a76-7fdb8511ee33.mp4

That said, it would be nice if links in Block Canvas followed the described behaviour:
- **Post titles and post date:** no underline on default, underline on hover
- **Site title and navigation links:** no underline on default, underline on hover
- **Links within paragraphs, post tags and categories:** underline on default, no underline on hover

Additionally:
- in Post Meta I suggest **replacing "Post Author" with "Post Author Name"**: that link should not be underlined on default, but on hover

I've created a [Figma file](https://www.figma.com/file/W7jjWeU2cstPfJ36Knjbu2/Block-Canvas?node-id=0%3A1) with the templates to show a visual example.

[This theme](https://andersnoren.se/themes/beaumont/) is the reference for link states and also the underline thickness.

### PR DESCRIPTION
**Pull request by madhusudhand**
#### Changes proposed in this Pull Request:

* Fixes the issues with links (pseudo states)
* Updates button styles ( :hover state has secondary color, needs review if this color is okay )
* Updates spacing to match Figma definition
* Updates typography of headings
* Moves footer template to pattern to enable translations.
* Updates min WP version to 6.0

#### Related issue(s):

#6592

### CODE REVIEW

**Comment by beafialho** [comment]
Thanks @madhusudhand. I'm afraid I cannot see any changes in my testing 😞  Could you please paste some screenshots/videos when you have a minute?

**Review by mikachan — COMMENTED** [review]
These changes are looking good!

It looks like the pseudo-states of the comments block and post-terms block need updating. These are underlined by default and don't change on hover. If we should be mimicking the behaviour in Blockbase, then all the links should behave the same (with no underline by default, and an underline on hover, etc).

Although, I don't think this is good for accessibility. I believe the links in the main body should be underlined, based on the [accessibility guidelines](https://make.wordpress.org/themes/handbook/review/accessibility/required/#content-links). Perhaps we should follow this rule for all links outside of the header and footer?

**Comment by beafialho** [comment]
> Although, I don't think this is good for accessibility. I believe the links in the main body should be underlined, based on the [accessibility guidelines](https://make.wordpress.org/themes/handbook/review/accessibility/required/#content-links). Perhaps we should follow this rule for all links outside of the header and footer?

@mikachan FYI: I mention [here](https://github.com/Automattic/themes/issues/6592) which links should be underlined. Links in the main body should be underlined.

**Comment by mikachan** [comment]
Ah thanks! I didn't see those in the original issue.

**Comment by madhusudhand** [comment]
@beafialho Here are few recordings and screenshots of the new changes. Let me know if you need any specific details.

https://user-images.githubusercontent.com/1935113/193745648-9ce882b5-00a7-47a2-9ea5-b23a9b3dce1d.mp4


https://user-images.githubusercontent.com/1935113/193745670-37a715a5-cad7-4a2c-b75d-dd65e5d7559f.mp4


https://user-images.githubusercontent.com/1935113/193745682-6ec87f6b-6102-459d-9d54-3ea4c7da59af.mp4

Spacing:

| Before | After |
| --- | --- |
| image | image |
| image | image |
| image | image |

**Review by mikachan — APPROVED** [review]
> It looks like the pseudo-states of the comments block and post-terms block need updating. These are underlined by default and don't change on hover. If we should be mimicking the behaviour in Blockbase, then all the links should behave the same (with no underline by default, and an underline on hover, etc).

I'm not seeing these issues now - I can see the correct hover states on all the links. I'm not sure what happened, I'm guessing it was a caching issue or something!

Do we want to set a different visual active and focus state on text links, and an active state on buttons?

Everything else looks good to me from a technical perspective 👍

**Comment by beafialho** [comment]
Thank you @madhusudhand! All looks good, I only two requests. 

The link underline is too thick and close to the word in your screenshots.

- Let's apply `text-underline-offset: .15em` to all links.
- And can we also make the underlines thinner as in [here](https://andersnoren.se/themes/bjork/blog/)?

**Comment by madhusudhand** [comment]
@beafialho Thanks for the inputs. Updated underline offset and thickness.

Before:
image

After:
image

Before:
image

After:
image

**Comment by beafialho** [comment]
Thank you! I believe this looks good!

**Pull request merged**
