### PR TITLE
DOS: Add theme

### PR DESCRIPTION
**Pull request by madhusudhand**
#### Changes proposed in this Pull Request:

Add new theme DOS, designed by @henriqueiamarino

image

### CODE REVIEW

**Comment by madhusudhand** [comment]
@henriqueiamarino Home template has an excerpt and also post content blocks, and the content appears to be redundant. Is this intentional?

image

**Comment by henriqueiamarino** [comment]
When I designed it, I considered blog posts to have an exclusive excerpt highlighting the text. But now it doesn't make much sense on a theme with no highlights, following vintage UIs aspect. Can you remove the excerpt, or do you want me to do it, @madhusudhand?

**Comment by henriqueiamarino** [comment]
In fact, I will conduct the changes and will let you know @madhusudhand thanks you.

**Comment by henriqueiamarino** [comment]
Hey @madhusudhand, DOS is updated — here and on the P2 as well.

[dos.zip](https://github.com/Automattic/themes/files/12213287/dos.zip)

**Comment by madhusudhand** [comment]
Thanks for the updates @henriqueiamarino 

I have only one comment on the text `is a theme designed by Automattic`. It doesn't go well with site title except for the demo site. Can you confirm?

image

Everything else looks good. Its a nice theme!

**Comment by henriqueiamarino** [comment]
Yes, thanks @madhusudhand this is a bit old; I didn't remember I added that line. It was removed anyway.

[dos.zip](https://github.com/Automattic/themes/files/12249834/dos.zip)

**Comment by madhusudhand** [comment]
Thanks @henriqueiamarino for addressing the comments.

I have pushed them here and theme is now ready. 🚢

**Comment by henriqueiamarino** [comment]
Hey @madhusudhand, here are the issues I found while building DOS [demo site](https://dosdemo.wordpress.com/):

- Headings still have Rubik as a standard font. Rubik is not present on the theme; I used JetBrains Mono only. I fixed it.
- Post-meta is missing from the demo site. It shows a template part error there. To fix it, I detached the Pattern and added the group again — it might need another fix from your side. I am not sure.
- The mobile view is breaking by a separator I added after the post-meta, inside the post-template. I fixed it by allowing the row to wrap to multiple lines. Should I edit the theme and upload it again?

**Comment by madhusudhand** [comment]
Can you zip and upload the theme from Automattic/themes `trunk` branch in demo site and do these changes, so that it would be easier merge those chases.

Attach the zip after final changes here. I will bring them in.

**Comment by henriqueiamarino** [comment]
I am unsure if that will do as I can't save a theme without _Create Block Theme_, and I fixed it on the demo already. I'll try to revert to the original and do it anyway.

**Comment by henriqueiamarino** [comment]
I fixed it on [my](https://dos.mystagingwebsite.com/) demo site, exported it, and updated the P2 with this file.

I am sorry for all the changes. I didn't know how to adjust many settings properly when I designed this theme — mainly related to the mobile view. This is the final update, anyway. Please, let me know when this is ready so I can launch it. Thanks @madhusudhand.

[dos.zip](https://github.com/Automattic/themes/files/12302666/dos.zip)

**Comment by madhusudhand** [comment]
@henriqueiamarino Provided fixes are merged and deployed here #7301

**Pull request merged**
