### PR TITLE
Multiple themes: fix right/left arrows in RTL mode

### PR DESCRIPTION
**Pull request by yoavf**
We use hardcoded numerical values for left-right arrows in CSS. 
Those need to be mirrored in RTL mode. 

Example issue (hever in this case) - the arrow is pointing the wrong way:
Screen Shot 2021-01-07 at 15 10 58

#### Changes proposed in this Pull Request:
- The first commit replaces the right arrow css (\2192 or \02192) with left arrow ( \2190 or \02190) and vice versa, using a directive for RTLCSS.
- The 2nd commit adds the result of running `npm run build:rtl` in all supported directories
- The next few commits address specific themes that use the manually built rtl.css file

### CODE REVIEW

**Review by jffng — APPROVED** [review]
Thanks @yoavf — this LGTM!

**Before**
Screen Shot 2021-01-07 at 12 24 53 PM

**After**
Screen Shot 2021-01-07 at 12 27 39 PM

**Comment by scruffian** [comment]
We'll need to bump version numbers for these themes before we merge this.

**Comment by jffng** [comment]
> We'll need to bump version numbers for these themes before we merge this.

I can do this.

**Comment by jffng** [comment]
On this branch, if I running `npm run build` within varia, the meaningful changes are overwritten. Here's the git diff:

```
diff --git a/varia/style-editor.css b/varia/style-editor.css
index b840a944..1feb0414 100644
--- a/varia/style-editor.css
+++ b/varia/style-editor.css
@@ -388,7 +388,7 @@ object {
 }
 
 .wp-block-a8c-blog-posts .more-link:after {
-	content: "\02192" /*rtl:"\02190"*/;
+	content: "→";
 	display: inline-block;
 	margin-left: 0.5em;
 }
diff --git a/varia/style-rtl.css b/varia/style-rtl.css
index 62ce2c4e..d27be499 100644
--- a/varia/style-rtl.css
+++ b/varia/style-rtl.css
@@ -3185,7 +3185,7 @@ body:not(.fse-enabled) .footer-menu a {
 }
 
 .entry-content .more-link:after {
-	content: "\02192";
+	content: "→";
 	display: inline-block;
 	margin-right: 0.5em;
 }
diff --git a/varia/style.css b/varia/style.css
index e4140977..e2ada450 100644
--- a/varia/style.css
+++ b/varia/style.css
@@ -3204,7 +3204,7 @@ body:not(.fse-enabled) .footer-menu a {
 }
 
 .entry-content .more-link:after {
-	content: "\02192" /*rtl:"\02190"*/;
+	content: "→";
 	display: inline-block;
 	margin-left: 0.5em;
 }
```

The same goes for running `npm run children` — the RTL changes are overwritten and replaced with `content: "→"`


I'm not sure what to do, because the sass looks correct.

**Comment by scruffian** [comment]
Does adding an RTL ignore comment fix it?

**Comment by MaggieCabrera** [comment]
From the [rtlcss docs](https://rtlcss.com/learn/usage-guide/value-directives/):

> 
>     SASS/SCSS will omit comments placed inside the declaration value from the output CSS.
> 
>     To preserve RTLCSS value directives, Use SASS interpolation syntax passing your comment as string.
> 
>     .example {
>       font-size:16px #{"/*rtl:14px*/"};
>     }

**Review by scruffian — COMMENTED** [review]
@yoavf @jffng I think this is now working correctly

I had to enclose the rtl comment in some special syntax so it outputs correctly.

This also has the unintended consequence of converting the character codes to UTF-8 but they seem to still work ok...

**Review by jffng — APPROVED** [review]
I rebuilt varia itself as well for good measure. This LGTM.

**Pull request merged**
