### PR TITLE
Blockbase: Remove style variations

### LINKED ISSUE #6941: [Bug]: Blockbase child themes & incompatible style variations
### Quick summary

Jackson's Charcoal style variation has white background text and Jackson has a white background. This isn't easy to read.

Ruby wine | Charcoal
-------|------
 | 

There are several more examples of this and similar issues with other blockbase child themes - skivers has the same style variations and they just change a thin button outline.

The style variations don't belong to the individual themes but rather their parent theme - blockbase. The variations were [added](https://github.com/Automattic/themes/pull/6167/commits/4cbb43dc10fd419f5334e0d7a768204a3c9af1dc) and [named](https://github.com/Automattic/themes/pull/6167/commits/d75c385c81f5710c77bf1073dddd8215fe8806a4) in #6167 but only started becoming visible in child theme after WP6.2 was merged to wpcom (see fbhepr%2Skers%2Sjcpbz%2Sjc%2Qvapyhqrf%2Spynff%2Qjc%2Qgurzr%2Qwfba%2Qerfbyire.cuc%3Se%3Qn8028o5p%23685-og & D104877-code for the merge and https://github.com/WordPress/gutenberg/pull/46554 for the initial GB change)

### Steps to reproduce

1. Activate the Jackson theme
2. In the site editor use the GS sidebar to set the style variation to charcoal

### What you expected to happen

To be able to read the text

### What actually happened

Couldn't read the text

### Browser

Mozilla Firefox

### Context

p1680136513400279-slack-C048CUFRGFQ passSY-5Al-p2#comment-11903

### Platform (Simple, Atomic, or both?)

_No response_

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

 * Don't use that style variation
 * Do use it and change the text colour

### PR DESCRIPTION
**Pull request by mmtr**
#### Changes proposed in this Pull Request:

As of [Gutenberg 15.1](https://github.com/WordPress/gutenberg/pull/46554)/[WordPress 6.2](https://github.com/WordPress/wordpress-develop/pull/3901), child themes inherit the style variations of the parent theme.

This is causing issues to Blockbase child themes such as Jackson in WordPress.com, because the headstart content for a child theme is only created for the default style variation. When a different style variation is applied, the styles from the headstart content are incompatible with the new variation:

https://user-images.githubusercontent.com/1233880/230398566-f5abd9a1-c558-4016-9734-201c430d81d3.mov

To mitigate that, and following [this suggestion](https://github.com/Automattic/themes/pull/6996#issuecomment-1500275877) from @pbking, this PR removes the style variations from the Blockbase theme, so users are no longer able to select them for either the parent or any child theme.

This is an alternate approach of https://github.com/Automattic/themes/pull/6996 / D107265-code, which only removes the variations for Blockbase child themes and keeps them on the parent theme.

#### Testing instructions:

- Apply these changes to your WP.com sandbox: `npm run deploy:push:changes`
- Also apply these changes to your sandbox to avoid issues with the `themes` cache while testing:

```diff
diff --git a/wp-content/lib/wpcom-themes.php b/wp-content/lib/wpcom-themes.php
index 534de104e0..7a2e46d7d9 100644
--- a/wp-content/lib/wpcom-themes.php
+++ b/wp-content/lib/wpcom-themes.php
@@ -2099,7 +2099,8 @@ class WPCom_Themes {
        }
 
        public static function get_style_variations( $stylesheet ) {
-               $style_variations = wp_cache_get( "style_variations_$stylesheet", 'themes' );
+               //$style_variations = wp_cache_get( "style_variations_$stylesheet", 'themes' );
+               $style_variations = false;
 
                if ( $style_variations === false ) {
                        $theme_demo_site = wpcom_get_theme_demo_site( $stylesheet );
@@ -2156,7 +2157,7 @@ class WPCom_Themes {
                                $style_variation['slug'] = sanitize_title( $style_variation['title'] );
                        }
 
-                       wp_cache_set( "style_variations_$stylesheet", $style_variations, 'themes', 5 * MINUTE_IN_SECONDS );
+                       //wp_cache_set( "style_variations_$stylesheet", $style_variations, 'themes', 5 * MINUTE_IN_SECONDS );
                }
 
                return $style_variations;
```
- Sandbox the API
- It's also recommended to use an incognito window/private session to avoid issues with the cached API responses by Calypso.
- Go to the WP.com Design Picker (`wordpress.com/setup/site-setup/designSetup?siteSlug=<SITE_DOMAIN>`)
- Search a Blockbase child theme such as Jackson
- Make sure it does not have any style variation
- Go to WP.com > Appearance > Themes
- Search a Blockbase child theme such as Jackson
- Make sure it does not have any style variation
- Activate it
- Go to WP.com > Appearance > Editor
- Open the Styles sidebar
- Make sure it does not have any style variation

#### Related issue(s):
Fixes https://github.com/Automattic/themes/issues/6941.

### CODE REVIEW

**Comment by BogdanUngureanu** [comment]
Works as expected for free themes. However, for Skivers, I've noticed that the style variations still appear. I think this is because premium themes have a blockbase-premium theme.

**Review by BogdanUngureanu — APPROVED** [review]

**Comment by pbking** [comment]
Should we migrate some of these removed style variations to those child themes that they DID work in?  It doesn't just remove the variations that don't work, it also removes many that do.

**Comment by pbking** [comment]
It seems that the problem is specific to a particular pattern.  Rather than removing all of the potentially valuable variations we instead fix the pattern in question. 

See [this comment](https://github.com/Automattic/themes/pull/6996#issuecomment-1502284392) for more details.

**Comment by mmtr** [comment]
Abandoning this in favor of https://github.com/Automattic/themes/pull/6996.

**Pull request closed without merging**
