### PR TITLE
Curator: update link and button styles

### LINKED ISSUE #5996: Curator: Button States
I gave it a closer look and concluded that burgundy background color doesn't work well for the buttons. Can we make these changes, please?

Captura de ecrã 2022-05-11, às 11 55 07

Currently, the buttons have a dashed underline/outline that doesn't look like the mockups, let's be rigorous about the details and make it match.

| Now | Intended |
| ------ | ------ |
| Captura de ecrã 2022-05-11, às 11 43 40 | Captura de ecrã 2022-05-11, às 11 42 37 |

### PR DESCRIPTION
**Pull request by mikachan**
#### Changes proposed in this Pull Request:
This PR updates the link and button styles to match the mocks in #5996.

Default:
image

Hover:
image

Click/focus:
image

Active:
image

#### Related issue(s):
Closes #5996

### CODE REVIEW

**Review by jffng — COMMENTED** [review]
Thank you for picking this up @mikachan! 

I noticed a few things:

1. When the button is linked and is clicked, both the hover and active visual states are present: 

Screen Shot 2022-05-25 at 10 14 27 AM

2. When I click on a linked outline button, the border is still black: 

Screen Shot 2022-05-25 at 10 21 30 AM

3. Gutenberg provides default CSS for the "visited" state that makes the text of buttons white:
Screen Shot 2022-05-25 at 10 16 20 AM

This results in the text of the button not showing at all, since the background is also white. Is this a bug in Gutenberg, or should we address that somehow here?

**Comment by mikachan** [comment]
Thanks @jffng! 1 & 2 should now be fixed.

> Is this a bug in Gutenberg, or should we address that somehow here?

I've seen this at least once before when working on themes, so I'm thinking it's something that should be addressed in Gutenberg, probably as part of addressing hover/focus/active state styles (here are some related issues: https://github.com/WordPress/gutenberg/issues/28063, https://github.com/WordPress/gutenberg/issues/27075).

I've added a fix in the theme for now.

**Comment by pbking** [comment]
I notice that a 'filled button' doesn't have the same padding as an outline button.  Should it?

image

```
<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center","orientation":"horizontal"}} -->
<div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"white","width":100,"style":{"color":{"text":"#1267ed"}}} -->
<div class="wp-block-button has-custom-width wp-block-button__width-100"><a class="wp-block-button__link has-white-background-color has-text-color has-background wp-element-button" style="color:#1267ed">Text</a></div>
<!-- /wp:button -->

<!-- wp:button {"width":50,"style":{"color":{"background":"#ffbb00","text":"#0c0c0c"}}} -->
<div class="wp-block-button has-custom-width wp-block-button__width-50"><a class="wp-block-button__link has-text-color has-background wp-element-button" style="color:#0c0c0c;background-color:#ffbb00">Solid</a></div>
<!-- /wp:button -->

<!-- wp:button {"textColor":"black","width":50,"style":{"color":{"gradient":"linear-gradient(160deg,rgb(0,166,141) 0%,rgb(119,255,0) 98%)"}}} -->
<div class="wp-block-button has-custom-width wp-block-button__width-50"><a class="wp-block-button__link has-black-color has-text-color has-background wp-element-button" style="background:linear-gradient(160deg,rgb(0,166,141) 0%,rgb(119,255,0) 98%)">Gradient</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->
```

**Comment by mikachan** [comment]
> I notice that a 'filled button' doesn't have the same padding as an outline button. Should it?

Thanks @pbking and @beafialho. The 'fill' button now has the same padding as the 'outline' button. Here's what it looks like in the different states:

Default:
image

Hover:
image

Click/focus:
image

Active:
image

With a custom background:
image

**Comment by pbking** [comment]
This now addresses the problem with a custom background color, however I'm not sure that the padding is appropriate when there isn't one.  Would it be helpful to use that padding based on the button having a .has-background class or something?

**Comment by mikachan** [comment]
> Would it be helpful to use that padding based on the button having a .has-background class or something?

Yep good idea, I've applied the padding to just the buttons with a background now. Does this look better?

**Comment by pbking** [comment]
👍 Looks good to me!
🚢

**Review by pbking — APPROVED** [review]

**Pull request merged**
