### PR TITLE
Fontaine: Add theme

### PR DESCRIPTION
**Pull request by iamtakashi**
#### Changes proposed in this Pull Request:
Add Fontaine theme.  pNEWy-ict-p2

screenshot

### CODE REVIEW

**Review by vcanales — CHANGES_REQUESTED** [review]
There are a couple of issues with markup, seen on the 404 and Single Post templates:

image

image

**Comment by iamtakashi** [comment]
Oh, thanks for spotting that. I'll take a look!

**Comment by iamtakashi** [comment]
Sorry about that! It was likely copy-and-paste errors. It should be good now.

**Comment by iamtakashi** [comment]
Sorry, @vcanales, let me commit one more thing before you start reviewing again. I found something else to fix!

**Comment by iamtakashi** [comment]
Thanks for waiting! It's now ready for the review.

**Review by vcanales — APPROVED** [review]
LGTM! Thanks :)

**Pull request merged**
