### PR TITLE
Fix button discrepancies in Varia

### LINKED ISSUE #3232: Varia / Hever: Button color discrepancies between editor and frontend
## Steps to replicate

Initially reported [here](https://github.com/Automattic/themes/pull/3223#issuecomment-776111311).

Create a copy of this post (pcrugM-jc-p2) as a reference on your test site.
Compare the contents of the editor and the frontend.

> The buttons that are different:
> Stock Outline
> Primary Outline
> Background Outline
> Primary/Secondary Outline
> 
> Removing [this line](https://github.com/Automattic/themes/blob/trunk/varia/sass/blocks/button/_style.scss#L22) in Varia's button styles (untested in other child themes) seems to correct the style of outline buttons on the view eliminating the discrepancies. (with the exception of a "Stock Outline" button which still renders incorrectly in the EDITOR only) There may be a better way to address that, but that's what my sleuthing uncovered.

## Result

107403577-4567b400-6ad3-11eb-83de-c8248a3e6fdb

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
This aligns the editor and frontend styles for buttons more closely. Ideally these files would be the same but I'm reluctant to make more changes than are needed in case it surfaces more bugs.

I have only rebuilt Hever to make it easier to review, so to test you'll need to use Hever.

#### Related issue(s):
Fixes #3232

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
I tested this on Hever with the darker color palette active and testing with Jason's pretty buttons page (pcrugM-jc-p2) there are still some inconsistencies:

Frontend:

Screenshot 2021-02-11 at 11 21 18
Screenshot 2021-02-11 at 11 21 14

Editor:

**Comment by scruffian** [comment]
That's weird, this is what I see. Editor:

Screenshot 2021-02-11 at 17 34 32


Frontend:
Screenshot 2021-02-11 at 17 34 50

**Comment by pbking** [comment]
My instance matches @scruffian 

From what I can tell this change will be GTG with a complete build.

**Review by MaggieCabrera — APPROVED** [review]
Yep, must have been something wrong with my sandbox, this looks ok now for me, thank you!

**Pull request merged**
