### PR TITLE
Russell: Update the navigation to match Blockbase

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
This takes the navigation from Blockbase to Russell, bringing in Social Links, right alignment, and a smaller font for the tag line.

### CODE REVIEW

**Comment by pbking** [comment]
Should we apply the navigation block style?

Before:


After:

**Comment by pbking** [comment]
The other bits look good. If you think the block style is 👍 I think it's GTG.

**Comment by scruffian** [comment]
Oh yeah we should, nice one.

**Comment by alaczek** [comment]
Will you be pushing this change to .com

**Comment by scruffian** [comment]
Yes, this will get pushed when we next deploy

**Pull request merged**
