### PR TITLE
#3863: Intergalactic 2: Newspack Heading Fixes

### LINKED ISSUE #3863: Intergalactic 2 Post Carousel title alignment off
### Steps to reproduce the behavior

1. Activate theme **Intergalactic 2**
2. Add a Post Carousel block
3. See alignment issue on post titles in published page/post

#### What I expected to happen

Titles should be left aligned

#### What actually happened

There is a huge space on the left, making titles run off the right-side of the block

### Context

3991957-zd-woothemes

Similar issue with another block here: https://github.com/Automattic/themes/issues/2609

#### Is this specific to the applied theme? Which one?

Intergalactic 2

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

All sites using this theme. (Confirmed on test site.) Impact low.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

image

#### Workaround

Adding the following CSS code fixes the issue.

```
.singular .wp-block-newspack-blocks-carousel .entry-title {
	width: unset;
	text-align: left;
}
```

### PR DESCRIPTION
**Pull request by bobmatyas**
### Changes proposed in this Pull Request:

This PR fixes three inter-related issues with the Blog Post blocks.

##### Editor View:

editor

##### Frontend View:
Screenshot on 2022-06-23 at 12-35-14

#### After

Screenshot on 2022-06-23 at 12-33-55

### Related issue(s):

Closes #3863, #3403, #2609

### CODE REVIEW

**Comment by madhusudhand** [comment]
@bobmatyas Can you update the PR with testing instructions?
Also, I do not find the `Post Carousel` block in the latest WP install. Is that coming from a plugin?

**Comment by bobmatyas** [comment]
@madhusudhand Sorry about that. This uses the Newspack Blocks plugin https://github.com/Automattic/newspack-blocks which is installed on WPCOM by default. If you install that, you can then test by creating a page with a "Homepage Posts" block with a grid view and one with a list view.

Here are two screenshots showing the settings (I grabbed the settings when another theme was installed, so it doesn't match what's above):

Screenshot on 2022-07-12 at 12-49-22
Screenshot on 2022-07-12 at 12-48-58

**Review by madhusudhand — COMMENTED** [review]
Changes look good for alignment issues. 
Unrelated to these changes, I see that post title and excerpt link are set `white` color and so they are not visible.

**Editor:**
image

**Frontend:**
image

**Post Title color:**
image

**Excerpt link color:**
image

**Comment by bobmatyas** [comment]
I added a fix for the titles so that they are visible and match what shows in the editor:

### Frontend 

Screenshot on 2022-07-14 at 15-06-26

### Editor

Screenshot on 2022-07-14 at 15-06-55

It would probably be best to fix that purple color for the links in both the editor and on the site, but that changes the existing behavior and might best be addressed in a new PR?

**Review by madhusudhand — APPROVED** [review]
LGTM!

**Pull request merged**
