### PR TITLE
_dsgnsystm: Fix text-alignment and padding in pullquote block

### PR DESCRIPTION
**Pull request by allancole**
#### Changes proposed in this Pull Request:

- Fixes text alignment in pullquote block
- Fixes left padding on blockquotes in pullquote block

**Before**

image

**After**

image

#### Related issue(s):

#1087

### CODE REVIEW

**Comment by iamtakashi** [comment]
In the editor, because of the lack of max-width that are specified for the front of the site, it's a lot wider. (as you can see the right aligned pull quote is pushed down) But this looks like a core bug.

Screen Shot 2019-07-18 at 19 12 10

**Comment by allancole** [comment]
@iamtakashi Yeah, I’m thinking we should remove the `max-width: 50%;` setting on all left/right aligned blocks. Even when a block is floated we don’t want to set an explicit width without also giving users a way to change that width in the editor. Using the image block as an example, a customer can set the image width to 25%, 50%, 75%, etc. If a customer chooses 25% in the editor, that’s what they get. They should also get 25% on the frontend, but with this rule in place they’d be stuck with 50% on the frontend with no way to change it.

In you’re screenshot above, the two blocks are actually floating naturally and since the right-aligned block has one extra character, it’s slightly too wide to float in that instance, but with less text it should float properly.

**Comment by iamtakashi** [comment]
> I’m thinking we should remove the max-width: 50%; setting on all left/right aligned blocks. Even when a block is floated we don’t want to set an explicit width without also giving users a way to change that width in the editor.

👍

**Comment by allancole** [comment]
That last commit fixes the max-width issue mentioned here: https://github.com/Automattic/themes/pull/1093

Gonna go ahead and merge this.

**Pull request merged**
