### PR TITLE
Block Canvas: update comments pattern.

### LINKED ISSUE #6563: Blank Canvas: Integrate Pixl's Comment Changes
> Henrique had a nice https://github.com/Automattic/themes/pull/6520 to the spacing and sizing overall in Pixl that I think could be worked in [to Block Canvas].

See [this comment](https://github.com/Automattic/themes/pull/6542#pullrequestreview-1105976788).

These would be good changes to have.  I'm not sure if/how much of the included CSS should be brought over.  My 'druthers is to keep that out if possible even if that means not all of the improvements come through.

If further adjustments need to be made via CSS that should probably go in the cloned theme (Decibel) rather than Block Canvas.

### PR DESCRIPTION
**Pull request by jffng**
#### Changes proposed in this Pull Request:

This PR makes the following changes to the comments in Block Canvas, to make it a cleaner starting point:

- Updates spacing values to use presets and relative values
- Removes styling opinions about the avatar

Before | After
--- | ---
Screen Shot 2022-09-14 at 9 05 32 AM | Screen Shot 2022-09-14 at 9 04 57 AM

#### Related issue(s):

Fixes #6563

### CODE REVIEW

**Review by vcanales — APPROVED** [review]
LGTM!

**Comment by pbking** [comment]
The FSE is telling me that there's some block funnyness going on here:

image

**Comment by jffng** [comment]
> The FSE is telling me that there's some block funnyness going on here:

Thanks, fixing bugs in block markup is very tedious and frustrating. Fixed in https://github.com/Automattic/themes/pull/6575/commits/40683fa49ce148c9b33ec54418d87993d3b37a30.

**Comment by pbking** [comment]
> fixing bugs in block markup is very tedious and frustrating

You speak the truth.

Problems solved, bringing this in.  Thank you!

**Pull request merged**
