### PR TITLE
Saison: add theme

### PR DESCRIPTION
**Pull request by beafialho**
Saison is a clean, modern theme for restaurants, bakeries and other food businesses. It comes with page patterns and style variations that allow you to quickly design and launch your website.

### CODE REVIEW

**Comment by jasmussen** [comment]
Working on fixing the conflicts in #8000, which can be a replacement for this PR.

**Comment by jasmussen** [comment]
Oh, @alaczek jinx, we worked on the same one! Sorry about that. I made #8000 as a replacement, because I've not found a good way to update these forked playground PRs directly. But I'm happy to close 8000 if that helps?

**Comment by alaczek** [comment]
> But I'm happy to close 8000 if that helps?

Yes, please :)

**Comment by alaczek** [comment]
I fixed a few more issues, most notably static path to images in patterns. I think this theme should be good to merge.

**Comment by beafialho** [comment]
Thank you for your reviews! Does this one need a version bump before I submit it to WordPress.org?

**Comment by alaczek** [comment]
I wouldn't know, maybe @vcanales can answer that?

**Pull request merged**
