### PR TITLE
Varia: Fix link and button color settings

### LINKED ISSUE #3250: Varia + children: Links and Outline Buttons same color as primary background
## Steps to replicate

1. Varia or a child theme active
2. In post or page, add a block with background color set to primary color (e.g. cover, group, or media & text block)
2. Inside block add a regular link, or a button with outline (otherwise default colors)

## Result

The link and button are invisible because they are also showing the primary color.

Screenshot with Barnsbury:

barnsbury-button-color

Screenshot with Exford:

exford-button-color

Can be seen on my test site:
https://badaboomtest.wordpress.com/testing-colors/?theme=pub%2Fvaria
https://badaboomtest.wordpress.com/testing-colors/?theme=pub%2Fbarnsbury
https://badaboomtest.wordpress.com/testing-colors/?theme=pub%2Fexford

## Expected

The link and button color should contrast the background so it can be seen.

From what I can see, the themes all adjust the regular text colors for elements with background color using CSS such as:
```
.has-primary-background-color:not(.has-text-color),
.has-primary-background-color.has-background-dim:not(.has-text-color) {
	color: white;
}
```
but there is no corresponding CSS for links and buttons to override the primary color being applied to links and buttons in this situation.

A possible fix may be to just include links in the above CSS:

```
.has-primary-background-color:not(.has-text-color),
.has-primary-background-color:not(.has-text-color) a,
.has-primary-background-color.has-background-dim:not(.has-text-color),
.has-primary-background-color.has-background-dim:not(.has-text-color) a {
	color: white;
}
```

* User report: 27566071-hc

Maybe related to these issues, but not sure:
https://github.com/Automattic/themes/issues/2582
https://github.com/Automattic/themes/issues/3232

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
This is another approach to fix #3250. This should just target cases when links and outline buttons are inside elements that share their default color.

Can only be tested in Dalston, to make the code easier to review.

#### Related issue(s):
#3250

### CODE REVIEW

**Comment by pbking** [comment]
Tested in a cover block and group, the result was the same.

Works well for links and outline buttons.  Not so much standard buttons.

image

**Comment by danieldudzic** [comment]
There's also an issue with Color Settings.

I have tested this inside of a Group block:
color_settings

**Comment by scruffian** [comment]
@danieldudzic good catch. I tightened up the selector to not work in that case. Should be good for another review...

**Comment by danieldudzic** [comment]
@scruffian there still seems to be an issue
still_an_issue

**Comment by scruffian** [comment]
@danieldudzic how are you seeing that issue? I can't reproduce (https://scruffiansimple.wordpress.com/2021/02/24/buttons-test/)
Screenshot 2021-02-24 at 09 43 26

**Comment by danieldudzic** [comment]
@scruffian https://danieldudzic.wordpress.com/button-dalston/

bug-2

**Comment by scruffian** [comment]
@danieldudzic I think this must have been a caching issue. I bumped the version numbers. Mind having another look? This is what I see on your sandbox:

Screenshot 2021-02-24 at 17 30 33

**Comment by danieldudzic** [comment]
LGTM 👍

**Pull request merged**
