### PR TITLE
Varia: Fix Mobile `.alignwide` widths to match normal width

### PR DESCRIPTION
**Pull request by allancole**
#### Changes proposed in this Pull Request:

- Makes `.alignwide` widths match the normal content width on mobile screens. 
- Also recompiles all Varia child themes to apply this fix. 
- Recompiling child themes also applies improvements from #1194 and #1204.  

#### Related issue(s):

#1192 

#### To do:

- [x] Improve nested calculations (ie: `calc( calc() )`): https://github.com/Automattic/themes/compare/enhancement/mobile-alignwide-width?expand=1#diff-b6d805de0184172207b2b53df97b66d7R3216
- [x] Test all child themes to make sure compiling other PRs hasn’t broken anything.
- [x] Fix issue where white space is removed from `calc()` which makes them not work in Chrome and FF.

### CODE REVIEW

**Comment by iamtakashi** [comment]
Thanks for working on this. This is definitely better for mobile. 👍 

The tiny width difference between wide and normal can still see in every brea point above for example this is what it appears with 782px viewport:

Screen Shot 2019-08-08 at 15 33 41

I started to wonder if we should make wide width form 1024 or even 1280 and above. Similar to the responsive pattern in editor. https://cld.wthms.co/MOlSJr 

Let me know your thoughts on this.

**Comment by allancole** [comment]
> The tiny width difference between wide and normal can still see in every brea point above for example this is what it appears with 782px viewport: 

> I started to wonder if we should make wide width from 1024 or even 1280 and above. Similar to the responsive pattern in editor. https://cld.wthms.co/MOlSJr

Yeah, it should match the editor behavior as closely as possible when it makes sense. I think increasing the threshold for the `.alignwide` breakpoint should be fine for the front-end. I’ll take another look there and move it up one size (from `large/tablet` to `x-large/desktop`)

**Comment by iamtakashi** [comment]
Sorry for not being able to review this sooner. 

I had the impression of we're going to make wide width element behaves the same as normal until desktop or at the point where the normal width fully expanded. I'm not saying this is how it should be, just wondering what most makes sense. This is what I see in the editor.

Sep-06-2019 13-55-11

Again, I don't know if this is the best, and the normal width behaves differently between the editor and the front-end anyway.

**Comment by allancole** [comment]
Ahhh, yeah I see what you mean. 

> I had the impression of we're going to make wide width element behaves the same as normal until desktop or at the point where the normal width fully expanded

Yeah, I missed that detail :-) The last commit above makes it work that way, and while it doesn’t exactly mirror the editor, I do think it’s the better solution. 

simple-wide-width-test

Check it out and let me know what you think.

**Comment by iamtakashi** [comment]
That looks great. In this way, we can avoid the situation where the difference between wide and normal is just a few pixels :)

**Pull request merged**
