### PR TITLE
Illustratr: Fix Blog Post Block grid width

### LINKED ISSUE #1774: Illustratr: Unable to display posts in a grid using the Blog Post block
## Steps to replicate

1. Add [the Blog Posts block](https://en.support.wordpress.com/wordpress-editor/blocks/blog-posts-block/) to a new page.
2. Tweak the settings of the Blog Posts block so that posts will display in a three-column grid.
3. View the page.

## Result

Posts displayed in one-column, despite the settings to display the posts in a three-column grid.

## Expected

I expected posts to display in a three-column grid, as per the block's settings. 

It seems the `flex-basis` is not working as expected in the CSS, but I'm not sure why.

Screenshot 2020-01-30 at 23 54 54

I've provided the user with the following CSS workaround for now:

```
@media only screen and (min-width: 782px) {
    .wpnbha.columns-3 article {
        width: calc(33.333% - 16px);
    }
}
```

* User report: #2668727-zen

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #1774 

<table>
<tr>
<td>Before:
<br><br>

#1774-before
</td>
<td>After:
<br><br>

#1774-after
</td>
</tr>
</table>

### CODE REVIEW

**Review by SiobhyB — APPROVED** [review]
Looks great, thanks so much Niels!

**Comment by nielslange** [comment]
@SiobhyB Thanks for testing this PR. I requested an additional review from @mendezcode as he's working with the themes team.

**Review by danieldudzic — CHANGES_REQUESTED** [review]
Please make sure the fix is comprehensive enough to cover the post meta, and its layout in the editor:
meta

Also, instead of hiding the post meta top border, please adjust the styling to match the regular posts feed.

**Comment by kjellr** [comment]
I pushed some small changes: 

- Moved this to the `blocks.css` file, and changed the specificity to make sure it's only targeting the Blog Posts block (other blocks might also use the `is-grid` class).  
- Added a light editor style adjustment to match the post title styles up just a little more closely (but only slightly... it looks like getting the Illustratr editor styles in sync with the front end is a larger project). 

These are light touches, mostly just aimed at getting the grid view working. I'm not too worried about 100% exactly matching the regular posts feed in the grid view, since the normal posts feed doesn't have a grid view available. 

I'll merge this in, and we can continue iterating from there.

**Pull request merged**
