### PR TITLE
Bysshe: Add theme

### PR DESCRIPTION
**Pull request by iamtakashi**
Add the Bysshe theme created by @mtias and @pablohoneyhoney. pNEWy-hIc-p2

This theme carries an image from Unsplash, this will not be submitted to WP.org and be available on WP.com only.

screenshot

### CODE REVIEW

**Comment by iamtakashi** [comment]
> Found a reference to unsplash.com

Yes, the designer, Matías, is fine with this theme being only on WP.com. Let me know when it's ok to merge.

**Comment by MaggieCabrera** [comment]
This is looking good to me. I don't know about the paragraphs with the dots and translations, since they are decorative, maybe we could use `esc_html_x` for those to add context for translators so they know that they are just symbols? It's still not super accessible but I think it shouldn't be a blocker

`esc_html_x( 'Title', 'context for translators', 'text-domain' );`

**Review by MaggieCabrera — APPROVED** [review]

**Comment by iamtakashi** [comment]
@MaggieCabrera Thanks for the review. That is a good point to use `esc_html_x` for those decorative text elements, but I wonder if they need to be translated. What do you think?

**Comment by iamtakashi** [comment]
Anyway, I've changed it to use `esc_html_x()` for the symbols. I'll merge it when it passes the automated checks.

**Pull request merged**
