### PR TITLE
Pique: Disable zooming into site logo on hover

### LINKED ISSUE #1770: Pique: Logo zooming in and out on Firefox when hovering
## Steps to replicate

1. Go to the Pique theme demo site using Firefox: https://piquedemo.wordpress.com/
2. Hover over the logo with your cursor.

GIF of the zooming:

https://cldup.com/-TLTqwJqgO.gif

## Result

The logo zooms in and out, making it hard to click.

## Expected

The logo should stay as it is.

This CSS seems to be causing it:

```
.site-branding .site-logo-link:hover {
transform: scale(5%);
}
```

This CSS prevents it from happening:

```
.site-branding .site-logo-link:hover {
transform: none;
}
```

* User report: [#3522963-hc]
* Follow-up ticket: [#2668950-zd]

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #1770

### CODE REVIEW

**Comment by melchoyce** [comment]
Is there any way to test just this PR without checking out the entire themes library?

**Comment by nielslange** [comment]
> Is there any way to test just this PR without checking out the entire themes library?

@melchoyce According to https://stackoverflow.com/a/13738951 you should be able to checkout the affected theme folder by running a so-called sparse checkout. Please let me know if you’re facing issues doing so. I’m happy to post the exact commands for you then. 😉

**Comment by melchoyce** [comment]
I... use the desktop app, not CLI 😅

**Comment by nielslange** [comment]
In that case, you might have to check out the entire repo. 😜

**Comment by mendezcode** [comment]
Fixed in *r55211-wpcom-themes*.

**Pull request merged**
