### PR TITLE
Varia: Updates the version numbers for Varia so we can deploy our changes

### PR DESCRIPTION
**Pull request by scruffian**
Just a version number bump.

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
I think we could change the minor version for these changes (https://semver.org/)

**Review by kjellr — APPROVED** [review]
LGTM

**Comment by MaggieCabrera** [comment]
Bumped to a minor version, this should be good to go

**Review by jffng — APPROVED** [review]
🚢

**Pull request merged**
