### PR TITLE
Bibimbap: address dotOrg review feedback

### LINKED ISSUE #6869: Bibimbap: dotOrg review feedback
### Address the following [review feedback](https://themes.trac.wordpress.org/ticket/133456) for dotOrg

[Skip link](https://make.wordpress.org/themes/handbook/review/required/#skip-links) - not ok
  - non-existent on the home page
  - readme.txt

missing license information for
  - cooper-hewitt font
  - bibimbap-map.png

### PR DESCRIPTION
**Pull request by madhusudhand**
#### Changes proposed in this Pull Request:

This change adresses dotOrg review feedback from [here](https://themes.trac.wordpress.org/ticket/133456)

#### Related issue(s):

Fixes: #6869 

Related: #6801

### CODE REVIEW

**Comment by madhusudhand** [comment]
@beafialho do you have any license reference for the map image?

image

**Comment by beafialho** [comment]
No @madhusudhand, I do not 😕

**Comment by jffng** [comment]
> do you have any license reference for the map image?

It looks like it was just a screengrab of google maps with an overlay. Is that attributable?

**Comment by pbking** [comment]
It looks like this theme [has already shipped](https://themes.trac.wordpress.org/ticket/133456) on [wporg](https://wordpress.org/themes/bibimbap/), even without these changes.

I'm not sure what to do about the map screengrab, but considering that it has launched anyway, can we just forget about that?

I see that the screenshot has been changed to match the index template, however that increased the size pretty dramatically.  I compressed it and I think it's back to normal now.

I've also added the 'main' tag to the home template post content block to support the skip link mentioned.  However, I've got more questions regarding the naming of the 'home' templates for this theme.

Why is it named wp-custom-template-home.htm and not home.html?  And why don't the changes I made to that file reflect in my site? :P 

I think that we should change the name of that template, and with that change this PR is probably good to ship and close the 'dotorg changes' task.

[EDIT]

Nevermind, I didn't realize there had been changes to the theme since these changes.

**Comment by pbking** [comment]
Few changes and gets them shipped to dotorg.

This is good to go now.  Sorry for my confusion above. :)

**Pull request merged**
