### PR TITLE
Pendant: Add missing tags

### PR DESCRIPTION
**Pull request by andres-blanco**
Fixes triggering home page replacement from Calypso on the Pendant theme.

related D84737-code

### CODE REVIEW

**Review by pbking — APPROVED** [review]
LGTM

**Comment by jffng** [comment]
Should these two tags (`auto-loading-homepage` and `blog-homepage`) be added to all of our block themes?

**Comment by madhusudhand** [comment]
For the context, recently I have seen a change here https://code.a8c.com/D84609#change-T95mUDZ01Af7 where the tag `blog-homepage` removed from `remote` while deploying changes.
May be because it was added in Phabricator directly and with removed comparing to themes repo.

**Comment by madhusudhand** [comment]
For the context, recently I have seen a change here D84609-code where the tag `blog-homepage` removed from `remote` while deploying changes.
I guess it is for the same reason. 
It was added in Phabricator directly and removed on next deployment because it was not there in themes repo.

**Pull request merged**
