### PR TITLE
Seedlet & Spearhead Custom Link Color

### PR DESCRIPTION
**Pull request by pbking**
#### Changes proposed in this Pull Request:

Changes the shape (or adds) theme.json files from the following Pull Requests:

Seedlet:
https://github.com/Automattic/themes/pull/3271
https://github.com/Automattic/themes/pull/3274

Spearhead:
https://github.com/Automattic/themes/pull/3133

#### Related issue(s):
https://github.com/Automattic/themes/issues/3243

#### Diff
D57441-code

### CODE REVIEW

**Comment by jffng** [comment]
Custom link colors are still not working for me in the view:

Editor | View
------- | ------
Screen Shot 2021-02-22 at 3 49 10 PM | Screen Shot 2021-02-22 at 3 49 17 PM

**Comment by scruffian** [comment]
It's not working in the view for me either - I tested in a cover block...

**Comment by pbking** [comment]
I found and fixed an [issue with the cover block specifically](https://github.com/Automattic/themes/pull/3325/files#diff-0518cab2ad99da1c18c91f1dd4a82bc31b1d8ddb55e49325d76c0370c96c4017R17) where the specificity of some anchor styling was preventing the 'link' style from cascading properly.  

I suspect there are other blocks with the same situation, I'll comb through spearhead and see where else it might be occurring. 

@jeffikus I was unable to reproduce your screenshot however (tested both Spearhead and Seedlet).  It only KINDA happened for me when I was testing and had SEEDLET in the editor, switched themes (but didn't reload the editor) and set the color to that green (secondary color) which isn't a color provided by Spearhead so it rolled back to the 'default'.  But that seems like I was trying too hard...

**Comment by pbking** [comment]
Shoot...
The "cover block" fix noted above breaks styles when a custom link is NOT applied.  Need to re-evaluate further...

**Comment by scruffian** [comment]
I pushed a fix to Seedlet colors for this, just needs another review...

**Comment by MaggieCabrera** [comment]
A cover block with custom link color shows differently on the editor vs the frontend:

**Editor:**
Screenshot 2021-03-02 at 10 19 44

**Frontend:**
Screenshot 2021-03-02 at 10 19 40

**Comment by scruffian** [comment]
Yeah sorry I forgot to update the editor styles too. Should be good to go now...

**Comment by pbking** [comment]
In the editor, in a GROUP with background {Primary}
A P with link-color set to {Foreground} renders correctly in the editor
image
but not so in the view:
image
Perhaps .has-link-color should be included in 
`.has-background:not(.has-background-background-color) a:not(.has-text-color):not(.wp-block-button__link)` which is coloring the link to 'currentColor'.

**Comment by scruffian** [comment]
This will be a lot easier to resolve once this is fixed: https://github.com/WordPress/gutenberg/pull/29557

**Comment by scruffian** [comment]
I removed a bunch of code from Seedlet to fix this. Some of this code was added in this PR: https://github.com/Automattic/themes/pull/3088

I think if you run the latest version of Gutenberg it will all work as expected, but there could be more cases I've not considered...

Screenshot 2021-03-04 at 13 09 11

**Review by MaggieCabrera — APPROVED** [review]
I could not get this to break, it looks good to me!

**Pull request merged**
