### PR TITLE
Tú: Initial commit

### PR DESCRIPTION
**Pull request by iamtakashi**
Adds a new theme Tú, a personal profile theme having a simple pattern on the front page.

iamtakashi jurassic tube_

### CODE REVIEW

**Comment by iamtakashi** [comment]
Hi @Automattic/theam!

Could you review this? Thanks in advance!

**Comment by iamtakashi** [comment]
Thanks for the note on pNEWy-fMJ-p2. I'll change the `front-page.html` to `home.html`.

**Comment by iamtakashi** [comment]
I've renamed the template from `front-page.html` to `home.html`.

I've also changed the `inherit` option for the post list pattern to `false` because the pattern will likely be used on a page since the user will need to make a posts page by themselves because of the quirk of `home.html`

Let me know if anything needs to change. Thanks in advance!

**Review by vcanales — APPROVED** [review]
Thanks for renaming the home! LGTM :)

**Comment by iamtakashi** [comment]
Thanks, @vcanales!  I've added a small fix making sure the footer pattern is full-width.

I'll deploy it to WP.com tomorrow!

**Pull request merged**
