### PR TITLE
Pixl: refine the comments.

### LINKED ISSUE #6459: Pixl: Styles: Comments
Update comments block styles.

Design: Cm51iCQSPu8Ar1qufDTeOQ-fi

image

And update the font settings of the comments block.

Current state:
image

### PR DESCRIPTION
**Pull request by jffng**
#### Changes proposed in this Pull Request:

Modifies the comments form and comment reply styles.

Screen Shot 2022-09-07 at 11 52 00 AM

@beafialho @henriqueiamarino could you advise on the above screenshot?  

I did not adjust the layout of the comments form since it would require CSS and is not editable by the user, do you think its layout is acceptable as is? 

#### Related issue(s):

Fixes #6459

### CODE REVIEW

**Comment by henriqueiamarino** [comment]
Hey @jffng I assume the layout can go as it is but I'd like to learn about the spacing marked in red. Is that editable? If yes I can help you with that.
An extra question, just as I am still new to that: Is it possible to enlarge the **comment's section** width a little? This way we wouldn't have that single word suspended as a widow.
response-feedback

**Comment by jffng** [comment]
@henriqueiamarino 

>  Is that editable?

Yes!

> Is it possible to enlarge the comment's section width a little?

We could make the comments section wider, but in that case it wouldn't align with the post content above it. What do you think?

**Comment by beafialho** [comment]
> We could make the comments section wider, but in that case it wouldn't align with the post content above it. What do you think?

The comments section should align with the post content. I'd just make sure that text is 12px. About it being a widow, I believe that could be unavoidable if a screen is scaled up or down @henriqueiamarino.

One detail: the tick box should match the other boxes.

Captura de ecrã 2022-09-08, às 16 11 06

**Comment by henriqueiamarino** [comment]
@jffng I believe this would make spacing more coherent.
response-feedback

**Comment by madhusudhand** [comment]
Updated the spacing and fonts.

image

**Comment by madhusudhand** [comment]
Changes looks good. Bringing it in. Any more changes will be addressed after the theme review by designer.

**Review by madhusudhand — APPROVED** [review]

**Pull request merged**
