### PR TITLE
Spearhead: styles for native jetpack related posts

### LINKED ISSUE #2647: Spearhead: Jetpack related posts should be styled to match the original site.
Current: 

Screen Shot 2020-10-21 at 9 48 47 AM

Spearhead.co: 

Screen Shot 2020-10-21 at 9 48 42 AM

### PR DESCRIPTION
**Pull request by MaggieCabrera**
#### Changes proposed in this Pull Request:

This PR adds styles for Jetpacks's native related posts to fit the design.

To test go to any post page on the demo and compare the related posts to the design/block styles.

Screenshot 2020-10-28 at 15 56 57

#### Related issue(s):

Closes #2647

### CODE REVIEW

**Comment by kjellr** [comment]
- It looks like the font size for titles is ending up as 18px instead of 20px
- We should change the line height for titles to 1.4. 
- Titles should be white by default.
- I'm seeing [a double underline](https://cloudup.com/cCN7yVmYRBN) on hover. 
- The context (category) should be changed to be the same size as post meta, and given a little top padding so that it is separated from the title: 

Before|After
---|---
Screen Shot 2020-10-28 at 11 36 35 AM|Screen Shot 2020-10-28 at 11 36 28 AM

**Comment by MaggieCabrera** [comment]
@kjellr where are you testing this? I can't get the "In Jetpack" text to show up

**Comment by kjellr** [comment]
It'll only show up for posts that have categories — the ones on the theam demo site do not have categories assigned.

**Comment by MaggieCabrera** [comment]
@kjellr this is ready for another review

**Comment by kjellr** [comment]
Thank you, @MaggieCabrera! This is looking much better. Just a couple small notes: 

1. I'm still seeing the category text (`jp-relatedposts-post-context`) appear larger and white — this should be  adjusted to match [the mockup above](https://github.com/Automattic/themes/pull/2721#issuecomment-718019263). 

Current|Recommended
---|---
Screen Shot 2020-10-28 at 1 34 23 PM|Screen Shot 2020-10-28 at 1 34 04 PM


2. Can we remove the top border above the related posts, and also make the "Related" header match the body text size? This will align with what happens on spearhead.co. 

Current|Recommended
---|---
Screen Shot 2020-10-28 at 1 36 33 PM|Screen Shot 2020-10-28 at 1 36 22 PM

3. If I hover in the just the right spot, I see a thick underline. 🤔 

 
hover

**Comment by MaggieCabrera** [comment]
>     1. I'm still seeing the category text (`jp-relatedposts-post-context`) appear larger and white 

Sorry I got confused by this:

> Titles should be white by default.

**Comment by MaggieCabrera** [comment]
@kjellr this should be better now hopefully

**Review by kjellr — APPROVED** [review]
🎉 Looks great, thank you @MaggieCabrera!

**Pull request merged**
