### PR TITLE
Mayland Blocks: Update buttons colors

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
This implements button colors using theme.json:

Screenshot 2021-03-03 at 19 08 19

### CODE REVIEW

**Comment by jffng** [comment]
Does this PR depend on a Gutenberg change that has yet to be merged?

I tested this on wpcom and using GB master and 10.1.0 locally without success. I would expect the background color to be set to a CSS custom property here, but it is not:

Screen Shot 2021-03-03 at 3 08 06 PM

**Comment by scruffian** [comment]
Yeah this will only work if you're running the latest Gutenberg

**Comment by pbking** [comment]
Compiling the latest gave me problems, running `npm install` like... 2-3 times?  seemed to get it to build.

Can confirm it works on latest!

**Review by MaggieCabrera — APPROVED** [review]
Can confirm it works for me as well!

**Pull request merged**
