### PR TITLE
Professio: add theme

### PR DESCRIPTION
**Pull request by henriqueiamarino**
Professio is created for individual teachers based on Annalee, a theme designed for personal coaches.

[Demo site](https://professio.mystagingwebsite.com/) | [Site content](https://github.com/user-attachments/files/17921870/professio.WordPress.2024-11-26.xml.zip)

screenshot

### CODE REVIEW

**Comment by henriqueiamarino** [comment]
@iamtakashi, please let me know how to fix the background images. CBT needs to link images better on the cover block.
I remember having the same issue on #7890, but I couldn't fix this one using the previous solution.

**Comment by iamtakashi** [comment]
> CBT needs to link images better on the cover block.

Interesting. I'm testing CBT to find out when it fails to localise. Because CBT correctly did it for some of the cover block instance in the theme.

**Comment by iamtakashi** [comment]
@henriqueiamarino I've pushed a [fix](https://github.com/Automattic/themes/pull/8462/commits/2e6dc8d366c7606a74f729a2692ef1213fb4459e) for the cover blocks. It looks like lots of changes, but I've just changed the URL of the background image from
`http://localhost.local/wp-content/themes/professio/assets/images/StockSnap_ESDCTK2C7Z_web.png` 
to
`<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/StockSnap_ESDCTK2C7Z_web.png` 
so it works on any site.

And move the content of each template to a pattern because we need to use the PHP function `get_template_directory_uri()`. 

Pull  my change by running `git pull` from this brunch, `add/professio` so you update your local copy with my change.

**Comment by iamtakashi** [comment]
It looks like CBT fails to localise the image in a cover block when one (or both) of the settings is on.  I've created an issue for it. https://github.com/WordPress/create-block-theme/issues/748

I'll continue reviewing the theme.

CleanShot 2024-11-26 at 23 52 08@2x

**Comment by henriqueiamarino** [comment]
Thanks, @iamtakashi. I pulled the changes as you asked me to.

**Comment by iamtakashi** [comment]
@henriqueiamarino The theme is solid! I only noticed a few things.

* Let's add the usual phrase for the query no results blocks on the archive, index, search, and home templates.
* Let the row block with the links and credit in the footer wrap to multiple lines for small screens. 
CleanShot 2024-11-27 at 17 56 56@2x
* Let's remove the term description block from the search results template. It will not print anything on the template.
* Remove these unused template parts,`parts/footer-simple.html` and `parts/time-to-read.html`.
* Remove these unused patterns, `patterns/no-results-content.php`, `patterns/services.php`, `patterns/testimonials.php`, `patterns/time-to-read.php`, `patterns/video.php`

**Comment by henriqueiamarino** [comment]
Thanks, @iamtakashi. I've checked and fixed the following issues:

- I added our default indicative sentence to the no-results block: Home, Archive, Index, and Search results;
- I allowed the last Footer block to wrap to multiple lines;
- I deleted the description block from the Search results template;
- I removed the unused template parts: footer-simple and time-to-read;
- I removed the unused patterns: no-results-content, services, testimonials, time-to-read, and video.

**Comment by iamtakashi** [comment]
Thanks for the update, @henriqueiamarino. I forgot to mention removing the Time to Read pattern from the JSON, and I just pushed [a change](https://github.com/Automattic/themes/pull/8462/commits/3b8d7c03c01f7dc5960fc99e27c8aabe173e9827) myself now.

The theme looks good to me. Ship it 🚢 !

**Pull request merged**
