### PR TITLE
Barnsbury: Add Color Annotations

### PR DESCRIPTION
**Pull request by kjellr**
Follows the mold of #1944 to add basic color annotations for Barnsbury. 

Screen Shot 2020-04-30 at 19 06 35
Still needs: 

- [x] Refinement around contrast. 
- [x] Double checking mobile styles.
- [x] Add featured color palettes.

### CODE REVIEW

**Comment by allancole** [comment]
@kjellr I tried to rebase this against `master` and for some reason it’s trying to do a merge this branch onto itself. I have no idea why or how this happened. When I look at my command logs, its shows `git rebase master` was run on this current branch, but the rebase commit shows this instead https://github.com/Automattic/themes/pull/1963/commits/51e4284ff80d0efd2f1bd45e82bc2e532ec1edd1 . I’m completely baffled. I did the exact same thing for [Balasana](https://github.com/Automattic/themes/pull/1950/commits/ab9cc8157217b22ba497d7161f010e35924ae48d), without issue. 

May need to skip this theme for now and come back to it.

**Comment by kjellr** [comment]
Wow — you're right, this PR got mixed up. 😅 I'll take a look at it too.

**Comment by kjellr** [comment]
@allancole I think I took care of it. I just updated from master, and fixed the conflicts (it was just the stylesheets, which needed to be recompiled). Seems generally ok now, but please double check.

**Comment by allancole** [comment]
Whew! Thanks @kjellr!! Thought I had to start over from scratch. 

> I just updated from master

Yeah, maybe I’ll try that for Brompton—`merge` instead of `rebase`.

**Pull request merged**
