### PR TITLE
Curator: Implement support for Button elements in theme.json

### LINKED ISSUE #6142: Vivre: add support for Button elements
As demonstrated in #6139, can we use the button element API on Curator to get rid of some CSS?

Specifically the search + file block button styles.

### PR DESCRIPTION
**Pull request by matiasbenedetto**
#### Changes proposed in this Pull Request:
Adding settings for button elements in theme.json and removing the CSS no longer needed

#### Related issue(s):
https://github.com/Automattic/themes/issues/6142

### CODE REVIEW

**Comment by jffng** [comment]
I am having trouble testing this because when I use Gutenberg trunk I get the following fatal error (I think unrelated to this PR because I get the same error using emptytheme):

```( ! ) Fatal error: Uncaught Error: Call to undefined function gutenberg_style_engine_get_block_supports_styles() in /Users/jeffreyong/Documents/THEMES/a8c-projects/gutenberg/lib/block-supports/elements.php on line 108```

And when I switch to a stable release, e.g. 13.5.2, the buttons appear like this:

Screen Shot 2022-07-06 at 5 23 30 PM

**Comment by matiasbenedetto** [comment]
@jffng is your dev env working fine? Can you reproduce this issue using the themes repo trunk branch?

I'm using the latest Gutenberg trunk version and it works fine for me. I'm getting this:
image

**Comment by pbking** [comment]
This is what I'm picking up for reg'ler buttons on this branch (and Gutenberg trunk) which looks like what the theme.json is expressing but not what the design shows. (I didn't expect an outline around the button).  If that's expected then carry on!

image

Figma:
image

The search block looks right to me:

image

**Comment by jffng** [comment]
I fixed my Gutenberg build and see the same thing as @pbking now. 

The default button states are incorrect now — there shouldn't be an outline or padding, and the hover state is picking up the incorrect colors.

**Expected**
Screen Shot 2022-07-08 at 10 13 33 AM

**This PR**
Screen Shot 2022-07-08 at 10 17 32 AM

I think this theme design is perhaps tricky because the default button blocks do not use the same style as other button elements (search, file, and comments).

**Comment by pbking** [comment]
Pushed an updated that I think fixes the above and also makes the theme look pretty good with the Gutenberg plugin not activated.

Buttons:
image

Hover state:
image
image

Button elements (search block):
image

Buttons (sans-Gutenberg):
image

Button elements (search block) sans-gutenberg:
image

**Comment by pbking** [comment]
I just realized that I changed the font family names in the change as well (from 'header and body' to the font family names).  I was going to open an issue for the same and shouldn't have made that change here.  Happy to back that out until we can discuss that further if need be.

**Comment by jffng** [comment]
Nice, it's now looking correct for button elements but not button blocks. 

The design for default button blocks has no padding, with an underline on hover (not a background color). See [above](https://github.com/Automattic/themes/pull/6166#issuecomment-1179043547) for the design intent.

> I just realized that I changed the font family names in the change as well (from 'header and body' to the font family names).

Hmm I guess it raises the question, is there any benefit to having semantically named font slugs? Perhaps a question to discuss with design folks as well.

**Comment by matiasbenedetto** [comment]
Thanks, @pbking and @jffng for your feedback and additions. I added a new commit around button and link styles.

**Review by jffng — APPROVED** [review]
I made one more [change](https://github.com/Automattic/themes/pull/6166/commits/d07155ae1e3c89e739703e87d395dc341ae9dd16) — remove the padding from default buttons via theme.json. 

LGTM!

**Pull request merged**
