### PR TITLE
Assembler: Add two new typography styles

### PR DESCRIPTION
**Pull request by alaczek**
Proposing two new font combos:
* Playfair Display + Figtree
* Rubik + Tilda Sans

I came up with these two font combos while working on ready made templates.

The Playfair Display + Figtree is meant to complement our offering of elegant font pairings.
The Rubik + [Tilda Sans](https://tilda.cc/lp/tildasans/) is a combo I grabbed from the [Cortado](https://cortadodemo.wordpress.com/) theme (swapping Plus Jakarta Sans for Tilda). 

| Playfair Display + Figtree | Rubik + Tilda Sans |
|--------|--------|
| image | image | 

cc @richtabor

### CODE REVIEW

**Comment by richtabor** [comment]
I'm not getting the Playfair Display to work here? 

CleanShot 2024-08-02 at 16 41 24

**Comment by richtabor** [comment]
Looks like fonts aren't loading properly for either.

I see, we need to register them in theme.json, like the other fonts. 

CleanShot 2024-08-02 at 16 42 10

**Comment by richtabor** [comment]
@beafialho what do you think of these font combinations?

**Comment by alaczek** [comment]
> I see, we need to register them in theme.json, like the other fonts.

Yep, I totally forgot to push the updated theme.json.

**Comment by richtabor** [comment]
I'm going to close this based on the typography improvements we did in https://github.com/Automattic/themes/pull/8421. Thanks!

**Pull request closed without merging**
