### PR TITLE
Add Block Style to Independent 2

### LINKED ISSUE #2444: Independent Publisher 2: Uncentered Captions
## Steps to replicate
From any site, using the block editor and this theme:
- Insert an image using the image block
- Add a caption
- Note the caption is centered in the editor
- Preview / publish and note the caption is not centered on the live site

## Result
Caption is not centered

## Expected
I'd expect it to be the same as the editor view, or as an image added from the classic editor.

* User report: https://wordpress.com/forums/topic/center-captions-below-single-image/

### PR DESCRIPTION
**Pull request by arcangelini**
#### Fixes
#2444 
#2454 

This addresses a few issues with Independent Publisher 2. Specifically captions and embeds.

#### Test
Before: https://llamaeatsagiraffe.wordpress.com/331-2/
After: https://business-plan.blog/sample-page/

I used Code Snippets to test the block style function.

```
// Add support for Block Styles.
		add_theme_support( 'wp-block-styles' );
```

### CODE REVIEW

**Review by scruffian — APPROVED** [review]
LGTM

**Comment by scruffian** [comment]
This looks good. Do you need help merging to wpcom? You'll need to bump the version number....

**Comment by arcangelini** [comment]
> This looks good. Do you need help merging to wpcom? You'll need to bump the version number....

@scruffian Yeah! I do not have sandbox so I will need some help merging into WPCOM and bumping this. Is bumping the version number something I can do without sandbox?

**Comment by scruffian** [comment]
Yeah the version number is simple, for future reference: https://github.com/Automattic/themes/pull/2672

**Pull request merged**
