### PR TITLE
Fixed Blockbase children style variations

### PR DESCRIPTION
**Pull request by rcrdortiz**
#### Changes proposed in this Pull Request:
Excluded some style variations that are not compatible with some Blockbase child themes. Now we can have Style Variations applied without needing to exclude the full list of style variations.

#### Related issue(s):
- https://github.com/Automattic/dotcom-forge/issues/7768
- https://github.com/Automattic/wp-calypso/issues/78559
- https://github.com/Automattic/themes/pull/6996#issuecomment-1503295866

### CODE REVIEW

**Review by dsas — COMMENTED** [review]
I think Kerr's charcoal style variation needs disabling too. It's mentioned on https://github.com/Automattic/wp-calypso/issues/78559 and the footer looks broken to me

Screenshot 2024-06-17 at 09 55 09

**Comment by rcrdortiz** [comment]
> I think Kerr's charcoal style variation needs disabling too. It's mentioned on [Automattic/wp-calypso#78559](https://github.com/Automattic/wp-calypso/issues/78559) and the footer looks broken to me
> 
> Screenshot 2024-06-17 at 09 55 09

Kerr doesn't seem to be in the themes repo.

**Comment by dsas** [comment]
> Kerr doesn't seem to be in the themes repo.

oops, didn't notice that it's a premium theme.

**Review by dsas — APPROVED** [review]

**Comment by mmtr** [comment]
Can we also fix the themes with issues noted in https://github.com/Automattic/themes/pull/6996#issuecomment-1503295866?

> Appleton (Charcoal: site title too dark, Ruby wine: Same as Default)
> Dorna (Ruby wine: Same as Default)
> Farrow (Charcoal: text too dark, Ruby wine: Same as Default)
> Heiwa (Ruby wine: Same as Default)
> Meraki (Ruby wine: Same as Default)
> Russell (Charcoal: low contrast text)
> Zoologist (White: Same as Default)

**Comment by rcrdortiz** [comment]
> Can we also fix the themes with issues noted in [#6996 (comment)](https://github.com/Automattic/themes/pull/6996#issuecomment-1503295866)?
> 
> > Appleton (Charcoal: site title too dark, Ruby wine: Same as Default)
> > Dorna (Ruby wine: Same as Default)
> > Farrow (Charcoal: text too dark, Ruby wine: Same as Default)
> > Heiwa (Ruby wine: Same as Default)
> > Meraki (Ruby wine: Same as Default)
> > Russell (Charcoal: low contrast text)
> > Zoologist (White: Same as Default)

Sure, I just added it to the list of related issues.

Fixing Zoologist is OOS (the problem isn't a side effect of propagating base theme style variations), it doesn't extend a base theme. The White variation is defined inside the Zoologist theme folder.

**Pull request merged**
