### PR TITLE
Morden: Revising layout styles to work with the improved responsive logic

### PR DESCRIPTION
**Pull request by allancole**
#### Changes proposed in this Pull Request:

- Revises the method for constricting the width of the `#page` wrapper.

#### Related issue(s):

Discovered after merging #1246

### CODE REVIEW

**Comment by iamtakashi** [comment]
@allancole It looks much better. Thanks for working on this.

The only thing I would change is the width of the inside of masthead. Can it be the same as other wide element?

localhost_8888_wordpress__page_id=1352

**Comment by allancole** [comment]
This should be good to go now @iamtakashi :-)

**Comment by iamtakashi** [comment]
LGTM 👍Thank you!

**Comment by allancole** [comment]
Great! Gonna merge this…

**Pull request merged**
