### PR TITLE
Varia: Remove color definitions from background settings

### LINKED ISSUE #1763: Varia: Button Text Colour in Blocks with Background Colour
I've noticed this while I was testing Calendly block. If a button is in a block that has a background colour, the button text colour changes to `currentColor`, and it becomes unreadable if the background colour is a light colour.

Screenshot 2020-01-24 at 12 27 43

### LINKED ISSUE #2548: Mayland: Buttons Block predefined colors issue
## Steps to replicate

1. Activate Mayland theme
2. Insert a Buttons block into a page/post
3. Choose predefined colors for fore- and background

## Result

Editor:
Button Block Color Settings

Front-end:
Front-end

Mayland CSS file:
Mayland CSS

## Expected

I expected the button to show the colors from the picked predefined color settings on the front-end, but it seems the CSS selectors are overwritten or not specific enough in the Mayland CSS file.
The front-end screenshot shows the CSS file line numbers, which are overwriting the chosen color.

### LINKED ISSUE #2844: Stratford Theme: Button Text Color Not Changing From Button Block Setting
## Steps to replicate

1. Activate the Stratford Theme.
2. Add a blank page.
3. Add dummy Content with Heading and Links
4. Add Button and change color form listed colors on Text Color and update the page
5. Color not changed
6. But If we select from Custom color picker. it works perfectly

Page Editor:

After Publish:

<h2>Browser / OS version</h2>

<p>Google Chrome — Version 86.0.4240.111 (Official Build) (64-bit)<br>Windows 10 Home Single Language — 20H2 (64-bit).</p>

## Result

Buttons text color not changed after choosing colors from age Editor > Button Block Setting > Color settings > Text Color

## Expected

Change the Color of Buttons Text, When choosing colors from Page Editor > Button Block Setting > Color settings > Text Color

* Follow-up ticket: 3509871-zd

### LINKED ISSUE #3150: Stow: Button Text Color Different in Editor & Page
## Steps to replicate

1. Open a page or post. 
2. Insert button block. 
3. Add texts in the button. 
4. Change texts color (to any color except white) and publish.
5. Check the page preview and published page. 

## Result

The button text color in the editor changes to the set color, while preview and published page shows the button text color in white. 
Changing theme fixes the button text color issue. 

**Editor (button text color is set to pink):** 

Screen Shot 2021-02-01 at 9 52 11 PM

**Preview & published page (button text color is white instead of pink):** 

Screen Shot 2021-02-01 at 9 52 26 PM

## Expected

Button text color will be the same in the editor, preview and published page. 

* User report: 3700147-zd (and testing on personal site, where I was able to replicate). 
* Follow-up ticket: 3700147-zd

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
This removes the color definitions from the background definitions for custom colors. This now means that if someone sets text and background colors without good contrast they will be hard to read, but I guess we have to give the user control :)

#### Related issue(s):
Fixes #3150
Fixes #2844
Fixes #1763

### CODE REVIEW

**Comment by jffng** [comment]
This is an alternative to #3182, and I like it better.

**Comment by pbking** [comment]
Also fixes: #2548 and #2866

An alternative but more specific approach: #3185

**Review by MaggieCabrera — COMMENTED** [review]
I think https://github.com/Automattic/themes/pull/3185 is closer to what we need because with this solution we are losing the default definitions of the blocks text color. Check that it's not always the same color, depending on the background the text color is defaulting to foreground or background color if no custom color is selected.

**Comment by scruffian** [comment]
Closing in favour of #3185

**Pull request closed without merging**
