### PR TITLE
Curator: add paragraph with quote block pattern

### PR DESCRIPTION
**Pull request by jffng**
#### Changes proposed in this Pull Request:

Adds Paragraph with Right Aligned Quote block pattern. 

Screen Shot 2022-06-15 at 11 59 46 AM

#### Related issue(s):

Part of #5935

### CODE REVIEW

**Comment by madhusudhand** [comment]
Set the `font-weight` of quote to `500` and tagline to `300`.

And in smaller media, space above the quote could reduce and needs some padding below the quote to separate it from next paragraph.

image

**Comment by jffng** [comment]
> Set the font-weight of quote to 500 and tagline to 300.

👍 

> And in smaller media, space above the quote could reduce and needs some padding below the quote to separate it from next paragraph.

I added a `20px` spacer in the last column to address this.

**Comment by jffng** [comment]
cc @beafialho this is ready for your review.

**Comment by beafialho** [comment]
This looks good as well!

**Pull request merged**
