### PR TITLE
Fix/seedlet pattern placeholder images

### PR DESCRIPTION
**Pull request by MaggieCabrera**
#### Changes proposed in this Pull Request:

As discussed in slack I added the images to the assets folder and included their dynamic url in the `register_block_pattern()` function

#### Related issue(s):

#2474

### CODE REVIEW

**Review by kjellr — APPROVED** [review]
Thank you, @MaggieCabrera! This looks great. I pushed a couple small changes (simplified the file names + added updated license info for the new images). This should be good to go!

**Comment by kjellr** [comment]
Actually one final thing — we should wrap the alt text in `__()` tags so they're translatable. 🙂

**Comment by MaggieCabrera** [comment]
> Actually one final thing — we should wrap the alt text in `__()` tags so they're translatable. 🙂

Yes, I will get to it. Should I deploy after that or just merge to GH? I heard you wanted to have multiple changes to seedlet before releasing a new version, right?

**Comment by kjellr** [comment]
Yeah, you can go ahead and merge + deploy to WP.com once that change is ready. Once we have a handful of updates, we'll raise the version number, update the changelog, and update on .org.

**Pull request merged**
