### PR TITLE
Skatepark: Add Testimonial block pattern

### PR DESCRIPTION
**Pull request by mikachan**
#### Changes proposed in this Pull Request:
This PR adds a Testimonial block pattern for Skatepark.

I couldn't see a design for the smaller resolutions, so I've had a go at stacking the elements and making the border full width (similar to some of the other elements). I also tried changing the blockquote from `flex` to `display: block` at mobile, as this makes the border the same width as the author content which looked nice too. @melchoyce, would appreciate any input from you!

| Larger Resolutions      | < 599px |
| ----------- | ----------- |
| desktop      | mobile    |

#### Related issue(s):
Part of #4308.

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
I understand the decision behind using the quote block but that means that we need to write a lot of CSS for it. Semantically it makes a lot of sense but it comes with a few problems:
- None of this CSS is customizable in the editor by the user
- As soon as the `testimonial` class is gone (for example: when we change themes) the style of the block changes dramatically

Maybe this is a good candidate to be a [Block Style](https://github.com/Automattic/themes/blob/0ce22c2eebf0ffb34289102dd37bda27a2ec7fe9/quadrat/inc/block-styles.php) if we stayed with the Quote Block approach. @kjellr @scruffian @jffng @pbking what do you all think? Should we do this kind of pattern with columns instead?

**Comment by jffng** [comment]
Hmm. While the copy in the design suggests the pattern is for a testimonial / quote, this kind of layout could be used for other kinds of text too. So I'm not 100% sold on using the quote for semantic reasons.

I think my first intuition would have been to make this pattern with columns: the first column with a separator + normal paragraph, and the second being a paragraph with a preset font size. Then adding a `wrap-reverse` to get the stacking order as @mikachan has shown above for < 600px.

The pattern might also be able to be achieved without columns, and purely using a group block + sidebar flex layout (page 124 of every-layout.dev).

**Comment by kjellr** [comment]
I think using a quote block style makes the most sense here. Some reasoning behind that: 

- We need some CSS in here so that it'll stack in the reverse order on mobile. 
- A block style is the official user-selectable way to apply a CSS class via a UI. 
- If the user switches themes, that block style disappears, but it'll still appear as a quote, which will maintain the role of each of the text fields here.

**Comment by MaggieCabrera** [comment]
Using a block style makes a lot of sense to me. Ideally in the near future the quote block will let you control better the style of the blockquote and the cite so we wouldn't need as much CSS for something like this

**Comment by mikachan** [comment]
Thanks so much all for the input. I'll try out a block style for the quote block next then. 

I used a blockquote for semantic reasons but I also completely understand the user may choose to use this for something that isn't a quote as well. 

> The pattern might also be able to be achieved without columns, and purely using a group block + sidebar flex layout (page 124 of every-layout.dev).

I really like the sound of this! I'll start with the quote block style, but this is great to have as another potential layout option.

**Comment by MaggieCabrera** [comment]
I think we still need the block pattern, we just need the block pattern to be using the block style :D Otherwise, this looks great to me

**Comment by mikachan** [comment]
> I think we still need the block pattern, we just need the block pattern to be using the block style :D Otherwise, this looks great to me

Ahh got it, will sort this!

**Comment by melchoyce** [comment]
Looking good 🙌 

Any chance we can artificially add some more space above the citation so it lines up a little better with the text? 

image

(@kjellr, do you think this is a bad idea because it'll be uneven if someone changes fonts?)

**Comment by kjellr** [comment]
> (@kjellr, do you think this is a bad idea because it'll be uneven if someone changes fonts?)

I think it's fine. 👍 We should maybe use an `em` or `ex` unit there.

**Comment by mikachan** [comment]
Thanks both! I've just added `margin-top: 1.5ex` to the citation, mainly because I really liked the idea of using `ex` here.

**Comment by MaggieCabrera** [comment]
> Thanks both! I've just added `margin-top: 1.5ex` to the citation, mainly because I really liked the idea of using `ex` here.

+1 it's a unit that makes sense to me when you really want to align things to the font, rather than just keep things generally proportional, LGTM!

**Review by MaggieCabrera — APPROVED** [review]

**Pull request merged**
