### PR TITLE
Blockbase: remove hardcoded flex justify content CSS rule for header component

### LINKED ISSUE #5066: Blockbase: Editor alignment styles do not apply to site header
## Steps to replicate

- Activate Blockbase
- Edit the header block in the Editor by aligning the items to the right or center
- The items do not change alignment

https://user-images.githubusercontent.com/1645628/142636423-30240657-eb7c-4e8e-b519-5c951cf07409.mov

It looks like this is because of two styles in _header.scss:

`justify-content: start;` ([here](https://github.com/Automattic/themes/blob/cdb5883c518ce7bc282998ffb6d5e4a2786841fb/blockbase/sass/base/_header.scss#L2)) & `flex-grow: 1;` ([here](https://github.com/Automattic/themes/blob/cdb5883c518ce7bc282998ffb6d5e4a2786841fb/blockbase/sass/base/_header.scss#L7))

### LINKED ISSUE #5078: Quadrat: changing justify settings in Header -> Row block has no effect
## Steps to replicate

1. Activate the Quadrat theme on your test site.
2. Activate Gutenberg plugin to enable the Site Editor.
3. Open the Site Editor and select `Header` -> `Row` block on the homepage.
4. Toggle the justify settings (left, center, right, space between).

## Result

Nothing happened.

## Expected

Nested Row items to move to the designated position.

### PR DESCRIPTION
**Pull request by matiasbenedetto**
#### Changes proposed in this Pull Request:
Blockbase: remove hardcoded flex justify content CSS rule for header component

#### Related issue(s):
https://github.com/Automattic/themes/issues/5078

### CODE REVIEW

**Review by scruffian — DISMISSED** [review]
I tested videomaker and blockbase. LGTM.

**Comment by mikachan** [comment]
I've tested this on Blockbase and I can't align the items in the header row, but I'm not sure if I'm doing something different. I'm testing on this branch with the latest GB trunk. Here's what I'm doing:

https://user-images.githubusercontent.com/1645628/143418644-86283353-6c4c-415b-989c-04ff17c4dc4a.mov

It looks like if I also remove `flex-grow: 1;` from `header.scss`, then I can apply alignment to the row:

https://user-images.githubusercontent.com/1645628/143419735-f6c41b9c-ea5f-4311-9015-464bd98e7552.mov

But I think by default we want the navigation to be right-aligned, and the other items on the left (at least in Blockbase). I'm not sure how to achieve this with the GB options! I'll have a think.

**Comment by MaggieCabrera** [comment]
I made an attempt at this over at https://github.com/Automattic/themes/pull/5102 and I ended up removing a lot of unneeded CSS but to make the behavior the same as the original menu I had to add a `flex-basis: 100%` that renders the justification attributes useless too... Headers are hard!!!

**Comment by MaggieCabrera** [comment]
I'm going to step out from this for a bit and work on other stuff but I think the key here is to remove most of the extra CSS we are adding to achieve the desktop layout and add whatever CSS is needed just to fix the responsive view. That way the user can still tinker in the editor successfully while we keep the responsive version consistent with the original design.

**Comment by matiasbenedetto** [comment]
Closing this PR in favor of https://github.com/Automattic/themes/pull/5120

**Pull request closed without merging**
