### PR TITLE
Remove fixed font-size from post title block on blockbase themes

### LINKED ISSUE #8046: Post Title block: changing heading level isn't respected in certain themes
### Quick summary

When changing the heading level in certain themes that seem to be child themes of blockbase, one cannot change the heading level of the Post Title block despite being able to change it in other themes, like OnyxPulse. Here's the original report: https://github.com/Automattic/wp-calypso/issues/74704

### Steps to reproduce

Pulling prior steps from https://github.com/Automattic/wp-calypso/issues/74704

> 1. Enable a theme compatible with the Site Editor Blockbase themes like Zoologist, Geologist, Quadrat, Arbutus but also some others like Stewart, Skivers, Bibimbap
> 2. Through the Site Editor, edit the Page template;
> 3. Click on the Post Title block, and through the Block toolbar change the Heading to h2, h3,h4…h6;
> 5. It doesn’t apply the change and keep’s it on H1;

### A clear and concise description of what you expected to happen.

The heading level to change. 

### What actually happened

The heading level didn't change. 

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by renatho**
#### Changes proposed in this Pull Request:

If we decide to go with this approach ([see this discussion in the issue](https://github.com/Automattic/themes/issues/8046)), it removes the fixed font-size from post title block on blockbase themes.

#### Related issue(s):

https://github.com/Automattic/themes/issues/8046

# Screenshots

With the screenshots, I also described if it was needed to change the child theme and the default tag of the post title in the page template.

## Blockbase

- Default heading tag: `h2`.

I took the screenshot from the "All Archives" template only for the Blockbase theme to save time.

#### Before

_blockbase-current

_blockbase-archive-current

#### After

_blockbase-without-fontsize-h2

_blockbase-archive-without-fontsize-h2

## Ames

- Default heading tag: `h2`.

#### Before

ames-current

#### After

ames-without-fontsize-h2

## Antonia

- Default heading tag: `h2`.

#### Before

antonia-current

#### After

antonia-without-fontsize-h2

## Appleton

- Default heading tag: `h2`.

#### Before

appleton-current

#### After

appleton-without-fontsize-h2

## Arbustus

- Default heading tag: `h2`.
- Also needed a change in the child `theme.json`.

#### Before

arbutus-current

#### After

arbutus-without-font-size-h2-needed-theme-change

## Attar

- Default heading tag: `h2`.

#### Before

attar-current

#### After

attar-without-fontsize-h2

## Barnett

- Default heading tag: `h2`.

#### Before

barnett-current

#### After

barnett-without-fontsize-h2

## Bennett

- Default heading tag: `h2`.

#### Before

bennett-current

#### After

bennett-without-fontsize-h2

## Blank Canvas

- Default heading tag: `h2`.

#### Before

blank-canvas-current

#### After

blank-canvas-without-fontsize-h2

## Calvin

- Default heading tag: `h2`.

#### Before

calvin-current

#### After

calvin-without-fontsize-h2

## Dorna

- Default heading tag: `h2`.

#### Before

dorna-current

#### After

dorna-without-fontsize-h2

## Farrow

- Default heading tag: `h2`.

#### Before

farrow-current

#### After

farrow-without-fontsize-h2

## Geologist

- Default heading tag: `h1`.
- Also needed a change in the child `theme.json`.

#### Before

geologist-current

#### After

geologist-without-fontsize-h1-needed-theme-change

## Hari

- Default heading tag: `h2`.

#### Before

hari-current

#### After

hari-without-fontsize-h2

## Heiwa

- Default heading tag: `h2`.

#### Before

heiwa-current

#### After

heiwa-without-fontsize-h2

## Jackson

- Default heading tag: `h2`.

#### Before

jackson-current

#### After

jackson-without-fontsize-h2

## Kingsley

- Default heading tag: `h2`.

#### Before

kingsley-current

#### After

kingsley-without-fontsize-h2

## Marl

- Default heading tag: `h2`.

#### Before

marl-current

#### After

marl-without-fontsize-h2

## Mayland (Blocks)

- Default heading tag: `h1`.
- Also needed a change in the child `theme.json`.

#### Before

mayland-blocks-current

#### After

mayland-blocks-without-fontsize-h1

## Meraki

- Default heading tag: `h2`.
- Also needed a change in the child `theme.json`.

#### Before

meraki-current

#### After

meraki-without-font-size-h2-needed-theme-change

## Quadrat

- Default heading tag: `h1`.
- Also needed a change in the child `theme.json`.

#### Before

quadrat-current

#### After

quadrat-without-font-size-h1-needed-theme-change

## Russell

- Default heading tag: `h2`.
- Also needed a change in the child `theme.json`.

#### Before

russell-current

#### After

russell-without-fontsize-h2-needed-theme-change

## Seedlet (Blocks)

- Default heading tag: `h1`.
- Also needed a change in the child `theme.json`.

#### Before

seedlet-blocks-current

#### After

seedlet-blocks-without-font-size-h1-needed-theme-change

## Winkel

- Default heading tag: `h2`.

#### Before

winkel-current

#### After

winkel-without-fontsize-h2

## Zoologist

- Default heading tag: `h1`.
- Also needed a change in the child `theme.json`.

#### Before

zoologist-current

#### After

zoologist-without-font-size-h1-needed-theme-change

### CODE REVIEW

**Comment by renatho** [comment]
I'm skipping the "Theme-Check results" since it's not related to the changes in this PR.

**Comment by allilevine** [comment]
I tested on Arbutus and Blockbase and I was able to change the heading levels and see the correct font size changes, both in the editor and on the live site. After that I couldn't get the site editor to load, it seems like a Playground issue.

**Comment by renatho** [comment]
Hi @Automattic/theam! 👋
Would some of you have the opportunity to take a look at this PR to solve the issue? Or is there anyone more involved with these themes that we could add as a reviewer?

**Review by mikachan — APPROVED** [review]
Thanks for working on this, @renatho! 

Based on the screenshots, I think this solution is fine. The code changes also look good. We can ignore both the Theme Check and Playground GH actions here since the checks are not related to these changes.

**Pull request merged**
