### PR TITLE
Quadrat: comment form style tweaks

### LINKED ISSUE #3898: Quadrat: Tidy up comment styles
- Change comment content's font size to `var(--wp--preset--font-size--normal)` to mirror the article text size. 
- Adjust space above + below comment content to `20px`.
- Add `30px` of vertical spacing in between comments.
- Add `60px` spacing between the last comment and the "Leave a Reply" header. 

Before|After
---|---
Screen Shot 2021-05-20 at 1 59 24 PM|Screen Shot 2021-05-20 at 2 05 02 PM

Group 6

### PR DESCRIPTION
**Pull request by MaggieCabrera**
#### Changes proposed in this Pull Request:

This PR styles the comments block to reflect the changes from https://github.com/Automattic/themes/issues/3898

Screenshot 2021-05-21 at 15 56 25

#### Related issue(s):

Closes https://github.com/Automattic/themes/issues/3898

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
I rebased this with the latest button changes and updated the screenshot with the latest changes too.

**Comment by MaggieCabrera** [comment]
I just updated this with Bea's comments from https://github.com/Automattic/themes/issues/3898 This is ready for another review.

**Review by danieldudzic — CHANGES_REQUESTED** [review]
This looks mostly fine.

If I have understood correctly, @beafialho [has suggested](https://github.com/Automattic/themes/issues/3898#issuecomment-845997424) that the comment text and button have the same font-size. At the moment there's still a slight discrepancy:

font_size

Also nested comments don't seem to be working - but I don't know if that's something we want to support (?)

**Comment by MaggieCabrera** [comment]
@danieldudzic I fixed the font size of the buttons. I do see the nested comments though:

Screenshot 2021-05-24 at 16 34 19

**Comment by pbking** [comment]
Font sizes and buttons styles all look 👍 
Confirmed that nested comments are working as well.

LGTM 🚢

**Pull request merged**
