### PR TITLE
Rainfall: add to deploy list, update screenshot, bump version

### PR DESCRIPTION
**Pull request by mikachan**
#### Changes proposed in this Pull Request:
Adds Rainfall to our dotorg deploy list.

### CODE REVIEW

**Review by madhusudhand — APPROVED** [review]
Looks good.

Should we bump the version to first major (1.0.0)?

**Comment by mikachan** [comment]
Thanks @madhusudhand! I've bumped the theme version too.

**Comment by mikachan** [comment]
I've updated the screenshot too from a discussion with @beafialho [here](p1664874758429639/1664816924.723079-slack-C029FM1EH).

**Review by madhusudhand — APPROVED** [review]
LGTM!

**Pull request merged**
