### PR TITLE
_dsgnsystm: Fix max-width for left/right aligned button blocks

### PR DESCRIPTION
**Pull request by allancole**
#### Changes proposed in this Pull Request:

- Reset the max-width on buttons with align left/right utility classes.

**Before**

image

**After**

image

#### Related issue(s):

- Fixes: #1084

### CODE REVIEW

**Comment by iamtakashi** [comment]
I'll share the concern. The max width on the utility class feels too aggressive. How about we remove the max-width and not fixing the buttons?

**Comment by allancole** [comment]
Good point and I agree. 

I’ll remove the max-width from the utility class, and instead place it only on the blocks that need this behavior: Cover, Image, Video, Embed, Quote, & Pullquote.

**Comment by iamtakashi** [comment]
Discussed and decided to remove `max-width: 50%;` [here](https://github.com/Automattic/themes/pull/1092#issuecomment-512981118). After that, we shouldn't need this fix.

**Comment by allancole** [comment]
With #1092 merged we no longer need this patch. Closing…

**Pull request closed without merging**
