### PR TITLE
Rockfield: Fix JS errors when header is hidden

### LINKED ISSUE #3388: Rockfield theme has Javascript errors when 'Hide Site Header' option is selected in the Customizer
## Steps to replicate

1. Activate the Rockfield theme
2. Set up a static front page (optionally including a Blog Posts block)
3. In the Customizer > Home Page Settings - turn on the 'Hide Site Header' option

## Result

When loading the home page - there are console errors:

```
Uncaught TypeError: Cannot read property 'offsetHeight' of null
    at pageHeaderHeight 
```

Any content which loads dynamically (like the 'More posts' button on a Blog Posts block) will not load.

## Expected

I expected the page to load normally - and for dynamic elements to load correctly.

----

I've checked with a few other themes which also have the 'Hide Site Header' option and was only able to recreate the error when Rockfield is active

### PR DESCRIPTION
**Pull request by danieldudzic**
Closes #3388

### CODE REVIEW

**Review by scruffian — APPROVED** [review]
LGTM

**Comment by scruffian** [comment]
Don't forget to update the version numbers and rebuild the downloads when you merge :)

**Comment by scruffian** [comment]
The package.json version number probably should be increased too.

**Comment by danieldudzic** [comment]
> The package.json version number probably should be increased too.

Thanks! Done :)

**Comment by jffng** [comment]
Was this deployed to wpcom? It shows up as a diff when I sync my local themes directory to sandbox.

**Comment by danieldudzic** [comment]
@jffng Yes - in r57944 & r57946

**Comment by jffng** [comment]
Ah okay. It looks like there are some differences now because of the linting that was recently introduced to the repo.

**Pull request merged**
