### PR TITLE
Varia buttons: Fix custom text color when button background color is set to "foreground" or "background"

### LINKED ISSUE #3365: Varia: Issues with button colors
## Steps to replicate

If you activate Stratford and choose to use the theme's homepage, the issue seen in the screenshot below will be replicated. 

Some button colors aren't showing properly on Stratford. They look fine in the editor, but not on the live site. 

This issue can be seen on our current Stratford theme demo: https://stratforddemo.wordpress.com/
Screen Shot 2021-02-25 at 3 47 31 PM

As well, there seems to be an issue with different states. I couldn't replicate this but have seen this in multiple reports (listed below). 

Normal state: 
Screen Shot 2021-02-25 at 3 39 41 PM

Active state: 
Screen Shot 2021-02-25 at 3 39 52 PM

Visited state: 
Screen Shot 2021-02-25 at 3 40 05 PM

## Result

Button isn't reflecting editor, active/hover/visited states are set to colors that cause visibility issues. 

## Expected

That the active, hover, and visited should be visible or there should be an option to set those separately. 

* User report: zd-3761048, hc-28020210

### PR DESCRIPTION
**Pull request by yashitamittal11**
**Description**

If the user selects the custom text color and background color for the button, the custom text color does not show on the live page. The color looks fine in the editor though.

**Changes proposed in this Pull Request:**

This PR ensures the custom text color selected by the user shows on the live site.

**Test instructions**

1. Add a button on a page.
2. Select a custom text color for the button.
3. Set the button background to "foreground" or "background" color.
4. The custom text color shows correctly in the editor. However, the color on the live page is not correct.

Note: The custom text color shows correctly if the user selects another color from the color palette. As in this case, the color is added via inline CSS. The issue is only visible when the user chooses the default theme color from the theme color palette.

**Also, this PR addresses only one part of the issue with the buttons on the Varia theme.**

| Before | After |
|---|---|
|  | Varia colors fixed |

#### Related issue(s):
Fixes https://github.com/Automattic/themes/issues/3365

### CODE REVIEW

**Review by madhusudhand — CHANGES_REQUESTED** [review]
Changes looks good.

@yashitamittal11 Can you run `npm run build` and `npm run children` inside `varia` directory and include those changes?

**Comment by yashitamittal11** [comment]
@madhusudhand Should I commit the following files?
style-rtl.css
style.css

**Comment by yashitamittal11** [comment]
I have committed the style-rtl.css and style.css files for all Varia's child themes except for Stow.
For Stow, style-rtl.css is not generated via this command "npm run children."

**Comment by madhusudhand** [comment]
> For Stow, style-rtl.css is not generated via this command "npm run children."

Thanks for pointing. There seems to be a syntax issue that got introduced in a previous commit. 
Can you remove the quotes around the closing `}` [here](https://github.com/Automattic/themes/blob/f17c82bcdf79b0dda6af85afa6ee3e68884b20f9/stow/sass/style-child-theme-editor.scss#L177) and re-run the command to include the stow changes too.

```font-family: #{map-deep-get($config-global, "font", "family", "code")};```

**Comment by yashitamittal11** [comment]
>Can you remove the quotes around the closing and re-run the command to include the stow changes too.

Thanks for the insight. I rerun the command after removing the quotes. I see three modified files now - 
1. ../stow/sass/style-child-theme-editor.scss
2. ../stow/style-rtl.css

The build job has added many formatting changes in the style-editor.css and style-rtl.css files. Is it okay to commit the files with these formatting changes?

style-rtl- stow

**Comment by madhusudhand** [comment]
>  I see three modified files now 

Yes, that is expected.

> Is it okay to commit the files with these formatting changes?

Yes. you can commit these changes as well.

**Comment by yashitamittal11** [comment]
Thanks. I have committed all the files.

**Review by madhusudhand — APPROVED** [review]
Thanks for working on this. Looks good to me.

**Comment by yashitamittal11** [comment]
>Also, this PR addresses only one part of the issue with the buttons on the Varia theme.

This PR addresses only one part of the problem discussed in the original issue. Should we reopen the original issue or create a new GitHub issue for the unsolved problem?

**Comment by madhusudhand** [comment]
I would suggest to keep the issue open and mention the parts that are fixed with this PR.

**Pull request merged**
