### PR TITLE
Quadrat: added polygons to header and footer

### PR DESCRIPTION
**Pull request by MaggieCabrera**
#### Changes proposed in this Pull Request:

This PR adds the squares from the design to the header and the footer. I tried using the group block as a control for the user to enable/disable/customize the color of the squares but it's not possible, since the background color is in the group block and we don't have access to a variable (in case the user uses a custom color). We could on the cover block because the color was actually on the before pseudoelement.

We could consider providing two different header/footer options for the user to use with or without the squares. I don't believe we can make a block style of the header/footer though.

I used clip-path instead of the square svgs because it was simpler to handle the overflow when the element was bigger than the viewport. The shapes are done "by eye" so they may need adjusting, but they are responsive and maintain aspect ratio no matter the screen size.

On big screens or posts with very little content, the top square and the bottom square are very close to one another. I'd love input from @beafialho and @kjellr about that. We could tweak with media queries so the proportions of the squares are different on some viewports (like forcing a max size of the squares for the bigger screens) or adapt the shapes so this issue is a little less prominent.

I've been headbutting a bit against this PR, so any new eyes that can point out other ways of achieving this or improving it are more than welcome.

Design:

Screenshot 2021-05-10 at 14 53 56

Header | Footer
--- | ---
ezgif-6-dc2d4b2b5081 | ezgif-6-35f211ea3934

### CODE REVIEW

**Comment by kjellr** [comment]
Thanks for working through this! We'll give it a test. 

> On big screens or posts with very little content, the top square and the bottom square are very close to one another. I'd love input from @beafialho and @kjellr about that. We could tweak with media queries so the proportions of the squares are different on some viewports (like forcing a max size of the squares for the bigger screens) or adapt the shapes so this issue is a little less prominent.

I think we'll need to hold off until https://github.com/Automattic/themes/issues/3784 and https://github.com/Automattic/themes/issues/3788 are resolved before we can really assess the proportions.

**Comment by kjellr** [comment]
This is looking good! I pushed a quick change to sync up with the header and footer changes. I'm _pretty_ sure I fixed the conflicts correctly, but feel free to revert if I missed something. 

Here's how this looks: 

Mobile|Tablet|Desktop
---|---|---
Screen Shot 2021-05-14 at 11 30 33|Screen Shot 2021-05-14 at 11 30 40|Screen Shot 2021-05-14 at 11 30 13

It's pretty tough to get it looking right on every single breakpoint. I think in general, the goal would be that on tablet and desktop breakpoints, the top rectangle would just slightly overlap the intro text of an article. On mobile, having it take up about half of the viewport seems right. Do you think we can adjust to try aiming for that?

> We could tweak with media queries so the proportions of the squares are different on some viewports (like forcing a max size of the squares for the bigger screens) or adapt the shapes so this issue is a little less prominent.

Yeah, this is a tough problem, but maybe the answer is simple... maybe entry-content has a min-height of 500px or something? That might end up looking really weird, but it's worth a try?

One additional note is that I think it would be cool for non-site-editor users to turn this on or off in the customizer. But we can follow up with that separately if need be.

**Comment by MaggieCabrera** [comment]
> This is looking good! I pushed a quick change to sync up with the header and footer changes. I'm _pretty_ sure I fixed the conflicts correctly, but feel free to revert if I missed something.

Yeah it looks fine to me, thank you.

> On mobile, having it take up about half of the viewport seems right. Do you think we can adjust to try aiming for that?

mmh, I can do that but it will probably mean chaging the clip-path a bit to move it more to the left border of the viewport. Could you do a small mock up so I can copy it the best I can?

> Yeah, this is a tough problem, but maybe the answer is simple... maybe entry-content has a min-height of 500px or something? That might end up looking really weird, but it's worth a try?

It's definitely simpler to change that than play with the clip-path :D

> One additional note is that I think it would be cool for non-site-editor users to turn this on or off in the customizer. But we can follow up with that separately if need be.

The problem with that is how do we carry that customization to the FSE when that's available, I don't think we have tools to do that at the moment.

**Comment by kjellr** [comment]
> > I think in general, the goal would be that on tablet and desktop breakpoints, the top rectangle would just slightly overlap the intro text of an article. On mobile, having it take up about half of the viewport seems right.
> 
> Could you do a small mock up so I can copy it the best I can?

Sure, here's what I'm thinking: 

Desktop|Tablet|Mobile
---|---|---
Polygon Placement (Desktop)|Polygon Placement (Tablet)|Polygon Placement (Mobile)

I'm less concerned about the footer placement — we can take another look at those after we adjust the headers. 

@beafialho do these mockups look alright to you?

**Comment by MaggieCabrera** [comment]
This is what it looks like now. I only adapted the distance between the date/tags and the header for the mobile version:

Desktop | Tablet | Mobile
--- | --- | ---
Screenshot 2021-05-14 at 15 11 09 | Screenshot 2021-05-14 at 15 10 53 | Screenshot 2021-05-14 at 15 10 10

**Comment by kjellr** [comment]
Cool! The mobile and tablet ones are looking good so far. 🌟

**Comment by MaggieCabrera** [comment]
The desktop version adapted to the new design:

Screenshot 2021-05-17 at 09 54 20

**Comment by beafialho** [comment]
> @beafialho do these mockups look alright to you?

These are looking good in general! 

I was wondering if there's a specific reason this square isn't reaching to the corner of the viewport on Desktop?

Captura de ecrã 2021-05-17, às 09 53 32

If it's possible, might be better to have it reach the corner, as shown here:

Captura de ecrã 2021-05-17, às 09 57 23

**Comment by MaggieCabrera** [comment]
> These are looking good in general!
> 
> I was wondering if there's a specific reason this square isn't reaching to the corner of the viewport on Desktop?
> 

Yeah, I just copied Kjell's new design from this comment, that gap is in there: https://github.com/Automattic/themes/pull/3801#issuecomment-841193933

**Comment by kjellr** [comment]
> I was wondering if there's a specific reason this square isn't reaching to the corner of the viewport on Desktop?

Yeah, I liked that little detail, since it clarifies the full shape of the polygon. But I can see how it might look like a mistake. Happy to remove that detail if you'd prefer, @beafialho.

**Comment by beafialho** [comment]
> But I can see how it might look like a mistake. Happy to remove that detail if you'd prefer, @beafialho.

That's what it looked like to me. I see your point, but I think it should look similar to Mobile and Tablet.

**Comment by kjellr** [comment]
Cool, let's expand the shape so that it doesn't leave that little detail then. 👍

**Comment by MaggieCabrera** [comment]
@beafialho @kjellr I rebased this and changed the corner of the polygon on desktop. This is what it looks like with the latest changes to the header and footer spacing:

Screenshot_2021-05-18 Screenshot

**Review by kjellr — APPROVED** [review]
This feels good! Let's merge it in.

**Pull request merged**
