### PR TITLE
Skatepark: typography adjustments from design feedback

### PR DESCRIPTION
**Pull request by MaggieCabrera**
After some design feedback from @melchoyce I went back and amended the typography settings a bit, letter spacings in particular. To test this I used this content:

```
<!-- wp:site-title {"level":3} /-->

<!-- wp:heading {"level":1} -->
<h1>Heading 1 / New Catalogs Available</h1>
<!-- /wp:heading -->

<!-- wp:heading -->
<h2>Heading 2 / New Catalogs Now Available at the NYPL</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3>Heading 3 / New Catalogs Now Available</h3>
<!-- /wp:heading -->

<!-- wp:heading {"level":4} -->
<h4>Heading 4 / New Catalogs Now Available</h4>
<!-- /wp:heading -->

<!-- wp:heading {"level":5} -->
<h5>Heading 5 / New Catalogs Now Available</h5>
<!-- /wp:heading -->

<!-- wp:heading {"level":6} -->
<h6>Heading 6 / New Catalogs Now Available</h6>
<!-- /wp:heading -->

<!-- wp:paragraph {"fontSize":"huge"} -->
<p class="has-huge-font-size">Paragraph Extra Large / Jeffrey Klein is the author of Curious Botany, the most-read blog about rare plants on the internet. He’s the host of the award-winning Embreea Talk podcast from PLNT.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"extra-large"} -->
<p class="has-extra-large-font-size">Paragraph Large / Jeffrey Klein is the author of Curious Botany, the most-read blog about rare plants on the internet. He’s the host of the award-winning Embreea Talk podcast from PLNT.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"medium"} -->
<p class="has-medium-font-size">Paragraph Medium / Jeffrey Klein is the author of Curious Botany, the most-read blog about rare plants on the internet. He’s the host of the award-winning Embreea Talk podcast from PLNT.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"small"} -->
<p class="has-small-font-size">Paragraph Small / Jeffrey Klein is the author of Curious Botany, the most-read blog about rare plants on the internet. He’s the host of the award-winning Embreea Talk podcast from PLNT.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"extra-small"} -->
<p class="has-extra-small-font-size">Paragraph Extra Small / Jeffrey Klein is the author of Curious Botany, the most-read blog about rare plants on the internet. He’s the host of the award-winning Embreea Talk podcast from PLNT.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"tiny"} -->
<p class="has-tiny-font-size">Paragraph Tiny / Jeffrey Klein is the author of Curious Botany, the most-read blog about rare plants on the internet. He’s the host of the award-winning Embreea Talk podcast from PLNT.</p>
<!-- /wp:paragraph -->
```

Result:

Screenshot 2021-08-03 at 18-16-07 Test headings – Site title

### CODE REVIEW

**Comment by melchoyce** [comment]
Minor notes:
- I had the h3 line-height set to 1.4, but seeing it in-browser, I think 1.3 would work a little better
- The Large and XL Paragraph line-height is a bit too high; anything we can do to bring those two down to 1.5 instead of 1.6?

**Comment by MaggieCabrera** [comment]
I can change the heading lineheights but the paragraphs I can't really make a combo of font-size/line-height. The original PR just adds the different font-sizes as options for the users to choose from on the topography panel but they are not tied to a specific line-height, they all just use the line-height that the paragraph block has set up (though they can change this line-height by themselves). We can make that change on block patterns, but that's as far as we can go.

**Comment by melchoyce** [comment]
Okay 👍

**Comment by MaggieCabrera** [comment]
Done! I renamed "small" and "extra small" to "normal" and "small" respectively to be consistent with what blockbase defines (and we didn't have a "normal" font size, which is the one that's used more widely, so It made more sense to do that).

**Review by melchoyce — APPROVED** [review]

**Pull request merged**
