### PR TITLE
Adds a small script to fix all warnings raised by npm modules

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
This is an attempt to fix the warnings raised here: https://github.com/automattic/themes/security/dependabot?page=2&q=is%3Aopen

I created a script which will do it for us automatically...

### CODE REVIEW

**Review by mikachan — COMMENTED** [review]
This is really cool! I ran the script locally and it worked for me. Only thing I can think to add is a shortcut to run the script, maybe something like: `"fix:deps": "./fix-dependencies.sh"` - but I'm also not sure how/where we plan to run this script, so maybe a shortcut isn't needed.

Do we have something similar for keeping the dependencies up to date?

**Comment by scruffian** [comment]
> Do we have something similar for keeping the dependencies up to date?

Not to my knowledge

**Comment by pbking** [comment]
Slightly different take on the task in #4478.  Added batch install, build, audit and version-bump.

**Comment by scruffian** [comment]
Closing in favour of https://github.com/Automattic/themes/pull/4478

**Pull request closed without merging**
