### PR TITLE
Varia: Refactor responsive logic to better support nested blocks with varying widths

### PR DESCRIPTION
**Pull request by allancole**
An even _more_ exhaustive approach to the solution proposed in #1218.

#### Changes proposed in this Pull Request:

- Makes .entry-content 100% wide to let the box-model determine .alignfull widths without negative margins
- .alignwide and _.aligndefault_ widths now have a fixed width, and a responsive 100% max-width
- Improves nested block behaviors and reduces CSS load
- Updates utility classes across the theme to work with this change
- Removes .responsive-max-width utility classes from .entry-content and similar wrappers that no longer need it
- Renames responsive `@extends` and `@mixins` to match Gutenberg pre/suffixes

#### Related issue(s):

If this PR is merged, both #1184 and #1218 can be rejected in favor of this PR.

Fixes: #1241
Fixes: #1192
Fixes: #1254
Fixes: #1252

#### Screenshots

responsive-refactor-1

responsive-refactor-2

### CODE REVIEW

**Comment by iamtakashi** [comment]
@allancole This is awesome improvement. This is definitely on the right direction. There are a few small thing I've noticed.

* Looks like core css stops the inner container of a cover block 70px short from 100%. We would want to change that with the variable.

Screen Shot 2019-08-13 at 11 40 42

* Let's not remove the padding with the negative margin on the last element.

Screen Shot 2019-08-13 at 11 52 10

* The same as above, let's keep the padding so that it's less opinionated, and handle group block like `div`

Screen Shot 2019-08-13 at 11 58 51

**Comment by allancole** [comment]
Added fixes based on your comments above. Let me know if you notices anything else @iamtakashi . 

Before we merge I think we should resync with Master and update all the child themes on this PR. I’ll do that once you’ve approved these last few fixes 👍

**Comment by iamtakashi** [comment]
Awesome, this works nicely, and I like the default 32px padding for Group as well.

> Before we merge I think we should resync with Master and update all the child themes on this PR. I’ll do that once you’ve approved these last few fixes 

Good idea. Hopefully, there won't be too much work for it.

**Comment by allancole** [comment]
Also I think we should merge this _after_ we launch the two themes for this week. That way we can apply the fix to all child themes that are live at once.

**Comment by iamtakashi** [comment]
> Also I think we should merge this after we launch the two themes for this week. That way we can apply the fix to all child themes that are live at once.

Good idea 👍

**Pull request merged**
