### PR TITLE
IP2: add padding control + line height

### PR DESCRIPTION
**Pull request by jffng**
This PR adds support for padding control and line height in IP2. 

Are there any other classic themes we want to do this for? I just picked IP2 because it's still quite actively used. cc @ianstewart 

Part of #2449.

### CODE REVIEW

**Comment by jeffikus** [comment]
We can check the most popular list. @ianstewart we could plan in a short spring for this and do a list of themes?

@jffng any test criteria for this to pass? Just test if the controls are present?

**Comment by jffng** [comment]
@jeffikus yes — I tested with cover and group blocks.

**Review by jeffikus — APPROVED** [review]
LGTM! Ship it!

**Comment by ianstewart** [comment]
Awesome. The list of free themes in this Calypso issue would be good:

https://github.com/Automattic/wp-calypso/issues/52757

**Pull request merged**
