### PR TITLE
Blank Canvas Blocks: Rename to Blank Canvas - only the slug should be renamed

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
I missed this in my review, sorry.

#### Related issue(s):
https://github.com/Automattic/themes/issues/5219

### CODE REVIEW

**Review by zaguiini — APPROVED** [review]
:shipit:

**Review by jeyip — APPROVED** [review]

**Comment by jeyip** [comment]
@scruffian would simply deploying these changes to dotcom fix the naming?

@zaguiini would you mind taking over this work while I'm on holiday vacation?

**Comment by zaguiini** [comment]
Absolutely, @jeyip 👍 

Let me wait until it's merged by @scruffian and I'll publish an update.

**Comment by zaguiini** [comment]
Merging after green light from @scruffian.

**Pull request merged**
