### PR TITLE
Quadrat: add illustrations as starter content

### PR DESCRIPTION
**Pull request by jffng**
#### Changes proposed in this Pull Request:

This PR bundles illustrations as starter content. 

**Testing Instructions**
- Create a fresh site
- Activate Quadrat
- Verify the illustrations appear in the media library

#### Related issue(s):

Partially addresses #4211

### CODE REVIEW

**Comment by scruffian** [comment]
I feel like we should use lower case file names but I'm not sure why! Maybe its a Windows thing?!

**Comment by kjellr** [comment]
> I feel like we should use lower case file names but I'm not sure why! Maybe its a Windows thing?!

Yeah, you're probably right. All the rest of the theme files are lowercase.

**Comment by scruffian** [comment]
I renamed the files. This LGTM

**Review by scruffian — APPROVED** [review]

**Comment by jffng** [comment]
Thank you!

**Pull request merged**
