### PR TITLE
Remote: header

### LINKED ISSUE #5508: Remote: Templates: Header template part (including mobile)
Screenshot 2022-02-10 at 13 49 54

@kjellr should we add the tagline or the site logo to the template part? Or leave that for users to do?

### PR DESCRIPTION
**Pull request by MaggieCabrera**
#### Changes proposed in this Pull Request:

I didn't add any CSS to this PR, let me know if there's anything that needs adjusting.

Screenshot 2022-03-08 at 10 36 06
Screenshot 2022-03-08 at 10 36 22
Screenshot 2022-03-08 at 10 36 29

#### Related issue(s):

Closes https://github.com/Automattic/themes/issues/5508

### CODE REVIEW

**Comment by pbking** [comment]
My navigation sub-menu items don't look like yours...

**Comment by MaggieCabrera** [comment]
> My navigation sub-menu items don't look like yours...
> 
> 

are you on the latest from trunk? I see it black on chrome and FF:

Screenshot 2022-03-11 at 13 05 50

**Comment by pbking** [comment]
Just pulled latest Gutenberg trunk and tested this branch again.  I am still seeing the white sub-navigation elements.

image

Just to make sure I also reset any customizations to my header template and re-created my menu (so that I would have sub-menu items) and got the same result.  

I see that the appropriate value is set I just don't see it getting rendered.

image

Considering that we should bring this in; it's either something funny with my local Gutenberg installation or a bug therein, neither of which should hold up this change.

**Comment by mikachan** [comment]
This is how I can see the sub-menus (and a sub-sub-menu):

image

So I think this looks good to me!

**Review by jffng — APPROVED** [review]
Also LGTM, thanks!

**Pull request merged**
