### PR TITLE
Retrato: fixing after Dotorg review

### PR DESCRIPTION
**Pull request by henriqueiamarino**
Fixing issues mentioned in the Dotorg review process:
- Added underlines to links;
- Standardized the image credits.

https://themes.trac.wordpress.org/ticket/187324#comment:3

### CODE REVIEW

**Review by madhusudhand — COMMENTED** [review]
@henriqueiamarino Could you provide link to the dotOrg review feedback?

Also, theme throws following errors. Could you address them?

`style.css    : Message : missing 'Requires at least' header metadata`

You can view complete list of errors by running `npm run validate:json retrato`.
Note: this script got merged recently. Please run on the changes from latest trunk.

**Comment by henriqueiamarino** [comment]
Thanks, @madhusudhand. I am still trying to figure out what happened. The theme is working fine, with no errors detected by the Theme Check plugin. I'll add it again.

**Comment by henriqueiamarino** [comment]
@madhusudhand, I believe, is working now. At least no errors are visible on the preview link.

**Review by MaggieCabrera — APPROVED** [review]
LGTM

**Comment by henriqueiamarino** [comment]
@MaggieCabrera, here's the demo content file.

[retrato.WordPress.2024-09-12.xml.zip](https://github.com/user-attachments/files/16982264/retrato.WordPress.2024-09-12.xml.zip)

**Pull request merged**
