### PR TITLE
Add Alley-Oop Theme

### PR DESCRIPTION
**Pull request by scruffian**

### CODE REVIEW

**Comment by alaczek** [comment]
This theme needs to be run through theme check plugin, it's throwing a bunch of warnings. Most notably the theme dir name doesn't match the theme slug.

**Comment by MaggieCabrera** [comment]
I fixed the warnings. This theme had dotcom specific code that I haven't seen in any of our other themes. Is this a premium theme by any chance?

This theme also has unsplash images, that are triggering the theme check plugin too

**Comment by iamtakashi** [comment]
> This theme also has unsplash images

I've noticed that, too. With that, this theme should only be on dotcom.

> This theme had dotcom specific code that I haven't seen in any of our other themes. Is this a premium theme by any chance?

There is no mention of it in the post. pNEWy-hMY-p2. It's probably inherited from the base theme he used to build it. Could you tell me where they are? I can clean it up.

**Comment by iamtakashi** [comment]
I'll clean up this theme.

**Comment by iamtakashi** [comment]
OK, I've edited quite a bit of the theme code. Again, we don't submit this theme to Dotorg as it uses Unsplash images. Is it good to go?

**Comment by iamtakashi** [comment]
I'll merge this instead of waiting :) Let me know if there is any problem.

**Pull request merged**
