### PR TITLE
Brute: add theme

### PR DESCRIPTION
**Pull request by henriqueiamarino**
Brute is a theme design inspired by the Brutalist concepts of the homonymous Architectural movement. It aims to be harsh, honest, utilitarian, and useful. It is a good portfolio pick for architects, design studios, and creative organizations.

[Demo site](https://brute.mystagingwebsite.com/)

screenshot

### CODE REVIEW

**Comment by alaczek** [comment]
I've found some issues with the theme:
* custom page-blog.html template isn't necessary.
* there are multiple H1 elements on the homepage used for decorative, rather than semantic purposes, which is an accessibility issue ([see this article for more details](https://www.a11yproject.com/posts/how-to-accessible-heading-structure/))
* there's a broken block in the search template:
image

**Comment by henriqueiamarino** [comment]
@alaczek, I have fixed the following issues on the latest commit:

- Fixed the broken block in the search template;
- Replace images that were using AI to prevent a block;
- New fonts were added to the style variations.

**Comment by MaggieCabrera** [comment]
I made a little fix with the `esc_attr_e`  for this one. I'm a little confused with the images. I see 2 files in the assets, and 1 in the screenshot, but I see 5 in the licenses, can you remove the ones that are unused? Does the theme screenshot need to be updated too?

**Comment by henriqueiamarino** [comment]
@MaggieCabrera, I provided the credits for all the images I use on the homepage. While two of them are packed within the theme, just one is shown on the screenshot. Should I credit only that one? This confuses me sometimes... screenshot is fine, updated.

**Comment by MaggieCabrera** [comment]
I think your commit removed my changes

**Comment by MaggieCabrera** [comment]
And about the credits: you don't need to credit what's on the demo site, only what you can see when you install the theme fresh from these files, that means:

- whatever images you can see on the screnshot
- whatever files are loaded in the assets

And of course we shouldn't load images externally, they should be packaged in the assets files

**Comment by henriqueiamarino** [comment]
Oh no, sorry about that, @MaggieCabrera. Before doing so, I checked the Update Branch button as you instructed me 😔
Anyway, I checked the inevitable html/attr issue you fixed before, and they are present in the latest commit.

**Comment by henriqueiamarino** [comment]
I'll check your fixes and try to reproduce them this afternoon.

**Review by MaggieCabrera — APPROVED** [review]
👍

**Comment by henriqueiamarino** [comment]
@MaggieCabrera, here's the demo content file.

[brute.WordPress.2024-09-12.xml.zip](https://github.com/user-attachments/files/16982294/brute.WordPress.2024-09-12.xml.zip)

**Pull request merged**
