### PR TITLE
Spearhead: Fixes the code and verse blocks in the editor

### PR DESCRIPTION
**Pull request by scruffian**
This fixes the colors of the code and verse blocks in the editor:

Screenshot 2020-10-16 at 15 47 34

Fixes https://github.com/Automattic/themes/issues/2561

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
I thought about doing this but isn't `--global--color-foreground-light` the wrong color for Seedlet?. It's the right one for Spearhead, but Seedlet's body text is actually `--global--color-foreground`. They are extremely similar for Seedlet but it may not be the case for other themes.

**Comment by scruffian** [comment]
Ok, so I'll set it to `--global--color-foreground` in Seedlet and the override it in Spearhead if we need to....

**Comment by MaggieCabrera** [comment]
> Ok, so I'll set it to `--global--color-foreground` in Seedlet and the override it in Spearhead if we need to....

On Spearhead dark mode there is a big difference between them:

```
--global--color-foreground-light: #ffffff;
--global--color-background: #1e1f21;
```

I do agree that defining them in Seedlet too is the best approach for future child themes

**Comment by scruffian** [comment]
I think the root of the problem here is that `foreground-light` is being abused in Spearhead. I think foreground should actually be `ffffff` and foreground-light should be `b2b2b2`, which of course doesn't make sense! I think we need to rename these variables...

I updated this PR to deal with the problem in Seedlet. I'll make a followup one to rename the variable which is going to be a bit more involved!

**Review by MaggieCabrera — APPROVED** [review]

**Pull request merged**
