### PR TITLE
Update theme upsidedown-update

### PR DESCRIPTION
**Pull request by henriqueiamarino**
Massive changes to the current theme
[upsidedown-update.zip](https://github.com/Automattic/themes/files/14955361/upsidedown-update.zip)

### CODE REVIEW

**Comment by mikachan** [comment]
👋 @henriqueiamarino The screenshot in this zip file is 2400px x 1800px - could you please provide one that's 1200px x 900px? Thanks.

**Comment by mikachan** [comment]
I've updated this PR so it's now adding the contents of the attached .zip file. I also ran the theme through Create Block Theme's save process once more.

**Comment by henriqueiamarino** [comment]
I'm sorry, @mikachan. Here's the screenshot. I will fix this in my other themes.
screenshot

**Comment by henriqueiamarino** [comment]
Do you need me to do something else?

**Comment by mikachan** [comment]
No problem, thanks for sending it over so quickly! Otherwise, I think the changes to this theme are looking good 👍

**Pull request merged**
