### PR TITLE
Archeo: fixed font files and styles

### PR DESCRIPTION
**Pull request by MaggieCabrera**
#### Changes proposed in this Pull Request:

I found that the font weights of the font we are using is not looking like the figma files. I see that we are only using one weight in the designs (400 on figma) and that doesn't look like the weight of the font in the browser:

Figma | Google fonts
--- | ---
Screenshot 2022-02-03 at 12 07 49Screenshot 2022-02-03 at 12 07 38 | Screenshot 2022-02-03 at 12 08 03

To follow the design as closely as possible I made the following decisions:

- The body font-weight is 400
- The headings font-weight is 300 (not 400 like figma says)
- I added the bold font file and italics for all 3 weights (300,400,700) so when users change the blocks weights and style it works as intended and it's not the browser forcing the font to do ugly things
- I preloaded the 400 and 300 normal fonts.

This is the content I used for testing:
```

<!-- wp:paragraph -->
<p>This text is the default weight and style</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong>This text has been bolded</strong></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><em>This text is in italics</em></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><strong><em>This text is bold and italic</em></strong></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1} -->
<h1 id="heading-2">HEADING 1</h1>
<!-- /wp:heading -->

<!-- wp:heading -->
<h2 id="heading-2">HEADING 2</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3 id="heading-3">HEADING 3</h3>
<!-- /wp:heading -->

<!-- wp:heading {"level":4} -->
<h4 id="heading-4">HEADING 4</h4>
<!-- /wp:heading -->

<!-- wp:heading {"level":5} -->
<h5 id="heading-4">HEADING 5</h5>
<!-- /wp:heading -->

<!-- wp:heading {"level":6} -->
<h6 id="heading-4">HEADING 6</h6>
<!-- /wp:heading -->

<!-- wp:paragraph {"fontSize":"small"} -->
<p class="has-small-font-size">Paragraph Small. WordPress is software designed for everyone, emphasizing accessibility, performance, security, and ease of use. We believe great software should work with minimum set up, so you can focus on sharing your story, product, or services freely.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"normal"} -->
<p class="has-normal-font-size">Paragraph Normal. WordPress is software designed for everyone, emphasizing accessibility, performance, security, and ease of use. We believe great software should work with minimum set up, so you can focus on sharing your story, product, or services freely.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"medium"} -->
<p class="has-medium-font-size">Paragraph Medium. WordPress is software designed for everyone, emphasizing accessibility, performance, security, and ease of use. We believe great software should work with minimum set up, so you can focus on sharing your story, product, or services freely.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"large"} -->
<p class="has-large-font-size">Paragraph Large.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"huge"} -->
<p class="has-huge-font-size">Paragraph Huge.</p>
<!-- /wp:paragraph -->
```

Figma | Site
--- | ---
Screenshot 2022-02-03 at 12 15 46 | Untitled

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
@beafialho @kjellr I trust your eyes more than mine when it comes to this

**Review by mikachan — COMMENTED** [review]
Thanks so much for working on this!

It looks good to me and I can see the fonts look better in the browser compared to before, and they're closer to Figma. Would definitely like to hear @beafialho's and @kjellr's feedback too.

**Comment by kjellr** [comment]
Thanks for this! It's super-weird that Figma says the incorrect font weight under "Inspect" there. "Light" is definitely the 300 weight. 🤔 

While you're at it, would you mind changing the default body line height (`--wp--custom--body--typography--line-height`) to 1.6 instead of 1.5? That's a change from the comps, but I think it looks far more comfortable in context here. 

Thank you!

**Review by scruffian — APPROVED** [review]
I rebased this so now it's good to go. The only thing I'm not sure about is whether the font weights on the body and headings are correct.

**Comment by kjellr** [comment]
Body + headings appears correct to me. If we could just [followup on this second change](https://github.com/Automattic/themes/pull/5452#issuecomment-1029395152), that would be great.

**Comment by mikachan** [comment]
It looks like the default line height has already been set to 1.6 with the changes on [this line here](https://github.com/Automattic/themes/pull/5452/files#diff-71bd04541f44ec5e5e0558f4a7299fde66db30de1526b63fb08d32096a93faa7R161) (from this PR). @kjellr, does this cover the change you wanted?

**Comment by kjellr** [comment]
Oh yes, sorry. I didn't see that when I reviewed the code originally. All set then, thanks!

**Pull request merged**
