### PR TITLE
Update theme George Lois to Maverick

### PR DESCRIPTION
**Pull request by henriqueiamarino**
Massive changes to the current theme. And a necessary update to the title.
Please change it from **George Lois** to **Maverick**.
[maverick.zip](https://github.com/Automattic/themes/files/14955436/maverick.zip)

This issue is a new version of an existing one, #7592, which is now closed.

### CODE REVIEW

**Comment by henriqueiamarino** [comment]
I will refrain from updating themes for a while. I'll be launching this new version in the Dotorg showcase anytime soon.

**Comment by henriqueiamarino** [comment]
This is a necessary update. I'll be closing all my other update PRs, but this one has to go as Pablo requires—especially regarding the title change.

**Comment by jasmussen** [comment]
Catching up on reviews here. It looks like this PR deletes the entire theme called "george-lois". Is that right? If so, I think it might also need to delete the folders. I can help make that happen, just let me know!

**Comment by henriqueiamarino** [comment]
Thanks for taking care of this, @jasmussen. This is an old but significant PR.
Let's retire this theme before having legal issues with Lois' legal heirs. I'll be launching the new one in the future. After your feedback, I had better ideas to make it more interesting.

**Comment by henriqueiamarino** [comment]
@jasmussen Once you can delete/retire a theme, you may also take care of **Maverick** and **Trailblazer**. They were both merged and blocked in Dotorg due to their existing names.  I'll work on that theme and submit it again under a new name; thank you!

**Comment by jasmussen** [comment]
Okay, just to be sure, for this theme we need to delete the entire folder, correct? If yes, I'll see if I can update this PR to remove all traces of the folder, and then we can look at Maverick and Trailblazer separately.

**Comment by jasmussen** [comment]
Tried to create #7933 as an alternative to this one.

**Comment by henriqueiamarino** [comment]
I am closing this in benefit of #7933.

**Pull request closed without merging**
