### PR TITLE
Feelin'Good: Prepare for the submission.

### PR DESCRIPTION
**Pull request by iamtakashi**
#### Changes proposed in this Pull Request:
- Change the display name
- Update the comment template part
- Optimise the screenshot.png
- Minor style adjustments
- Clean up custom CSS

### CODE REVIEW

**Review by mikachan — APPROVED** [review]
These changes look good and test well for me.

**Comment by iamtakashi** [comment]
@mikachan Thanks for reviewing and merging this. This doesn't seem to be deployed to WP.com, so there are no edits on the version number and readme.txt. Do I need to do anything else?

**Comment by iamtakashi** [comment]
> Do I need to do anything else?

Maybe, did you expect me to run `npm run deploy:version-bump`? I remember we discussed that the script for bumping theme versions will be separated from deploying changes to Dotcom.

**Comment by mikachan** [comment]
We need to run a deploy but there are multiple theme changes queued up, so I'm currently seeing if they can all be deployed at once. It's looking fine I think so this should be deployed soon.

**Comment by iamtakashi** [comment]
OK, thank you for clarifying!

**Comment by mikachan** [comment]
This has been deployed now!

**Comment by iamtakashi** [comment]
Hmm, but no update has been made to the [readme.txt](https://github.com/Automattic/themes/tree/trunk/feelingood), and the version number hasn't increased. Why do you think that is? The deploy process should take care of it, no?

**Comment by mikachan** [comment]
Yes, the deploy process takes care of that. The readme.txt was updated here with a version bump and changelog update: https://github.com/Automattic/themes/commit/738fb07fd914c0d19c633c02f34d5481dfff228b#diff-c0a3fdf16f8cbe4c3fce1dc791968145987dd6dab5e10a8ed46643dc6916215e

**Comment by iamtakashi** [comment]
Oh!? I see them updated now. That's good, I wondered why I couldn't see them when I posted the last comment. Have you experienced something like this?

**Comment by mikachan** [comment]
> Have you experienced something like this?

Not specifically like this, but I'm wondering if you checked the files before the version bump was pushed maybe?

**Comment by iamtakashi** [comment]
Okay, I'm not sure what happened. Anyway, thank you!

**Pull request merged**
