### PR TITLE
Independent Publisher 2: Adjust images styles

### LINKED ISSUE #1786: Independent Publisher 2: Image styles not displayed on front-end
## Steps to replicate

In the Block Editor with Independent Publisher 2 active applied image styles are not properly displayed on the front-end. This appears to affect both Default and Rounded, though it's more obvious with the latter. 

Here's a default image in the editor with pointed corners:

Screen Shot 2020-02-06 at 8 55 02 PM

Here it is with the rounded style:

Screen Shot 2020-02-06 at 8 52 29 PM

And here's how it appears on the front-end for both with slightly rounded corners:

Screen Shot 2020-02-06 at 8 52 44 PM

## Result

The front-end image styling did not match the editor and was unaffected by what was set there.

## Expected

For the front-end styling to match what's shown in the editor. 

* User report: #2694410-zen

### PR DESCRIPTION
**Pull request by nielslange**
Fixes #1786 

<table>
<tr>
<td>Editor before (default)

#1786-editor-before-default
</td>
<td>Editor after (default)

#1786-editor-after-default
</td>
</tr>
<tr>
<td>Editor before (rounded)

#1786-editor-before-rounded
</td>
<td>Editor after (rounded)

#1786-editor-after-rounded
</td>
</tr>
<tr>
<td>Frontend before (default)

#1786-frontend-before-default
</td>
<td>Frontend after (default)

#1786-frontend-after-default
</td>
</tr>
<tr>
<td>Frontend before (rounded)

#1786-frontend-before-rounded
</td>
<td>Frontend after (rounded)

#1786-frontend-after-rounded
</td>
</tr>
</table>

### CODE REVIEW

**Comment by kriskarkoski** [comment]
@nielslange Happy to test, but can you tell me the best way to do that since we don't have PR previews like we do for Calypso? Is the easiest way to download and install the theme with the fix?

**Comment by nielslange** [comment]
@kriskarkoski You can test this change on a local testing site or an AT testing site by taking the following steps:

1. Download the latest version of the theme repo via https://github.com/Automattic/themes/archive/master.zip
2. Unzip that file.
3. Browse to the folder of the Independent Publisher 2 theme and zip that folder
4. Import that theme into your testing site to see the current issue
5. Download the featured branch of the theme repo via https://github.com/Automattic/themes/archive/update/%231786.zip
6. Repeat steps 2. to 4.

These steps allow you to test the PR. You will have to delete the Independent Publisher 2 theme from your site before installing the updated version though.

**Comment by mendezcode** [comment]
✅ Tested, LGTM.

**Comment by mendezcode** [comment]
Deployed in **r55222-wpcom-themes**.

**Pull request merged**
