### PR TITLE
LeanCV: fixes issues mentioned on #8517

### PR DESCRIPTION
**Pull request by henriqueiamarino**
This PR addresses the issues mentioned by @iamtakashi in review #8517.

- The only solution I found for the duotone issue will impact users, I am aware. But I do think this is better than simply removing duotones, which would impact much more the theme's concept;
- Mobile menu set;
- The strong tags were removed;
- Font size presets adjusted, and numeric font values on theme.json were all turned into presets;
- Removed unused template parts;
- Removed unused patterns;
- Fixed Footer padding;
- Checked and fixed all the <main> tags. They are all set to the Content block now;
- Updated readme.txt and style.css for the Version number, Tested Up To, and Requires PHP;
- Removed tags and set the necessary ones.

### CODE REVIEW

**Comment by iamtakashi** [comment]
@henriqueiamarino Thanks for the update! I've pushed [a change](https://github.com/Automattic/themes/pull/8518/commits/04ae122e152cf2e82f6f1db855f992bdc31e76ad) to fix the things that seem overlooked.

* Removed `patterns/hidden-404.php`, `patterns/portrait.php`, and `patterns/self.php`.
* Added `wide-blocks` tag.
* Changed the version number to `1.0.0` inside the changelog.
* Changed the minimum PHP version to 7.0 (it was my fault) in the `readme.txt` and the `style.css`.
* Added back the theme tag `blog` (since the theme description says a blog theme).

--
Now, I noticed the duotoned elements don't change immediately in the editor. (It changes on the front of the site, though) The Professio theme is also suffering from this. You have overcome this issue in AlleyOop and Raconteur. Should we do the same in this theme? 
CleanShot 2024-12-13 at 01 41 23

**Comment by henriqueiamarino** [comment]
Thanks, @iamtakashi. It's really disturbing how some changes I make vanish from the commits. I am 100% sure I noticed those. I did remove those patterns and added <wide-blocks>. That's a bummer. Anyway, yes, the default-duotone replacement works only after you activate the theme.json, for instance, after refreshing the Editor.

Several ready-to-use duotone presets will work for this one, but we should not abandon the unique default duotone technique entirely on other themes. It's helpful, and eventually, the Editor will be faster at displaying that change.

I can add more presets and fix the style variations for this one. It's restrictive for users but probably the faster solution.

**Comment by iamtakashi** [comment]
Beautiful. Thanks, @henriqueiamarino.

I just pushed a change to update the minimum PHP version again. Sorry for being back and forth. It looks like 8.2 will be the minimum PHP version going forward. ([more info](https://github.com/Automattic/themes/issues/7785))

**Comment by iamtakashi** [comment]
I'll merge this and bump up the version. The dotorg version should be updated automatically. I'll launch this on dotcom soon, so it'd be great if you could send me the demo content.

**Pull request merged**
