### PR TITLE
Add PHPCS and PHPCBF to fix linting issues

### PR DESCRIPTION
**Pull request by scruffian**
This adds a PHPCS check before you commit a file. It will also try to automatically fix any issues it finds in the file for you.

It doesn't block you from committing if there are errors. It also doesn't work unless you run `composer install` in your root directory. I hope this means that contributors won't be preventing from committing, while enabling us to improve code quality.

To test:
- run `npm i` in the root of the repo
- then run `composer install`
- make a change to a file
- commit the file
- notice that any problems with the coding standards in the file are reported to you.

### CODE REVIEW

**Review by jffng — COMMENTED** [review]
I encountered a couple issues when running this for the first time:

- `lodash` is required by husky. I resolved this by running `npm i --save-dev lodash` at the root of the repo.
- Upon introducing a change to `seedlet/functions.php` that would result in a coding standards error to be automatically fixed, I received the following output: 

Screen Shot 2020-10-07 at 10 23 31 AM

**Comment by MaggieCabrera** [comment]
I also had to install lodash but I got this when changing `varia/functions.php`:

Screenshot 2020-10-07 at 19 47 02

**Comment by scruffian** [comment]
Thanks for testing. I've fixed those two points.

**Comment by jffng** [comment]
Works for me! As a follow on, should we add something to the readme about this bit of tooling? It doesn't prevent someone from committing so I'm okay to merge as is.

**Comment by scruffian** [comment]
I've added a note to the README about this. I'll p2 it too...

**Comment by MaggieCabrera** [comment]
Thank you for this!

**Comment by kjellr** [comment]
This is excellent, thank you!

**Pull request merged**
