### PR TITLE
Promoter: add theme

### PR DESCRIPTION
**Pull request by henriqueiamarino**
Promoter has a simple structure and displays only the necessary information for a real portfolio. It's ready for designers, artists, architects, and creators to use.
[Demo site](https://promoter.mystagingwebsite.com/)

screenshot

### CODE REVIEW

**Comment by alaczek** [comment]
I'm seeing a few issues with this theme:
* search and archive templates use custom query loop setting which leads to wrong results being displayed (there was an identical issue for Organizer - #8040).
* there are no comments in the single post template.
* single page template doesn't include page title.
* on the homepage, if posts have no featured images, they stick to the line above, which looks off visually.

image

**Comment by henriqueiamarino** [comment]
I've updated the theme following @alaczek's feedback and added some diversity to my style variations.

**Comment by MaggieCabrera** [comment]
I'm reviewing this and making some changes

**Review by MaggieCabrera — APPROVED** [review]
Added some changes to make patterns into templates and fixed main tags and this is good to go!

**Comment by henriqueiamarino** [comment]
@MaggieCabrera, here's the demo content file.

[promoter.WordPress.2024-09-12.xml.zip](https://github.com/user-attachments/files/16982221/promoter.WordPress.2024-09-12.xml.zip)

**Pull request merged**
