### PR TITLE
Quadrat: fixing hover styles for buttons inside the subscribe form

### PR DESCRIPTION
**Pull request by matiasbenedetto**
Hi :wave: 

#### Changes proposed in this Pull Request:
Adding some CSS definitions to:
- Fix the hover style of the buttons rendered by the Jetpack subscribe form
- Fix font-weight in the submit button rendered by the Jetpack contact form

Hover styles fix demo:
hover button

Font-weight fix demo:
font weight

#### Related issue(s):
https://github.com/Automattic/themes/issues/4602

### CODE REVIEW

**Comment by pbking** [comment]
I think there is a jetpack issue opened that will ultimately fix this and allow us to remove these changes.  Make a comment pointing future-us to that change so that we can remove this when appropriate.

**Comment by scruffian** [comment]
Do you think these rules should be in Blockbase?

**Comment by matiasbenedetto** [comment]
I reverted the Quadrat changes and add the fix in Blockbase as @scruffian suggested. I think it looks much better now and it's not a hack we have to revert later.

**Comment by scruffian** [comment]
> it's not a hack we have to revert later.

I still think this is something we'll want to remove from Blockbase eventually, when the Jetpack block is updated.

**Comment by scruffian** [comment]
LGTM

**Review by scruffian — APPROVED** [review]

**Pull request merged**
