### PR TITLE
Jazzers: add theme

### PR DESCRIPTION
**Pull request by vcanales**
A Jazz-inspired theme by @henriqueiamarino

### CODE REVIEW

**Comment by henriqueiamarino** [comment]
I don't know what is wrong with this site @vcanales. I created [this PR](https://github.com/WordPress/gutenberg/issues/50828) to get an answer, but it is still a mystery. On the Editor, everything is in color, nice and sweet. But in the frontend, everything turns to Black and White.

Be my guest to try it [here](https://jazzers.mystagingwebsite.com/wp-admin/site-editor.php)...

**Comment by vcanales** [comment]
I see! Could you export the theme as it is on the demo site so I can look at it locally?

**Comment by henriqueiamarino** [comment]
Sure, @vcanales, here it is!

[the-jazzers.zip](https://github.com/Automattic/themes/files/13888788/the-jazzers.zip) (recently updated)

**Comment by henriqueiamarino** [comment]
@vcanales and @mikachan, I created a version of this theme that works even if the Duotone bug is not fixed correctly. If you want to check the issue, it is [here](https://github.com/WordPress/gutenberg/issues/50828), but it doesn't matter now to the current **Jazzers**.

Can you replace the zip and go on with the launch, please? Thanks!
[jazzers.zip](https://github.com/Automattic/themes/files/14560292/jazzers.zip)

**Comment by henriqueiamarino** [comment]
@MaggieCabrera, here's the demo content file.

[thejazzers.WordPress.2024-09-12.xml.zip](https://github.com/user-attachments/files/16982305/thejazzers.WordPress.2024-09-12.xml.zip)

**Pull request merged**
