### PR TITLE
Videomaker: Update tag styles

### LINKED ISSUE #4844: Videomaker: Update tag styles
Tags in Videomaker should look like this:
Captura de ecrã 2021-10-12, às 15 00 50

They should appear wherever the post-meta template is used.

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
Adds CSS for Post Tags to match the Figma file.

Figma
Screenshot 2021-10-19 at 12 20 54

This PR
Screenshot 2021-10-19 at 12 21 44

#### Related issue(s):
https://github.com/Automattic/themes/issues/4844

### CODE REVIEW

**Review by pbking — DISMISSED** [review]
👍 LGTM

**Comment by pbking** [comment]
The [issue](https://github.com/Automattic/themes/issues/4844#issue-1026684421) notes:  `They should appear wherever the post-meta template is used.`

However the tags aren't present on the index page: 
image

just the page itself:
image

Considering the post-meta is on the index page as well should the tags as well?

**Comment by pbking** [comment]
Oh, actually I see that it's not the `post-meta` template-part being used on the index page.  Should it?

I also see that there IS a slight discrepancy between the spacing of elements on the index page and other pages that @beafialho mentioned earlier due to this difference in method.

**Comment by scruffian** [comment]
I updated this to use the post-meta template on the index.

**Pull request merged**
