### PR TITLE
Add a language file for blank-canvas theme

### PR DESCRIPTION
**Pull request by dlind1**
#### Changes proposed in this Pull Request:

Add a POT file for Blank Canvas theme to ensure that automatic translation processes would run.

Right now every theme should have a POT file in languages/[theme name].pot in order for the translation project to be created in GlotPress instance at translate.wordpress.com and translation files be created.

### CODE REVIEW

**Review by scruffian — APPROVED** [review]
LGTM. Do you need help deploying this?

**Comment by dlind1** [comment]
Looks like it should be a matter of copying the files to the sandbox and creating a diff, then merging/deploying it, correct?

**Comment by scruffian** [comment]
Yes exactly :)

**Comment by dlind1** [comment]
Thanks, done!

**Pull request merged**
