### PR TITLE
Block Canvas: Add no results content to search template

### PR DESCRIPTION
**Pull request by iamtakashi**
The lack of no result contents in the search template was repeatedly mentioned in WP.com, and it'd be nice if Block Canvas resolves the issue, so that it's not necessary for theme designers to handle the case every time.

| Before | After |
| ----------- | ----------- |
| iamtakashi jurassic tube__s=Pneumonoultramicroscopicsilicovolcanoconiosis (1) | iamtakashi jurassic tube__s=Pneumonoultramicroscopicsilicovolcanoconiosis |

I also fixed a minor issue with the tag for `.wp-block-query` in the search template in this PR.

### CODE REVIEW

**Review by mikachan — COMMENTED** [review]
Thanks for doing this!

It looks like there's a package-lock.json included here by mistake, so this should be removed. Otherwise, this is looking good to me.

However, the no results block is not behaving as I expect. It seems that the no results message is always shown regardless of the search results. I've opened an issue in Gutenberg here: https://github.com/WordPress/gutenberg/issues/47793

**Review by mikachan — COMMENTED** [review]
Ugh sorry @iamtakashi, just realised that this is the package-lock.json in the root of the repo. We do commit this, but there shouldn't be any changes to commit as part of this PR.

**Comment by iamtakashi** [comment]
Sorry @mikachan, something went wrong in the initial commit. It should be good now.

**Comment by iamtakashi** [comment]
> However, the no results block is not behaving as I expect. It seems that the no results message is always shown regardless of the search results.

Hmm, interesting, that does sound familiar, but I can't reproduce it now.

**Comment by iamtakashi** [comment]
> but I can't reproduce it now.

I said it too soon 🙂 I can reproduce that now.

**Review by mikachan — APPROVED** [review]
🚢

**Comment by iamtakashi** [comment]
@mikachan Since the theme isn't on WP.com, is it simply to merge it with the button above? Is there anything else we need to do other than merging? It's the first time for me to contribute to Block Canvas.

**Comment by mikachan** [comment]
Yes that's right, with Block Canvas we just need to merge the PR.

**Pull request merged**
