### PR TITLE
Sophisticated Business: Fix excess text side padding for the full wid…

### LINKED ISSUE #916: Sophisticated Business: Excess side paddings in the text column when it's stacked
In small screens, when the block becomes stacked, there is too much side paddings in the text column.

Screen Shot 2019-06-04 at 18 22 30

### PR DESCRIPTION
**Pull request by danieldudzic**
…th stacked Media & Text. Closes #916

### CODE REVIEW

**Comment by iamtakashi** [comment]
It looks good in small screens, but we need some slight adjustments.

Sophisticated has a vertical line on the left of the text with a viewport larger than 1168px.

Screen Shot 2019-06-17 at 14 29 05

So there are three states that effect white space inside the column.
- Small screen (Looks good with this change)
- Tablet https://d.pr/free/i/iQsPTJ
- Desktop https://d.pr/free/i/OoQP0S

**Comment by danieldudzic** [comment]
@iamtakashi Could you please provide some more details on how exactly the table and desktop views should be adjusted?

> Tablet https://d.pr/free/i/iQsPTJ
> Desktop https://d.pr/free/i/OoQP0S

My understanding is, that the space above the text dynamically increases based on the image height.

adjusts_height

**Comment by iamtakashi** [comment]
Sorry for not being extra clear. I was talking about the whitespaces on both sides.

**Comment by iamtakashi** [comment]
I've added further fix, and I also reverted seems-to-be accidental commit for Modern business in this branch.

**Pull request merged**
