### PR TITLE
Erma: Update theme and prepare for Dotorg submission

### PR DESCRIPTION
**Pull request by beafialho**
Changes from WordPress Playground:

- Replaces screenshot with one with the right size
- Adds fonts and images licenses

### CODE REVIEW

**Review by mikachan — APPROVED** [review]

**Comment by mikachan** [comment]
@beafialho It looks like this theme is missing a theme URI too.

**Comment by beafialho** [comment]
Thank you @mikachan, here's the URI: https://themeshaper.com/erma/

**Comment by beafialho** [comment]
I added it here: https://github.com/Automattic/themes/commit/ced809959aedc75bda59985f549ef9bcb324e55a

**Comment by mikachan** [comment]
Thanks @beafialho! I've added the Theme URI to this PR, and I think this is now ready to bring in 🎉

**Pull request merged**
