### PR TITLE
Adonay: Add new theme

### PR DESCRIPTION
**Pull request by jasmussen**
Alternative to #7928. Includes the same changes. Let's see if the playground link works so we can test this.

### CODE REVIEW

**Comment by beafialho** [comment]
Thank you for the review, this looks good to me!

**Comment by beafialho** [comment]
@mikachan do you think it's fine to Squash and merge this one?

**Review by beafialho — APPROVED** [review]

**Comment by mikachan** [comment]
It looks like there are a few `.DS_Store` files that should ideally be removed before merging, but all the other files look good to me 👍

**Comment by jasmussen** [comment]
Given the green check, I'll go ahead and merge this. Kudos Bea!

**Pull request merged**
