### PR TITLE
Blank Canvas: Add the "Subscription Form and Links" pattern

### PR DESCRIPTION
**Pull request by kjellr**
Adds the **Jetpack Subscribe + Links** pattern from https://github.com/Automattic/themes/issues/3161, now that https://github.com/Automattic/jetpack/issues/18085 has been resolved. This PR also properly escapes the wpcom-only block pattern strings + URLs to match up with the changes made in #3345.

Two small caveats: 

- The design is changed slightly from the mockup in the other thread: I've removed the noisy background so that the form field text is more readable.
- It's pretty obvious that the two 50% buttons don't add up to the full width of the container. This is a Gutenberg bug, and there's [a potential fix here](https://github.com/WordPress/gutenberg/pull/29165). I don't think that should hold this PR up though. 

## Screenshots

Editor:

kjellreigstad wordpress com_wp-admin_post php_post=2075 action=edit(1200x900)

Front End:

Desktop|Mobile
---|---
kjellreigstad wordpress com_(1200x900)|kjellreigstad wordpress com_(iPhone X)

### CODE REVIEW

**Comment by jffng** [comment]
I got a block validation error when I added this pattern:

Screen Shot 2021-03-08 at 1 52 12 PM

Clicking "Attempting Block Recovery" worked though.

**Review by scruffian — APPROVED** [review]
LGTM. I didn't see the validation error. The jetpack form looks very different on the front/back but that's outside of the scope of this...

**Comment by kjellr** [comment]
@jffng were you testing on WP.com? I just want to make sure we can't reproduce before merge.

**Comment by jffng** [comment]
Yes — tested on a simple site. I will give it another spin on different site to see if I can still recreate it.

**Comment by jffng** [comment]
Confirm this happens every time I insert the pattern on a sandboxed simple site. This is the console error:

```
index.js:13 Block validation: Block validation failed for `jetpack/subscriptions` (Object).

Content generated by `save` function:

<div class="wp-block-jetpack-subscriptions wp-block-jetpack-subscriptions__supports-newline">
			[jetpack_subscription_form
				subscribe_placeholder="Enter your email address"
				show_subscribers_total="false"
				button_on_newline="false"
				submit_button_text="Sign Up"
				custom_background_emailfield_color="undefined"
				custom_background_button_color="undefined"
				custom_text_button_color="undefined"
				custom_font_size="16"
				custom_border_radius="0"
				custom_border_weight="1"
				custom_border_color="undefined"
				custom_padding="16"
				custom_spacing="10"
				submit_button_classes="has-text-color has-primary-color has-background has-background-background-color"
				email_field_classes=""
				show_only_email_and_button="true"
			]</div>

Content retrieved from post body:

<div class="wp-block-jetpack-subscriptions wp-block-jetpack-subscriptions__supports-newline">[jetpack_subscription_form subscribe_placeholder="Enter your email address" show_subscribers_total="false" button_on_newline="false" custom_font_size="undefinedpx" custom_border_radius="0" custom_border_weight="1" custom_padding="16" custom_spacing="10" submit_button_classes="has-undefinedpx-font-size has-text-color has-primary-color has-background has-background-background-color" email_field_classes="has-undefinedpx-font-size" show_only_email_and_button="true"]</div>
```

**Comment by kjellr** [comment]
@jffng I tried on a couple test sites and was unable to reproduce. Is your sandbox up to date?

**Comment by jffng** [comment]
It was not! Working now 🚢

**Pull request merged**
