### PR TITLE
Skatepark: simplify nav

### LINKED ISSUE #4591: Skatepark: Mobile spacing around social menu is incorrect
Current|Intended
---|---
current|iPhone 8 - 19

Intended margins: 

iPhone 8 - 19

### LINKED ISSUE #4964: Skatepark: Vertical interior spacing in the header is incorrect
I feel like we've already fixed this once or twice. There should be more spacing between the site title and tagline, and also between the menu and the social nav on desktop. 

Please reference the design comps, as those have extensive mockups for how the header should appear. 

Current Dev|Mockup
---|---
Screen Shot 2021-11-02 at 3 33 12 PM|Home

### LINKED ISSUE #4965: Skatepark: Missing space between the social nav and the menu on mobile
~40px is fine. 

Current|Mockup
---|---
Screen Shot 2021-11-02 at 3 35 46 PM|Screen Shot 2021-11-02 at 3 37 25 PM

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
Updates the skatepark nav:

Screenshot 2021-12-13 at 14 50 31
Screenshot 2021-12-13 at 14 50 17
Screenshot 2021-12-13 at 14 50 05

#### Related issue(s):
Fixes https://github.com/Automattic/themes/issues/4965
Fixes  https://github.com/Automattic/themes/issues/4591
Fixes  https://github.com/Automattic/themes/issues/4964

### CODE REVIEW

**Comment by kjellr** [comment]
@scruffian since we can't get the spacing and alignment exactly right using the standard Gutenberg controls, I think we should just borrow this layout for the theme (the same one I'm erroneously seeing in [the Geologist children here](https://github.com/Automattic/themes/pull/5179#issuecomment-992592018)): 

Screen Shot 2021-12-13 at 10 42 19 AM

**Comment by scruffian** [comment]
Ok that's done in 5f862e3

**Review by MaggieCabrera — APPROVED** [review]
Let's bring this in!

**Comment by scruffian** [comment]
I'd like to get @kjellr's 👍 before we merge...

**Comment by kjellr** [comment]
I'm getting a fatal error when I activate Skatepark on this PR: 
Screen Shot 2021-12-14 at 12 26 54 PM

**Comment by pbking** [comment]
> I'm getting a fatal error when I activate Skatepark on this PR:

Odd.  Works on my machine. :P And the code that error seems to be pointing to isn't changed in this branch either.  Not sure what would be causing that.

**Comment by scruffian** [comment]
@kjellr I pushed a change to this, which if it doesn't fix your issue might at least make it easier to determine what the problem is. Would you mind taking a look?

**Comment by kjellr** [comment]
This generally looks good. My only request is that we change the header from `alignfull` to `alignwide` instead. We also need a new screenshot to reflect this change, so I've pushed one to this PR myself. 

Also this isn't a blocker, but do you know why there's so much extra space above the header in the site editor? 

Screen Shot 2021-12-17 at 9 33 23 AM

**Comment by scruffian** [comment]
This is ready for another review. I'll look at the site editor issue separately.

**Review by MaggieCabrera — APPROVED** [review]
🚢

**Pull request merged**
