### PR TITLE
Inversum: add theme

### PR DESCRIPTION
**Pull request by henriqueiamarino**
Inversion is a blog theme designed in the WordPress Site Editor. Its neat visuals introduce a direct experience on post reading: noticeable post titles listed on a text-only page, with an original swap of header and footer blocks.
[Demo site](https://inversum.mystagingwebsite.com/)

screenshot

### CODE REVIEW

**Comment by henriqueiamarino** [comment]
@jasmussen This one, the Upsidedown, has also been reviewed many times. It might be quicker to submit it to the Dotorg review queue.

**Comment by jasmussen** [comment]
Nice, I love this one. The demo text may be a bit over the top, but it's fun!

Very few pieces on this one. I immediately noticed that these things don't fully line up:
Screenshot 2024-07-04 at 11 32 10

Maybe they don't have to?

I'm not sure why, but in the site editor, and only there, there's no top padding on the site:

Screenshot 2024-07-04 at 11 33 45

Love the style variations, I especially like the swedish one, and the dark Noir one. Again a thing for future variations, some typography changes might be nice too.

Readme looks good, templates look good, mobile looks good. Nice one.

**Comment by henriqueiamarino** [comment]
Thanks, @jasmussen. Yes, I've been noticing these misalignments in many themes. I conclude that something has changed in our **Layout** settings, whether Inner blocks use (or not) content width.
Not a big problem, though. I have a quick fix for them.

Would you recommend any topic for a demo content change?

**Comment by henriqueiamarino** [comment]
**I am closing this PR and deleting the branch as I commit unwanted changes. I'll create a new PR.**
This is probably related to issue #7925

**Pull request closed without merging**
