### PR TITLE
Seedlet Blocks - add templateParts theme.json data

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
#### Changes proposed in this Pull Request:

Goes along with - WordPress/gutenberg#28410 - to declare the JSON info for template part sections. This will aid in allowing themes to supply the default taxonomy term used for enabling semantic/categorized template part flows.

#### Related issue(s):
Also opened a PR for the core theme-experiments repo - https://github.com/WordPress/theme-experiments/pull/197

### CODE REVIEW

**Review by jffng — APPROVED** [review]
I tested this on my sandbox by activating Seedlet Blocks on a site with FSE feature flags, and it did not appear to cause any issues.

If it's helpful to merge this for testing, that seems fine to me!

**Review by jeyip — APPROVED** [review]

**Comment by jeyip** [comment]
Should we do this TT1-blocks as well?

**Comment by Addison-Stavlo** [comment]
> Should we do this TT1-blocks as well?

Yup!  I have a PR open on theme-experiments for that. https://github.com/WordPress/theme-experiments/pull/197

**Comment by scruffian** [comment]
Did this get synced to wpcom too?

**Pull request merged**
