### PR TITLE
Beafialho playground changes 2024 05 20 t14 49 00 245 z

### PR DESCRIPTION
**Pull request by jasmussen**
#### Changes proposed in this Pull Request:

This is a clone of #7815 but hopefully with the conflicts fixed. It is intended to replace the other PR.

### CODE REVIEW

**Comment by jasmussen** [comment]
@beafialho can you give a quick look at the theme preview with the Playground link above, see if this matches your expectations? If yes, we can merge this one as a fix! 

From my quick test, this one is ready to go. And I still love this theme, and the 404 page:

Screenshot 2024-07-08 at 14 03 07

**Comment by beafialho** [comment]
Thank you @jasmussen , that looks good to me!

**Comment by jasmussen** [comment]
Cool! My next instinct is to merge this one and close your other PR!

I'll go ahead and do that, and I trust Sarah if you see this and we did wrong, let me know!

**Comment by mikachan** [comment]
Just catching up here - it all looks good to me, and this is definitely a good way to work around conflicts!

**Pull request merged**
