### PR TITLE
Skatepark: typography settings

### LINKED ISSUE #4318: Skatepark: theme.json: Typography settings
Define the typography default settings for Skatepark on theme.json

Desktop:

Styles

Mobile:

Styles – Mobile

### PR DESCRIPTION
**Pull request by MaggieCabrera**
#### Changes proposed in this Pull Request:

This PR establishes typography settings for Skatepark. I have changed on Blockbase (and re-built all the children) because changing the font-weight of the headings blocks takes prevalence over changing the individual heading elements. This seems to be [intentional](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#element-styles). For BB + the previous children the font weight for headings was constant for all the headings, but that's not the case for Skatepark.

To test this you can use this post content and compare it to the [figma file](CA8Gb16mt9yYNWOiVLAWak-fi-980%3A1636):
```
<!-- wp:site-title {"level":3} /-->

<!-- wp:heading {"level":1} -->
<h1>Heading 1 / New Catalogs Available</h1>
<!-- /wp:heading -->

<!-- wp:heading -->
<h2>Heading 2 / New Catalogs Now Available at the NYPL</h2>
<!-- /wp:heading -->

<!-- wp:heading {"level":3} -->
<h3>Heading 3 / New Catalogs Now Available</h3>
<!-- /wp:heading -->

<!-- wp:heading {"level":4} -->
<h4>Heading 4 / New Catalogs Now Available</h4>
<!-- /wp:heading -->

<!-- wp:heading {"level":5} -->
<h5>Heading 5 / New Catalogs Now Available</h5>
<!-- /wp:heading -->

<!-- wp:heading {"level":6} -->
<h6>Heading 6 / New Catalogs Now Available</h6>
<!-- /wp:heading -->

<!-- wp:paragraph {"fontSize":"huge"} -->
<p class="has-huge-font-size">Paragraph Extra Large / Jeffrey Klein is the author of Curious Botany, the most-read blog about rare plants on the internet. He’s the host of the award-winning Embreea Talk podcast from PLNT.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"extra-large"} -->
<p class="has-extra-large-font-size">Paragraph Large / Jeffrey Klein is the author of Curious Botany, the most-read blog about rare plants on the internet. He’s the host of the award-winning Embreea Talk podcast from PLNT.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"medium"} -->
<p class="has-medium-font-size">Paragraph Medium / Jeffrey Klein is the author of Curious Botany, the most-read blog about rare plants on the internet. He’s the host of the award-winning Embreea Talk podcast from PLNT.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"small"} -->
<p class="has-small-font-size">Paragraph Small / Jeffrey Klein is the author of Curious Botany, the most-read blog about rare plants on the internet. He’s the host of the award-winning Embreea Talk podcast from PLNT.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"extra-small"} -->
<p class="has-extra-small-font-size">Paragraph Extra Small / Jeffrey Klein is the author of Curious Botany, the most-read blog about rare plants on the internet. He’s the host of the award-winning Embreea Talk podcast from PLNT.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"tiny"} -->
<p class="has-tiny-font-size">Paragraph Tiny / Jeffrey Klein is the author of Curious Botany, the most-read blog about rare plants on the internet. He’s the host of the award-winning Embreea Talk podcast from PLNT.</p>
<!-- /wp:paragraph -->
```

Desktop:

Screenshot 2021-07-27 at 11-26-37 Typography Test – a8c-wp-env

Mobile:

Screenshot 2021-07-27 at 11-27-01 Typography Test – a8c-wp-env

#### Related issue(s):

Closes https://github.com/Automattic/themes/issues/4318

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
Looks like the Red Hat Display font is not on the list of fonts we have on the customizer and that's popping errors and making the customizer unresponsive. I'm on it.

**Comment by MaggieCabrera** [comment]
This is ready for review again, I added a function to blockbase so that if the theme fonts are not in the ones we defined originally as options to select from, they get added to the selects directly from the theme.json. The other way would be to add them to the $fonts array but that would break if someone wanted to create a child theme of BB that used different fonts too.

This was the error I was getting:

Screenshot 2021-07-28 at 11 08 47

**Comment by pbking** [comment]
Nicely done on the font-adding logic.  I pushed a small change so the value is returned instead of set but it checks out nicely.

(well, it WAS like a 2 line change until phpcs got ahold of it...)
Most of the commit was just code formatting...

**Comment by pbking** [comment]
I think we should have a discussion RE: how we manage those more detailed custom header settings.
Quadrat did (and didn't and did again) the [same thing](https://github.com/Automattic/themes/pull/3824/files#diff-e931f91f2104cfa1b90951136fbb78ebc24d20cd399d6e596831b52d8d39429eR205) for different values for different heading levels.

I'm not sure I'm keen on introducing additional variables in these child themes.  Initially I found it confusing (that they CSS variables that were in the child and not the parent or other themes).

I suggest instead we keep these varying H-level specifics out of 'custom' and exclusively in the block/element stylings. (And suggest cleaning out those same values from Quadrat.)

**Review by pbking — APPROVED** [review]
Reviewed both Quadrat and Skatepark.
Both check out.
LGTM: 🚢

**Comment by melchoyce** [comment]
I'm still not seeing the fonts loading:

image

**Pull request merged**
