### PR TITLE
Varia: Add posts list block support

### PR DESCRIPTION
**Pull request by allancole**
#### Changes proposed in this Pull Request:

This PR adds a default styles and variables to the a8c Posts List block. 

- Optimize selector nesting
- Add style for `featured` span to match archives
- Add vertical spacing to match index/archives
- Add link color to meta data and clean up spacing
- Use small font-size in meta data'
- Also fixes a [responsive image bug](https://github.com/Automattic/themes/compare/varia_add_posts_list_block_support?expand=1#diff-480b74bc7d291227b08c24b6af8b67e4R13), originally reported here: #1085 

#### Related issue(s):

Fixes: #1097 

## Merging note:

Once this PR is merged, we’ll need to re-build all child themes based on Varia, so that they _automatically_ adopt these new styles.

### CODE REVIEW

**Comment by allancole** [comment]
Adding screenshots for clarity.

Before:
image


**After:**
image

**Comment by iamtakashi** [comment]
The only thing I'd note is that we need add top margin of 3 x `vertical`  to the "view all posts" link.

**Comment by allancole** [comment]
The above commit adds vertical spacing as described. I also added the button style to the “View All Posts” link similar to what we commonly used to do with the “Load More Posts” button used in Infinite Scroll.

image

Let me know what you think @iamtakashi

**Comment by iamtakashi** [comment]
Good idea. Thank you, @allancole!

**Pull request merged**
