### PR TITLE
Shawburn: Add color annotations

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
Adds color annotations for Shawburn. To test, load this onto your sandbox and try changing palettes.

### CODE REVIEW

**Comment by pbking** [comment]
If I load the view after applying the change, but have not yet visited the customizer or editor my colors appear to be absent.  

image
image
However, once I click "default" in the customizer the site appears as expected.
I imagine that if I were to [Save Changes] then my view would be working fine (though I have abstained to keep my .com instance in a reproducible state). 
image

**Comment by scruffian** [comment]
Thanks for finding that. I've fixed it in 610fa9c.

**Comment by pbking** [comment]
I found that using the 1st palette the customizer shows a menu color scheme of:
image
while the view:
image

**Comment by pbking** [comment]
When the changes in fix/rgb_to_hslv and add/color-annotations-for-shawburn are combined the issue noted above goes away.  Otherwise I see no further errors.  Once the PR is cleaned up the changes (in both branches) seem G2G.

**Pull request merged**
