### PR TITLE
Brightblog: add theme

### PR DESCRIPTION
**Pull request by henriqueiamarino**
Brightblog is a blog theme with large typography and vibrant color palettes. With its clean and modern design, it offers a unique and engaging way to showcase your blog content.

[Demo site](https://brightblog.mystagingwebsite.com/)

screenshot

### CODE REVIEW

**Comment by jasmussen** [comment]
**General visual observations**

Demo site looks nice, very colorful, bold. 

There's something about the logo here  that isn't quite legible, and the stripes look too similar to the burger menu:

Screenshot 2024-08-02 at 10 31 18

Not a blocker of course, as it's just demo content, just a thought.

One challenge to consider for future themes is to make it behave slightly better when no featured images are set:

Screenshot 2024-08-02 at 10 32 13

There's a fair bit of whitespace to the left of the post, and the heading sticks pretty close to the header in this screenshots. Small fixes could be to simply add some top/bottom padding to the post itself, so that the whitespace feels more intentional and clearly indicated as intentional whitespace.

Should the color of the overlay be set to better match the colors of the site/style variation?

Screenshot 2024-08-02 at 10 34 41

A more general question, _not a blocker_. You've correctly included and use the site logo as the "Home" link. But when no image is set, in this particular design, there's no home link at all:

Screenshot 2024-08-02 at 10 34 11

It's mostly an intereresting question to ponder for us on the block editor site, perhaps. It feels reasonable for a theme to more or less require that a site icon be set, in order to fully work well.

Should these be linked?

Screenshot 2024-08-02 at 10 36 43

Just to #, but just so the visual style (underlined, probably), is more visible.

Mobile looks great.


**Other**

Templates look good.

Style variations are fun. Slightly crazy, but that matches the colorful nature of the theme.

Readme looks good.

**Summary**

This is a fun one. A few tiny things to look at fixing, but we can get this one going, I think.

**Comment by henriqueiamarino** [comment]
Thanks, @jasmussen. I reviewed it following your feedback.

**Comment by jasmussen** [comment]
Changes look good, almost! There's a glitch here:

Screenshot 2024-08-05 at 11 25 44

Pretty sure it's from changes [here](https://github.com/Automattic/themes/pull/7911/commits/d69f4e39e3fe9de2bab87ebc861e395b490df1ca#diff-360cbe880620a023fdca2ce6fe253e681139ee7dac02f2472de22709ecf995bcR16):

So instead of:

```
<?php esc_html_e('<a href="#">Instagram</a>', 'brightblog');?>
```

You can do:

```
<a href="#"><?php esc_html_e('Instagram', 'brightblog');?></a>
```

**Comment by henriqueiamarino** [comment]
CBT has been showing this error for a couple of weeks. All links break like that. Pixel fellows are already informed. I hope they fix it soon.

**Comment by jasmussen** [comment]
@madhusudhand is this a CBT issue, do you know?

**Comment by henriqueiamarino** [comment]
Thanks for following this up, @jasmussen. The manual fix worked fine on the links.

**Comment by madhusudhand** [comment]
> @madhusudhand is this a CBT issue, do you know?

Yes, it is related to https://github.com/WordPress/create-block-theme/issues/573

**Comment by jasmussen** [comment]
Thanks Madhu! 

I guess this PR is good to go then, given you made manual fixes?

**Comment by henriqueiamarino** [comment]
Okay, @jasmussen; thank you once more.

**Pull request merged**
