### PR TITLE
Seedlet: Fix WooCommerce mobile/menu buttons

### LINKED ISSUE #2739: Seedlet: Mobile menu not clickable when WooCommerce activated
When you have WooCommerce activated on a site using Seedlet there is a mobile menu toggle and a mobile WooCommerce cart toggle. The regular mobile menu toggle is not clickable on all devices.

## Steps to replicate

* Activate WooCommerce on a site using Seedlet
* View the site on mobile
* Try to open the regular menu
* Open the cart 

## Results

* The regular menu can't be clicked/opened.

https://d.pr/i/RE5OYQ

* The cart opens but there is a toggle overlap issue.

https://d.pr/i/uLKtL3

## Expected

Both menus should be opened with no overlap issues.

I used the following to resolve but I think there's probably a more complete solution for whatever the actual issue is.

_Is the close button supposed to be on the right side for both menus, or should it be on the left for the cart toggle?_

```
body:not(.primary-navigation-open) #primary-open-menu  {
	position: relative;
	z-index: 1;
}

body.primary-navigation-open #woo-open-menu {
    display: none;
}
```

https://d.pr/i/cNc8cU

* User report: 25257093-hc
* Follow-up ticket: 3448417-zd-woothemes

### PR DESCRIPTION
**Pull request by arcangelini**
#### Live Test Site
https://woocommerce-shipping.mystagingwebsite.com/

#### Before

[Screenshot](https://d.pr/i/Gc2zNG)
- Menu button in mobile is not clickable

#### After

[Screenshot](https://d.pr/i/0AQ74Q)
- Menu clickable

I wasn't sure if the close option for the cart should be on the left side also. I can fix that as well.

```
#woo-close-menu {
    left: 0;
}
```

#### Changes proposed in this Pull Request:

* Set width to `auto` for the menu button containers
* Align main menu button to the right
* Fix element selector for hiding the `open` buttons

#### Related issue(s):
Fixes #2739

### CODE REVIEW

**Comment by scruffian** [comment]
Thanks for this, we'll try to get a review done soon.

**Comment by scruffian** [comment]
@arcangelini sorry it took so long to review. This fix looks good, but I had to move the code to the SASS files so it doesn't get overwritten by future changes. If you're still happy with this then I think we can merge.

**Review by MaggieCabrera — APPROVED** [review]
LGTM

**Comment by arcangelini** [comment]
Oops! Sorry about that, I made the changes in the wrong file. I meant to do them in the SASS files and compile from there. I am trying to get better at remembering that and the versioning. Thanks @scruffian and @MaggieCabrera

**Comment by scruffian** [comment]
We didn't do the versioning in this PR as we're going to do an update to these themes at the end of the week.

**Pull request merged**
