### PR TITLE
Seedlet: Compress the SASS build and add source maps

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
 - Use `clean-css` to compress the css files that we build, to make them smaller for production
- Add source maps to CSS files so that we can see what files the original rules live in

To test:
- Check that you can see the source file in the inspector when looking at CSS rules.
- Check that RTL ignore rules are preserved.

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
I think the rtl ignore rules are not working. 

```
/**
 * .alignright
 */
.alignright {
	/*rtl:ignore*/
	float: right;
	margin-top: 0;
	margin-bottom: var(--global--spacing-vertical);
	/*rtl:ignore*/
	margin-left: var(--global--spacing-horizontal);
}
```

float right is working when the website is in arabic:

Screenshot 2020-10-01 at 11 24 10

**Comment by scruffian** [comment]
I think that's the expected behaviour. The rule is not being changed, so it is being ignored... unless I am missing something?

**Comment by MaggieCabrera** [comment]
Yeah sorry, I was not understanding how that worked!

**Review by MaggieCabrera — APPROVED** [review]
I compared the RTL site with and without the changes and it looked the same. LGTM.

**Comment by jffng** [comment]
> Use clean-css to compress the css files that we build, to make them smaller for production

Out of curiosity, do we have a way of measuring the performance benefit of this change on wpcom?

**Comment by scruffian** [comment]
I decided to remove the CSS minification. I was concerned that removing the comment from the top of style.css might have unintended consequences, and it only saves 20KB. We can look at doing it again in the future, but for me the priority is to have the sourcemap, so I'm merging!

**Pull request merged**
