### PR TITLE
Iotix: add global padding and fix footer

### LINKED ISSUE #6946: iotix: style issues
Found following issues in iotix.

Footer needs a closing tag to avoid block asking for recovery.
image

It requires Root padding
image

Archive page shows single column, but it is expected to have two columns.
image

Search block when inserted in a post vs search template
image
image

CC: @jffng @beafialho

### PR DESCRIPTION
**Pull request by jffng**
#### Changes proposed in this Pull Request:

This PR adds root padding and fixes a block validation error with the footer.

#### Related issue(s):

#6946

### CODE REVIEW

**Review by mikachan — COMMENTED** [review]
The footer looks good with this PR and I'm not seeing the block recovery error, however, on the homepage I'm not seeing any horizontal padding around the post content:

image

I don't think it's related to this PR, but I did think adding the global padding would fix it 🤔 Does it just need to be wrapped in a group?

**Comment by jffng** [comment]
> Does it just need to be wrapped in a group?

This question plagues my existence 😅 

@beafialho Looking at the **home** template for this theme, right now it's a post template block — should we replace this with a pattern or actual blocks?

**Comment by beafialho** [comment]
@jffng are you referring to the home template in [this demo site](https://startuptheme.mystagingwebsite.com)?

**Comment by jffng** [comment]
@beafialho yep! I guess I am not familiar with the approach to make the home template just use a post content block, rather than putting the blocks you want directly into the template (as a pattern or just directly). But I could be out of date or missing some context.

**Comment by beafialho** [comment]
Ah yes! Here's what I did: I created a page called Home, which uses the home template then I set this page as "Front Page" in the reading settings. That way I added and edit the content in the page, not in the template.

**Pull request merged**
