### PR TITLE
Videomaker: Update footer navigation block

### LINKED ISSUE #4961: Videomaker: Adjust footer links spacing + make them uppercase
Let's decrease the spacing between the footer links and make them uppercase by default, to make them look like the designs.

| Currently      | Intended |
| ----------- | ----------- |
|  Captura de ecrã 2021-11-02, às 15 47 46 |      Captura de ecrã 2021-11-02, às 15 43 02 |

### PR DESCRIPTION
**Pull request by mikachan**
#### Changes proposed in this Pull Request:
This PR updates the Videomaker footer navigation block in line with some recent GB updates and adds text decoration and block gap settings. It also fixes a small bug with the footer group block, where some of the brackets were missing from the CSS variables.

Before:
image

After:
image

#### Related issue(s):
Closes #4961

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
With the latest GB trunk, this is not showing vertical for me, also I randomly picked a menu I had that had multiple levels and it looked like this (looks like a GB issue to me):

Screenshot 2021-11-16 at 11 12 21

**Comment by mikachan** [comment]
Ah yeah, the menu isn't showing vertical for me either with the latest GB trunk. Let me see if I can find any related issues, or I'll create one.

**Comment by MaggieCabrera** [comment]
Looks like the markup for this has changed:

`<!-- wp:navigation {"layout":{"type":"flex","setCascadingProperties":true,"orientation":"vertical"}} /-->`

This worked for me on trunk, but we need to find when that change was made and have it in a separate PR so that we can merge only that change when it makes it to dotcom and not before, so it would be out of the scope of this PR

**Comment by MaggieCabrera** [comment]
mmh, the demo site in dotcom is showing this:

Screenshot 2021-11-16 at 11 28 41

Let's make it work on dotcom and then have a PR ready to update with the latest markup if needed

**Comment by mikachan** [comment]
Ahh thanks for finding the new markup.

It looks like the menu is vertical with the old markup on dotcom, I'll go with that for now and start another PR for the new markup. Thanks for your help!

**Review by MaggieCabrera — APPROVED** [review]
Yep! Looking good on the demo site right now, let's update the markup in a followup PR

**Comment by beafialho** [comment]
Just checking if I should still see this in the demo site?

Captura de ecrã 2021-11-18, às 11 26 49

**Comment by mikachan** [comment]
> Just checking if I should still see this in the demo site?

Sorry yes you will, this hasn't been merged yet.

**Comment by beafialho** [comment]
Ok, thanks 👍

**Pull request merged**
