### PR TITLE
Update theme vivre

### PR DESCRIPTION
**Pull request by beafialho**
Changes from WordPress Playground Walkthrough

### CODE REVIEW

**Comment by jasmussen** [comment]
Let me know if you'd like a review of this one. Or should it be closed? Just catching up on old things here.

**Comment by beafialho** [comment]
@jasmussen I don't remember exactly which changes I made to this one but I do remember pinging Sarah about them, and both getting to the conclusion that maybe there were too many drastic changes made to the theme, and that could be disrupting to the sites using Vivre. Perhaps it's wiser to close this one and I'll open a new one in the future.

**Comment by jasmussen** [comment]
I'll trust you to then press the "close with comment" button if you prefer! 

The good thing is, we can always reopen, and restore the file changes, if need be. LMK!

**Comment by beafialho** [comment]
Great, I'll close this one for now.

**Pull request closed without merging**
