### PR TITLE
Multiple themes: add term-description to archive template

### LINKED ISSUE #5753: [Theme: Archeo] Missing term descriptions in category archives
### Quick summary

In its category & tag archives, Theme Archeo **does not show term descriptions** by default:

Screen Shot on 2022-03-25 at 13:42:29

Screen Shot on 2022-03-25 at 13:42:08

### Steps to reproduce

1. Create a term and give it a description.
2. Assign this terms to at least one post.
3. Visit the archive page for that post.

### What you expected to happen

I expected to see the term description at the top of the term archive page.

### What actually happened

The term description was not displayed.

### Context

Testing new themes.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

I am opening this issue regarding **Archeo**, but we should consider making a point of adding term descriptions to all our themes by default. We had the exact same issue with other themes in the past:

https://github.com/Automattic/themes/issues/2793
https://github.com/Automattic/themes/issues/2809

### Browser, operating system and other notes

N/A

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

We can add a term description block manually, but this might be hard to discover for users:

Screen Shot on 2022-03-25 at 13:41:29

I would rather have this term description block added by default to term archives.

### PR DESCRIPTION
**Pull request by madhusudhand**
#### Changes proposed in this Pull Request:

Add term-description block in archive template in the following themes

### Arbutus

image

### Archeo

image

### Blockbase

image

### Remote

image

### Skatepark

image

### Livro

image

### Pendant

image

### Quadrat

image

### Russel

image

### Stewart

image

### Geologist

image

### Zoologist

image

### Videomaker

image

### Block Canvas

image

### Mayland Blocks

image

### Seedlet Blocks

image

#### Related issue(s):

Fixes: #5753

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
I think we need design eyes on this one @kjellr @beafialho

**Comment by beafialho** [comment]
This was not contemplated in the designs to be there by default and, in my opinion, it could be added by users instead if they want to.

**Comment by MaggieCabrera** [comment]
We've added the category descriptions to our themes in the past because classic themes didn't allow the user the possibility for customization, now users can simply add the block themselves to FSE. In my opinion theme designs don't need to include everything all the time.

**Comment by kjellr** [comment]
> This was not contemplated in the designs to be there by default and, in my opinion, it could be added by users instead if they want to.

Yeah, I think it's worth selectively including this block in themes moving forward. But I'd advise against putting it in existing themes. Both for the reason @beafialho shared here, but also because this change would potentially make descriptions appear where they didn't before on live sites. In most cases that would be fine, but I imagine it could be confusing for some users.

**Comment by madhusudhand** [comment]
Closing this base on the above discussion.

**Pull request closed without merging**
