### PR TITLE
Blockbase comments block refactor

### LINKED ISSUE #4515: Blockbase: Refine comments styling
The current comments styling in Blockbase looks quite unfinished:

Screen Shot 2021-08-31 at 11 54 37 AM

This effects all of the child themes (Quadrat, Skatepark, etc.). I'd like to suggest a few minor CSS updates so we can get this into a more workable state: 

Screen Shot 2021-08-31 at 12 00 12 PM

1. Increase vertical spacing between each comment to `calc(1.5 * var( --wp--style--block-gap ))`
2. Increase spacing above and below the comment paragraph content to mimic the normal paragraph block's spacing (`var( --wp--style--block-gap )`)
3. Change the "Reply" button to a text link instead.

### PR DESCRIPTION
**Pull request by MaggieCabrera**
#### Changes proposed in this Pull Request:

This PR refactors the Post comments block for Blockbase and all its children according to what's discussed on #4515 and #4531 
There was some redundant CSS on some of the themes and some that could be refactored into Blockbase to work for all the children.

This is the before and after:

Blockbase:

Before | After
--- | ---
Screenshot 2021-09-07 at 12-53-54 Gutenberg Verse – Skatepark | Screenshot 2021-09-07 at 12-53-32 Gutenberg Verse – Skatepark

Seedlet:

Before | After
--- | ---
Screenshot 2021-09-07 at 12-56-46 Gutenberg Verse – Skatepark | Screenshot 2021-09-07 at 12-56-33 Gutenberg Verse – Skatepark

Mayland:

Before | After
--- | ---
Screenshot 2021-09-07 at 12-55-21 Gutenberg Verse – Skatepark | Screenshot 2021-09-07 at 12-54-57 Gutenberg Verse – Skatepark

Quadrat:

Before | After
--- | ---
Screenshot 2021-09-07 at 12-57-08 Gutenberg Verse – Skatepark | Screenshot 2021-09-07 at 12-57-23 Gutenberg Verse – Skatepark

Geologist:

Before | After
--- | --- 
Screenshot 2021-09-07 at 12-59-13 Gutenberg Verse – Skatepark | Screenshot 2021-09-07 at 12-59-26 Gutenberg Verse – Skatepark

Skatepark:

Before | After
--- | ---
Screenshot 2021-09-07 at 12-58-26 Gutenberg Verse – Skatepark | Screenshot 2021-09-07 at 13-07-48 Gutenberg Verse – Skatepark

#### Related issue(s):

Closes #4515
Partially addresses #4531

### CODE REVIEW

**Comment by kjellr** [comment]
This looks great! Just a few comments: 

1. On second thought, let's make the font size of the reply link smaller. I suggest we match the font size of the comment meta (`0.75em`).
2. Please make sure all of the Reply links are underlined. 
3. On Skatepark, it looks like the comment header isn't lining up correctly with the avatar. See the screenshot below.
4. Seedlet doesn't appear to be indenting its comments properly (this is noticeable in your screenshot above too). 


Skatepark (Broken)|Quadrat (Correct)
---|---
Screen Shot 2021-09-07 at 8 52 11 AM|Screen Shot 2021-09-07 at 8 54 07 AM

Seedlet, without nesting: 

Screen Shot 2021-09-07 at 8 52 45 AM



Thank you!

**Comment by MaggieCabrera** [comment]
> This looks great! Just a few comments:
> 
>     1. On second thought, let's make the font size of the reply link smaller. I suggest we match the font size of the comment meta (`0.75em`).
> 
>     2. Please make sure all of the Reply links are underlined.
> 
>     3. On Skatepark, it looks like the comment header isn't lining up correctly with the avatar. See the screenshot below.
> 
>     4. Seedlet doesn't appear to be indenting its comments properly (this is noticeable in your screenshot above too).
> 

Thanks so much for the quick review! I think I fixed all the points above, this is ready for another review.

**Review by kjellr — APPROVED** [review]
This looks great, thanks Maggie! We may refine more eventually, but this is a great starting point for these, and it's way nicer than what we had before. 🙌

One very tiny thing I noticed in Seedlet Blocks: The spacing above and below each comment should be equal, but right now there's more space at the bottom than at the top: 

Screen Shot 2021-09-07 at 3 45 09 PM

Feel free to fix that here or in a followup PR! Thank you!

**Comment by MaggieCabrera** [comment]
Fixed the last thing and bringing this in

**Pull request merged**
