### PR TITLE
Stratford/Varia: Some color choices are ignored in customizer

### PR DESCRIPTION
**Pull request by DanielSmithMichigan**
| BEFORE (Watch the blue color of the text in the center).        | AFTER.           |
| ------------- | ------------- |
| ezgif-2-b3eb740e088e | ezgif-2-addba23d7eb6 |

### Testing Steps

1. Push this to your sandbox using:
```
cd themes; ./sandbox.sh clean;
```
Then
```
./sandbox.sh push
```
1. Make sure your sandbox is enabled in the hosts file and calypso is using your sandbox in general
1. Create a new site with stratford as the theme
1. Go to the customizer
1. Give the customizer a minute to load.
1. Go to "Colors & Backgrounds"
1. Change colors and notice that they are applied as you change them.

#### NOTE: When you're on the default colors, the very first color change will produce some expected results. But after that change, the color changes will be what you would expect. See this p2 post for more information: pd2qbF-c9-p2

### CODE REVIEW

**Comment by andres-blanco** [comment]
This works on stratford and Varia! 
The good news is that this also seems to fix the problem on other Varia child themes, I tested on 
 * Alves
 * Hever

**Comment by andres-blanco** [comment]
This does fix Hever on Atomic also! 🚀 
| Before | After |
|------|-----|
|  | |

**Review by andres-blanco — APPROVED** [review]
LGTM! This seems to fix a really serious issue (when you click on colors it does nothing) on Varia and (some of) it's children.

**Comment by DanielSmithMichigan** [comment]
D64265-code

**Pull request merged**
