### PR TITLE
Tronar: Add theme

### PR DESCRIPTION
**Pull request by iamtakashi**
#### Changes proposed in this Pull Request:
Add the Tronar theme. pNEWy-hAY-p2

screenshot

### CODE REVIEW

**Review by mikachan — APPROVED** [review]
This looks great to me! Code looks good and theme is testing well for me locally. I think we can merge this, thanks @iamtakashi!

**Comment by iamtakashi** [comment]
Thanks for the quick review, @mikachan ! It's good to know that I should've separated those paddings like that.

**Comment by mikachan** [comment]
> It's good to know that I should've separated those paddings like that.

Oh yes, sorry I meant to mention that. They weren't causing any errors on the front end, I just noticed the JSON schema wasn't happy with them in my editor, so I fixed them.

**Comment by iamtakashi** [comment]
Thank you!

**Pull request merged**
