### PR TITLE
Block-canvas: adding fluid type in theme.json

### PR DESCRIPTION
**Pull request by matiasbenedetto**
#### Changes proposed in this Pull Request:
Block-canvas: adding fluid type in theme.json

#### Related issue(s):
Part of: https://github.com/Automattic/themes/issues/6493

### CODE REVIEW

**Review by mikachan — COMMENTED** [review]
Looking good 👍

Do we want to add any minimum and maximum values to the existing font sizes? The small font size minimum defaults to 12px, which is quite small, so I'd maybe set a minimum for this at 0.813rem. I'm not too opinionated though!

Also, there are a few static font sizes set in theme.json for specific blocks, such as core/comment-content, core/navigation, core/quote, core/site-tagline, core/site-title, h1, h5, and the main body font size. Should we make these fluid as well?

**Comment by pbking** [comment]
The `fontSize` configured that doesn't use one of the preset values seems to be consistently `1.125rem` including the actual default font size for the page (!). I suggest that it should exclusively be using preset (and probably `preset--medium` for those values).

Should preset values have opinionated max/min?  I don't feel strongly that they should, the value it would add is that it's already there for a cloned theme to further tweak.

It's only for that reason that I would also suggest configuring an opinionated global min/max; not because the default values are quite small, but so that the value is already there to change when this theme is cloned.

**Comment by mikachan** [comment]
> It's only for that reason that I would also suggest configuring an opinionated global min/max; not because the default values are quite small, but so that the value is already there to change when this theme is cloned.

I think this is a good idea - provide the values so that they are more easily customizable when using this as a base theme. Maybe we could add them to just one/a few presets as an example of both opinionated min/max values and default calculations?

**Comment by pbking** [comment]
I've added some more fluidity giving (good default I think) examples of how to configure fluidity and also leveraging the size presets instead of values.

**Comment by matiasbenedetto** [comment]
I like the changes regarding the replacement of the custom font size for the CSS vars :+1: 
The examples can be helpful too.
LGTM

**Pull request merged**
