### PR TITLE
Block Canvas: Remove patterns

### PR DESCRIPTION
**Pull request by matiasbenedetto**
#### Changes proposed in this Pull Request:
 I moved the content of the patterns to the templates and removed the patterns from Block Canvas theme.

### Why?
Block Canvas is used as a theme starter to create other themes. Usually, the content of the patterns is overwritten in the templates, and the patterns are no longer used. When the new theme is exported the patterns are included but have nothing to do with the theme created.

### CODE REVIEW

**Comment by mikachan** [comment]
@iamtakashi @beafialho @henriqueiamarino Do you still use Block Canvas as a base theme, and would these changes improve your theme workflow?

**Comment by beafialho** [comment]
I still use Block Canvas as a base theme, yes. If removing the patterns will simplify the process and files, I think it's a good change.

**Comment by iamtakashi** [comment]
I don't use Block Canvas any more, but this is a good idea for a base theme 👍👍👍

**Comment by henriqueiamarino** [comment]
Just like @beafialho, I still use it, and if these changes make things better, I am OK with them.

**Comment by mikachan** [comment]
Thanks for the feedback, all! In that case, I think we should bring this in.

**Review by mikachan — APPROVED** [review]

**Pull request merged**
