### PR TITLE
Update the gold variation typography

### PR DESCRIPTION
**Pull request by Imran92**
#### Changes proposed in this Pull Request:
- Go to Appearance -> Themes and activate the Course theme.
- Go to Appearance -> Editor -> Templates -> Lesson (Learning Mode - Default).
- Click Styles -> Browse Styles -> Gold, click Save.
- Compare the typography with the design. Use an HTML vs Design tool ([example](https://chrome.google.com/webstore/detail/pixelparallel-by-htmlburg/iffnoibnepbcloaaagchjonfplimpkob?hl=en)) because the CSS provided by the Figma design is not always accurate (mainly for letter spacing).

#### Related issue(s):
Resolves https://github.com/Automattic/themes/issues/7122

### CODE REVIEW

**Review by m1r0 — COMMENTED** [review]
It looks like some of the typography still needs an update. Here's a list of what I've found:

* `sensei-lms/course-title` - Uses system font instead of Montserrat.

* `sensei-lms-course-navigation-module__title` - Uses system font instead of Montserrat.
image
* `sensei-lms-course-navigation-lesson__title` - Uses system font instead of Montserrat.

* `wp-block-sensei-lms-course-theme-lesson-module` - Uses system font instead of Montserrat.
* `wp-block-post-title` - The letter spacing can be improved.

* `wp-block-post-content` - The letter spacing can be improved.

* `.wp-element-button` - The letter spacing can be improved.

* `wp-block-sensei-lms-page-actions` (pagination) - The font-weight can be improved.

**Comment by Imran92** [comment]
Thanks for the review @m1r0 ! I'm looking into the issues you've mentioned. I guess the fonts depended on this https://github.com/Automattic/sensei/pull/6823, which was merged yesterday. Can you kindly check if having that PR in place in sensei fixes the fonts for you?

**Comment by Imran92** [comment]
I've made some changes here https://github.com/Automattic/themes/pull/7047/commits/ffe0813ac21fa324bcf3032a679f9d27ffaadcea

Here's how they're looking for me locally with pixelparallel
Screen Shot 2023-05-06 at 12 18 43 AM
Screen Shot 2023-05-06 at 12 19 13 AM

Screen Shot 2023-05-06 at 12 17 15 AM
Screen Shot 2023-05-06 at 12 17 34 AM
Screen Shot 2023-05-06 at 12 17 54 AM
Screen Shot 2023-05-06 at 12 18 21 AM

Screen Shot 2023-05-06 at 12 16 45 AM

**Comment by merkushin** [comment]
Could you help me, please? :) What am I doing wrong?
I use `feature/learning-mode-improvements` (fresh, assets built) for sensei and this branch for the theme. I reset styles, then applied Gold variation.
But typography looks wrong. I mean it looks even different from your screenshots.
Here is the most noticeable example (that's the module name above the lesson title):
CleanShot 2023-05-09 at 02 26 34@2x
Upd. The same when I'm trying Miro's PRs.

**Comment by merkushin** [comment]
I see the difference for the title, but we found that spacing between words depends on the screen resolution. Probably, that's why I see it that way.
CleanShot 2023-05-09 at 12 06 00@2x

However, the pagination is thinner.
CleanShot 2023-05-09 at 12 10 04@2x

**Comment by Imran92** [comment]
Thanks for the review @merkushin, I've updated the pagination here https://github.com/Automattic/themes/pull/7047/commits/f66670d95fd457439931fa798fa18df56da0cf25, can you take another look? Thanks

**Comment by m1r0** [comment]
@merkushin Maybe you didn't re-apply the variation after switching to this branch? Or maybe you have some custom settings applied that are overwriting the variation settings?

@Imran92 I've noticed that the font-size is different on different viewport sizes. For example, the `wp-block-sensei-lms-course-title` font-size is 16px on 1920px viewport but on 1500px viewport the font-size is 15.75px. When doing html-vs-desing, this looks like a letter-spacing issue. Maybe that's why we see it differently? 🤷 

I'm still noticing the following when testing on 1920px:

* `sensei-lms/course-title` - Has the correct font now but the letter-spacing is off a bit. `letter-spacing: 0.002em;` -> `letter-spacing: -0.01em;`



* `sensei-lms-course-navigation-module__title` - Still uses system font instead of Montserrat.

image

* `sensei-lms-course-navigation-lesson__title` - Still uses system font instead of Montserrat.

image

* `sensei-lms-course-navigation-lesson__extra` - Uses system font instead of Montserrat.

image

* `wp-block-sensei-lms-course-theme-lesson-module` - Uses system font instead of Montserrat.

image

* `wp-block-post-title` - Uses different letter spacing.

image

* `post-content` - Uses different letter spacing. `letter-spacing: -0.004em;` -> `letter-spacing: -0.01em;`

* `post-content` - On mobile, the font-size should be 16px.

* `buttons` - On mobile, the font-size should be 14px.

**Comment by m1r0** [comment]
Forgot to mention that I'm testing on the most recent changes on the `feature/learning-mode-improvements` sensei branch.

**Comment by Imran92** [comment]
Thanks for the review @m1r0 ! I've updated the font families. Also the font sizes for the content and the button are fixed [here](https://github.com/Automattic/themes/pull/7047/commits/3b4ea083fbdf3eb5569551bf6d317b5a4a287e18).

For the letter spacings of post content and post title, they are appearing perfectly on my setup on 1920px. Can you kindly take a look again?

Screen Shot 2023-05-11 at 4 01 48 PM

Screen Shot 2023-05-11 at 4 00 16 PM

**Comment by m1r0** [comment]
Nice! Thanks for the update.

I've noticed that the global styles for the post-title and the post-content are not working. Is it possible to make them work following Donna's [global styles guide](https://href.li/?https://wp.me/p6rkRX-6hi)? Or maybe we should merge and make another card for fixing the global styles? cc @merkushin 

> For the letter spacings of post content and post title, they are appearing perfectly on my setup

I have no idea why we see it differently, but I'm ok with merging as is. We don't have to focus that much on details. 👍

**Comment by Imran92** [comment]
Thanks @m1r0 ! I've updated it [here](https://github.com/Automattic/themes/pull/7047/commits/473b1fe2aa66c73bec4ab53744b39246098a9b94)

**Review by m1r0 — APPROVED** [review]
Looks good! 

We're not able to apply global styles on some of the Sensei blocks but I feel that would be somewhat hard to do with the provided design and will require a refactoring of the theme.json. We can open a separate card for it if we decide it's a priority.

**Pull request merged**
