### PR TITLE
Quadrat: mobile post header with featured image

### LINKED ISSUE #3897: Quadrat: Update Meta/Title spacing on small screens
Really minor, but can we trim `20px` from the vertical spacing between the post meta and the title on mobile views? They feel a little far apart to me there. It can stay as is on larger screens. 

Before|After
---|---
Screen Shot 2021-05-20 at 1 41 08 PM|Screen Shot 2021-05-20 at 1 41 44 PM

### PR DESCRIPTION
**Pull request by MaggieCabrera**
#### Changes proposed in this Pull Request:

The mobile version of the post header was causing issues with a featured image, I went to the figma and saw that this has been designed already and I tried my hand at reproducing the same design as close as possible. I'm using `object-fit: cover;` here so I'm manipulating a bit how the image looks like compared to desktop. I'd love design eyes on this if possible @beafialho @kjellr 

I went ahead and did the change for the spacing between the post meta and the post title in the same PR.

Figma | Site
--- | ---
Screenshot 2021-05-21 at 09 43 41 | Screen Capture on 2021-05-21 at 09-45-31(1)

#### Related issue(s):

Closes #3896
Closes #3897

### CODE REVIEW

**Comment by beafialho** [comment]
Thanks @MaggieCabrera! The spacing looks good to me, the only comment is that there should be a square behind the post title and meta, overlapping the featured image.

Captura de ecrã 2021-05-21, às 12 37 56
Captura de ecrã 2021-05-21, às 12 38 11

**Comment by MaggieCabrera** [comment]
Mmmh, I'm looking at the desktop version of the post with a featured image and that rises more questions:

- I checked @kjellr [opened this issue](https://github.com/Automattic/themes/issues/3804) to change how posts with featured images should look like and that deviates from this design (and also doesn't include the square)
- I'm a bit hesitant about including the square using CSS because that will mean the user can't remove it if they don't want it. I could probably make it a block style but that won't be available for the users to change until FSE is available to them (I'm still unsure if dotcom is including the FSE for users or not when 5.8 lands).

**Comment by beafialho** [comment]
Oh I see, I missed that issue. In that case, I think what you have here looks good.

**Comment by kjellr** [comment]
Hey sorry I missed this PR. I think we should revert, because the site title and menu can very easily become unreadable depending on the featured image used: 

quadrat

**Pull request merged**
