### PR TITLE
Bibimbap: optimise images and add credits

### LINKED ISSUE #6811: Bibimbap: Compress images
### Quick summary

Many of the images included in Bibimbap have a pretty large file size:

image

The screenshot.png file is also 1.7MB. We should compress these images so they're web-ready.

### Steps to reproduce

N/A

### What you expected to happen

N/A

### What actually happened

N/A

### Browser

_No response_

### Context

_No response_

### Platform (Simple, Atomic, or both?)

_No response_

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by madhusudhand**
#### Changes proposed in this Pull Request:

* Optimise and remove unused images.
* Add image credits to readme

Note: `bibimbap/assets/images/bibimbap-image.png` doesn't compress `1.31 MB` and left it to this size as it is used in custom template and shouldn't effect normal theme experience.

#### Related issue(s):

fixes #6811
also relates to #6801

### CODE REVIEW

**Comment by jffng** [comment]
Thanks @madhusudhand. This LGTM. 

One question:

> Note: bibimbap/assets/images/bibimbap-image.png doesn't compress 1.31 MB and left it to this size as it is used in custom template and shouldn't effect normal theme experience.

Will this break wpcom's recommendation to keep images under 500kb, since this file will be copied to every site that activates the theme?

**Comment by madhusudhand** [comment]
@beafialho The image `https://www.foodiesfeed.com/free-food-photo/korean-meal-from-above/` could not be compressed to less then `500kb` because of the the many colors and dimensions. Do you have any suggestions to replace it with?

**Comment by beafialho** [comment]
@madhusudhand I'm not sure I understand, the theme already has the images resized and compressed.

**Comment by madhusudhand** [comment]
@beafialho following are the image sizes before and after this PR. 
(assets from [here](pNEWy-fLt-p2#comment-55434)).

image

image

`bibimbap-image` is at its most compressed state yet it takes `1.4` megabytes.

**Comment by beafialho** [comment]
@madhusudhand oh, I understand. Thanks for clarifying. Here's an alternative:

bibimbap_image

**Comment by madhusudhand** [comment]
Thanks @beafialho 
Updated the new image and merging the changes.

**Pull request merged**
