### PR TITLE
Try: George Lois theme: Delete the whole thing.

### PR DESCRIPTION
**Pull request by jasmussen**
#### Changes proposed in this Pull Request:

Alternative to #7733. Deletes the George Lois theme, with the intent to add a different-name version of the same.

### CODE REVIEW

**Comment by jasmussen** [comment]
Let me know if I did this right Sarah/Henrique!

**Review by mikachan — COMMENTED** [review]
I can see this removes the `george-lois` theme directory, which is correct if we want to remove this theme entirely.

However, I can see the George Lois theme still exists on dotcom, so we probably need to coordinate there first before deleting the theme from this repo. cc @miksansegundo

**Comment by miksansegundo** [comment]
Hi, I believe we have to retire the theme from Dotcom first. @alaczek, will you create a task for retiring it?

cc: @dsas I don't have experience retiring themes. There is a guide at PNEWy-tR-p2

**Comment by dsas** [comment]
@miksansegundo agreed that we need to retire the theme but we don't need to block this PR to do it. The sync script won't delete the theme directory from dotcom, even though it gets removed in this repo (we should carefully double check this when syncing though).

**Comment by jasmussen** [comment]
Thanks for the input. What's the next step here, then? Delete the folder? Maverick is already present, same theme: https://github.com/Automattic/themes/tree/trunk/maverick

**Comment by miksansegundo** [comment]
Yes, it seems that you can merge this PR safely and later we'll retire the theme from Dotcom.

**Comment by jasmussen** [comment]
Cool, thanks for the help. @henriqueiamarino should we merge this one and close #7733?

**Comment by henriqueiamarino** [comment]
Ok, thanks @jasmussen. I'm merging it.

**Review by henriqueiamarino — COMMENTED** [review]
Everything is fine here, merging the PR.

**Pull request merged**
