### PR TITLE
Update Navigation Alignment for popular themes

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request:
The following themes have right aligned navigation in their overlay which is probably not the intended design. This PR switches them to be left aligned.

- Foam
- Adventurer
- Lativ
- Bibimbap
- Startfit
- Erma
- Jaida

## Screenshots
Before
Screenshot 2023-12-21 at 13 45 04
After
Screenshot 2023-12-21 at 13 45 17
Before
Screenshot 2023-12-21 at 13 43 27
After
Screenshot 2023-12-21 at 13 43 38
Before
Screenshot 2023-12-21 at 13 47 59
After
Screenshot 2023-12-21 at 13 37 43
Before
Screenshot 2023-12-21 at 13 35 06
After
Screenshot 2023-12-21 at 13 34 55
Before
Screenshot 2023-12-21 at 13 29 39
After
Screenshot 2023-12-21 at 13 29 28
Before
Screenshot 2023-12-21 at 13 37 50
After
Screenshot 2023-12-21 at 13 48 21
Before
Screenshot 2023-12-21 at 13 46 18
After
Screenshot 2023-12-21 at 13 46 59
Before
Screenshot 2023-12-21 at 13 19 18
After
Screenshot 2023-12-21 at 13 18 46
Before
Screenshot 2023-12-21 at 13 50 40
After
Screenshot 2023-12-21 at 13 50 58

### CODE REVIEW

**Comment by iamtakashi** [comment]
I personally prefer the left-aligned navigation, so 👍 from me. Some users who liked the right-aligned nav might complain, though.

I am pinging other theme authors @beafialho @henriqueiamarino for input.

**Comment by beafialho** [comment]
I also prefer the left-aligned navigation as default 👍

I know this is outside the scope of this PR, but just throwing in an ideal scenario for the future: being able to choose whether navigation menu items on overlay are left or right aligned.

**Comment by scruffian** [comment]
> I know this is outside the scope of this PR, but just throwing in an ideal scenario for the future: being able to choose whether navigation menu items on overlay are left or right aligned.

We were looking at this in https://github.com/WordPress/gutenberg/pull/55657 but it's got stuck so I thought a quick fix would be good for now.

**Comment by jeffikus** [comment]
These themes are active on production sites - this isn't a fix for those people imo. This is a visual change and they could see this as a regression. They should be able to retain their existing alignment, while fixing it to the intended style.

**Comment by ianstewart** [comment]
> Some users who liked the right-aligned nav might complain, though.
>
> These themes are active on production sites - this isn't a fix for those people imo. This is a visual change and they could see this as a regression. They should be able to retain their existing alignment, while fixing it to the intended style.

Plus one.

**Pull request closed without merging**
